import {createAdminClient} from "@/lib/supabase/admin";
import {BlockHelpButton} from "@/components/GuidedTour";
import {inviteAdvisor} from "../actions";

type Props={searchParams:Promise<{invite?:string;email?:string}>};

export default async function UsersPage({searchParams}:Props){
 const supabase=createAdminClient();
 const{data:profiles}=await supabase.from("profiles").select("id,full_name,role,system_role,phone,created_at").order("created_at",{ascending:false});
 const params=await searchParams;const sent=params.invite==="sent"&&params.email;
 return <main className="admin-shell">
  <header className="admin-header"><div><span className="eyebrow">FELHASZNÁLÓK</span><h1>Szerepkörök és rendszerjogok</h1><p>A szakmai szerepkör és a rendszeradminisztrátori jogosultság elkülönül. A rendszeradmin nem használja a szaktanácsadói munkateret.</p></div></header>
  <section className="panel" data-help-block="system-user-invite" style={{marginBottom:16}}><div className="panel-heading"><div><h2>Szaktanácsadó meghívása</h2><p>A meghívás csak friss kétfaktoros hitelesítéssel és rendszeradminisztrátori jogosultsággal hajtható végre.</p></div><BlockHelpButton label="A szaktanácsadó-meghívás magyarázata" content={{title:"Szaktanácsadó meghívása",body:"Ebben a blokkban új szaktanácsadói felhasználót hívhatsz meg név és e-mail cím megadásával. A meghívás rendszeradminisztrátori művelet, és nem azonos gazdálkodó vagy gazdaság létrehozásával.",important:"A meghívás csak megfelelő rendszeradmin jogosultsággal és friss kétfaktoros hitelesítéssel hajtható végre. Rendszeradmin jogot ezen az űrlapon nem osztunk ki."}}/></div>
   {sent?<div className="notice" style={{marginBottom:16}}><strong>Meghívó elküldve:</strong> {params.email}</div>:null}
   <form action={inviteAdvisor} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,alignItems:"end"}}><label>Név<input name="full_name" autoComplete="name" placeholder="Szaktanácsadó neve" style={{display:"block",width:"100%",marginTop:6}} /></label><label>E-mail<input name="email" type="email" autoComplete="email" required placeholder="nev@pelda.hu" style={{display:"block",width:"100%",marginTop:6}} /></label><button type="submit">Szaktanácsadó meghívása</button></form>
  </section>
  <section className="panel" data-help-block="system-user-register"><div className="panel-heading"><div><span className="eyebrow">FELHASZNÁLÓI NYILVÁNTARTÁS</span><h2>Felhasználók és jogosultságok</h2></div><BlockHelpButton label="A felhasználói nyilvántartás magyarázata" content={{title:"Felhasználók és rendszerjogok",body:"A táblázat a rendszerben lévő felhasználókat, szakmai szerepüket, rendszerjogukat, telefonszámukat és létrehozási idejüket mutatja. A szakmai szerep azt jelzi, hogy gazdálkodó vagy szaktanácsadó; a rendszerjog ettől külön kezeli a rendszeradminisztrátori hozzáférést.",important:"A rendszeradmin jogosultság kritikus hozzáférés, ezért nem módosítható egyszerű kapcsolóval ebből a listából. A szakmai szerepkör és a rendszeradmin jogosultság két külön jogosultsági réteg."}}/></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:10}}>Név</th><th style={{textAlign:"left",padding:10}}>Szakmai szerep</th><th style={{textAlign:"left",padding:10}}>Rendszerjog</th><th style={{textAlign:"left",padding:10}}>Telefon</th><th style={{textAlign:"left",padding:10}}>Létrehozva</th></tr></thead><tbody>{(profiles??[]).map(p=><tr key={p.id} style={{borderTop:"1px solid #eee1e3"}}><td style={{padding:10}}><strong>{p.full_name||"Névtelen felhasználó"}</strong><small style={{display:"block",color:"#75666a"}}>{p.id}</small></td><td style={{padding:10}}>{p.role==="advisor"?"Szaktanácsadó":"Gazdálkodó"}</td><td style={{padding:10}}><b style={{color:p.system_role==="admin"?"#922b36":"#75666a"}}>{p.system_role==="admin"?"Rendszeradmin":"Normál"}</b></td><td style={{padding:10}}>{p.phone||"—"}</td><td style={{padding:10}}>{p.created_at?new Date(p.created_at).toLocaleDateString("hu-HU"):"—"}</td></tr>)}</tbody></table></div><div className="notice" style={{marginTop:16}}>Adminjog kiosztását szándékosan nem tesszük egyszerű kapcsolóvá ezen az oldalon. A jogosultság-emelés kritikus művelet, ezért külön friss MFA-val védett folyamatként kezelendő.</div></section>
 </main>
}
