import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {AdminNav} from "@/components/AdminNav";
import {decodeSupervisionConfig,defaultSupervisionConfig,SUPERVISION_EVENT,supervisionLabel} from "@/lib/supervision";
import {saveSupervisionConfig} from "./actions";

export default async function AdminSupervisionPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="advisor")redirect("/dashboard");
 const[{data:farms},{data:events}]=await Promise.all([supabase.from("farms").select("id,name,owner_id").order("name"),supabase.from("timeline_events").select("id,farm_id,description,event_at,created_at").eq("event_type",SUPERVISION_EVENT).order("event_at",{ascending:false}).limit(500)]);
 const latest=new Map<string,any>();for(const e of events??[])if(e.farm_id&&!latest.has(e.farm_id))latest.set(e.farm_id,e);
 return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">SZAKTANÁCSADÁSI IDŐSZAKOK</span><h1>Szemlézési szezonok</h1><p>A gazdálkodói napló egész évben működik. Itt csak azt állítod be, mikor várjon el a rendszer rendszeres szaktanácsadói szemlét.</p></div></header><AdminNav active="supervision"/>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">GAZDASÁGONKÉNT</span><h2>Aktív felügyeleti időszakok</h2></div></div><div style={{display:"grid",gap:14}}>{(farms??[]).map(f=>{const event=latest.get(f.id),cfg=decodeSupervisionConfig(event?.description)||defaultSupervisionConfig;return <article key={f.id} style={{border:"1px solid #dfe5df",borderRadius:14,padding:16,background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><strong style={{fontSize:16}}>{f.name}</strong><small style={{display:"block",marginTop:4,color:"#6f7c74"}}>{supervisionLabel(cfg)}</small>{cfg.note&&<small style={{display:"block",marginTop:3,color:"#879087"}}>{cfg.note}</small>}</div><span className="user-pill">{cfg.enabled?"Automatikus figyelés":"Kikapcsolva"}</span></div><form action={saveSupervisionConfig} style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:10,marginTop:14}}><input type="hidden" name="farm_id" value={f.id}/><label style={{fontSize:12,fontWeight:800}}>Szezon kezdete<input name="active_from" defaultValue={cfg.activeFrom} pattern="\d{2}-\d{2}" placeholder="03-15" style={{width:"100%",marginTop:5,padding:10,border:"1px solid #dfe5df",borderRadius:9}}/></label><label style={{fontSize:12,fontWeight:800}}>Szezon vége<input name="active_to" defaultValue={cfg.activeTo} pattern="\d{2}-\d{2}" placeholder="10-31" style={{width:"100%",marginTop:5,padding:10,border:"1px solid #dfe5df",borderRadius:9}}/></label><label style={{fontSize:12,fontWeight:800}}>Elvárt szemleciklus<input name="inspection_interval_days" type="number" min="1" max="365" defaultValue={cfg.inspectionIntervalDays} style={{width:"100%",marginTop:5,padding:10,border:"1px solid #dfe5df",borderRadius:9}}/></label><label style={{fontSize:12,fontWeight:800,display:"flex",alignItems:"center",gap:8,paddingTop:25}}><input name="enabled" type="checkbox" defaultChecked={cfg.enabled}/> Automatikus szemlefigyelés</label><label style={{gridColumn:"1/-1",fontSize:12,fontWeight:800}}>Megjegyzés<input name="note" defaultValue={cfg.note||""} placeholder="pl. téli időszakban nincs rendszeres szemlézés" style={{width:"100%",marginTop:5,padding:10,border:"1px solid #dfe5df",borderRadius:9}}/></label><button className="btn btn-primary" type="submit" style={{justifySelf:"start"}}>Beállítás mentése</button></form></article>})}</div></section></main>
}
