"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

async function canManageFarm(supabase:any,userId:string,farmId:string){const{data:farm}=await supabase.from("farms").select("owner_id").eq("id",farmId).maybeSingle();if(!farm)return false;if(farm.owner_id===userId)return true;const{data:p}=await supabase.from("profiles").select("role").eq("id",userId).maybeSingle();if(p?.role==="advisor")return true;const{data:m}=await supabase.from("farm_members").select("id").eq("farm_id",farmId).eq("user_id",userId).eq("active",true).in("member_role",["manager","agronomist"]).maybeSingle();return!!m}
function num(v:FormDataEntryValue|null){const s=String(v||"").trim().replace(",",".");if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null}
export async function saveMachine(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const id=String(formData.get("id")||""),farmId=String(formData.get("farm_id")||""),name=String(formData.get("name")||"").trim(),machineType=String(formData.get("machine_type")||"other"),manufacturer=String(formData.get("manufacturer")||"").trim(),model=String(formData.get("model")||"").trim(),registrationNo=String(formData.get("registration_no")||"").trim(),serialNo=String(formData.get("serial_no")||"").trim(),notes=String(formData.get("notes")||"").trim(),currentHours=num(formData.get("current_hours")),currentHectares=num(formData.get("current_hectares")),serviceIntervalHours=num(formData.get("service_interval_hours")),nextServiceHours=num(formData.get("next_service_hours"));if(!farmId||!name)throw new Error("Gazdaság és gépnév kötelező.");if(!(await canManageFarm(supabase,user.id,farmId)))throw new Error("Nincs jogosultságod ehhez a gépparkhoz.");if(currentHours!==null&&currentHours<0||currentHectares!==null&&currentHectares<0)throw new Error("Negatív üzemóra vagy hektár nem adható meg.");const payload={farm_id:farmId,name:name.slice(0,120),machine_type:["tractor","combine","sprayer","implement","loader","other"].includes(machineType)?machineType:"other",manufacturer:manufacturer||null,model:model||null,registration_no:registrationNo||null,serial_no:serialNo||null,current_hours:currentHours,current_hectares:currentHectares,service_interval_hours:serviceIntervalHours,next_service_hours:nextServiceHours,notes:notes||null,updated_at:new Date().toISOString()};if(id){const{data:existing}=await supabase.from("machines").select("farm_id").eq("id",id).maybeSingle();if(!existing||existing.farm_id!==farmId)throw new Error("A gép nem található.");const{error}=await supabase.from("machines").update(payload).eq("id",id);if(error)throw new Error(error.message)}else{const{error}=await supabase.from("machines").insert(payload);if(error)throw new Error(error.message)}revalidatePath("/machines");revalidatePath("/dispatch");revalidatePath("/admin/machines")}
export async function toggleMachine(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const id=String(formData.get("id")||"");const{data:m}=await supabase.from("machines").select("id,farm_id,active").eq("id",id).maybeSingle();if(!m||!(await canManageFarm(supabase,user.id,m.farm_id)))throw new Error("Nincs jogosultságod ehhez a géphez.");const{error}=await supabase.from("machines").update({active:!m.active,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/machines");revalidatePath("/dispatch")}
