import {createServerClient} from "@supabase/ssr";
import {NextResponse,type NextRequest} from "next/server";
const protectedPrefixes=["/dashboard","/admin","/farms","/fields","/map","/operations","/tasks","/team","/dispatch","/machines","/work","/timeline","/documents","/invoices","/messages","/notifications"];
export async function middleware(request:NextRequest){let response=NextResponse.next({request});const supabase=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{cookies:{getAll(){return request.cookies.getAll()},setAll(cookiesToSet){cookiesToSet.forEach(({name,value})=>request.cookies.set(name,value));response=NextResponse.next({request});cookiesToSet.forEach(({name,value,options})=>response.cookies.set(name,value,options))}}});const{data:{user}}=await supabase.auth.getUser();const pathname=request.nextUrl.pathname,protectedRoute=protectedPrefixes.some(prefix=>pathname===prefix||pathname.startsWith(`${prefix}/`));if(protectedRoute&&!user){const url=request.nextUrl.clone();url.pathname="/login";url.searchParams.set("next",`${pathname}${request.nextUrl.search}`);return NextResponse.redirect(url)}if(!user)return response;const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();const isAdvisor=profile?.role==="advisor";
 if(pathname==="/admin"||pathname.startsWith("/admin/")){if(!isAdvisor){const url=request.nextUrl.clone();url.pathname="/dashboard";url.search="";return NextResponse.redirect(url)}return response}
 if(isAdvisor&&["/dashboard","/work","/team","/dispatch","/machines"].includes(pathname)){const url=request.nextUrl.clone();url.pathname="/admin";url.search="";return NextResponse.redirect(url)}
 if(!isAdvisor){const[{data:owned},{data:membership}]=await Promise.all([supabase.from("farms").select("id").eq("owner_id",user.id).limit(1).maybeSingle(),supabase.from("farm_members").select("id,farm_id,member_role,active").eq("user_id",user.id).eq("active",true).limit(1).maybeSingle()]);const workerOnly=!owned&&!!membership;
   if(pathname==="/dashboard"&&workerOnly){const url=request.nextUrl.clone();url.pathname="/work";url.search="";return NextResponse.redirect(url)}
   const workerRestricted=["/farms","/map","/operations","/team","/dispatch","/machines","/timeline","/documents","/invoices","/messages"];
   const coordinator=membership&&["manager","agronomist"].includes(membership.member_role);
   if(workerOnly&&!coordinator&&workerRestricted.some(prefix=>pathname===prefix||pathname.startsWith(`${prefix}/`))){const url=request.nextUrl.clone();url.pathname="/work";url.search="";return NextResponse.redirect(url)}
 }
 const fieldMatch=pathname.match(/^\/fields\/([^/]+)$/);if(fieldMatch&&!isAdvisor){const fieldId=decodeURIComponent(fieldMatch[1]);const{data:field}=await supabase.from("fields").select("farm_id").eq("id",fieldId).maybeSingle();if(!field){const url=request.nextUrl.clone();url.pathname="/work";url.search="";return NextResponse.redirect(url)}const{data:farm}=await supabase.from("farms").select("owner_id").eq("id",field.farm_id).maybeSingle();const isOwner=farm?.owner_id===user.id;const{data:member}=!isOwner?await supabase.from("farm_members").select("id").eq("farm_id",field.farm_id).eq("user_id",user.id).eq("active",true).maybeSingle():{data:null};if(!isOwner&&!member){const url=request.nextUrl.clone();url.pathname="/work";url.search="";return NextResponse.redirect(url)}}return response}
export const config={matcher:["/((?!_next/static|_next/image|favicon.ico).*)"]};
