"use client";
import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {markAllNotificationsRead,markNotificationRead} from "./actions";
import styles from "./notifications.module.css";
type Item={id:string;kind:string;title:string;message:string|null;href:string|null;read_at:string|null;created_at:string};
function icon(kind:string){if(kind.includes("task"))return"☑";if(kind.includes("report")||kind.includes("reply"))return"✉";if(kind.includes("inspection"))return"◉";return"●"}
export function NotificationCenter({items}:{items:Item[]}){const router=useRouter();const[view,setView]=useState<"all"|"unread">("all");const[busy,start]=useTransition();const visible=useMemo(()=>view==="unread"?items.filter(i=>!i.read_at):items,[items,view]);const unread=items.filter(i=>!i.read_at).length;function read(id:string){start(async()=>{await markNotificationRead(id);router.refresh()})}function readAll(){start(async()=>{await markAllNotificationsRead();router.refresh()})}return <div data-tour="notification-center"><section className={styles.summary}><article className={styles.card}><span>Összes értesítés</span><strong>{items.length}</strong></article><article className={styles.card}><span>Olvasatlan</span><strong>{unread}</strong></article><article className={styles.card}><span>Olvasott</span><strong>{items.length-unread}</strong></article></section><div className={styles.toolbar}><button className={view==="all"?styles.active:""} onClick={()=>setView("all")} type="button">Összes</button><button className={view==="unread"?styles.active:""} onClick={()=>setView("unread")} type="button">Olvasatlan ({unread})</button>{unread>0&&<button type="button" disabled={busy} onClick={readAll}>Mind olvasottnak jelölése</button>}</div>{visible.length?<div className={styles.list}>{visible.map(n=><article className={`${styles.item} ${!n.read_at?styles.unread:""}`} key={n.id}><div className={styles.icon}>{icon(n.kind)}</div><div className={styles.body}><strong>{n.title}</strong>{n.message&&<p>{n.message}</p>}<small>{new Date(n.created_at).toLocaleString("hu-HU")}{n.read_at?" · Olvasott":" · Olvasatlan"}</small></div><div className={styles.actions}>{n.href&&<Link href={n.href} onClick={()=>!n.read_at&&read(n.id)}>Megnyitás</Link>}{!n.read_at&&<button disabled={busy} type="button" onClick={()=>read(n.id)}>Olvasottnak</button>}</div></article>)}</div>:<div className={styles.empty}>{view==="unread"?"Nincs olvasatlan értesítés.":"Még nincs értesítés."}</div>}</div>}
