"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";

function safeNext(v:string|null){return v&&v.startsWith("/")&&!v.startsWith("//")?v:null}
type Mode="loading"|"setup"|"challenge";
type PendingEnrollment={userId:string;factorId:string;qr:string;secret:string};
const pendingKey="agrar-mentor-mfa-pending:v1";

export default function MfaPage(){
 const supabase=useMemo(()=>createClient(),[]);const initStarted=useRef(false);const[mode,setMode]=useState<Mode>("loading");const[factorId,setFactorId]=useState("");const[qr,setQr]=useState("");const[secret,setSecret]=useState("");const[code,setCode]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{if(initStarted.current)return;initStarted.current=true;let active=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!active)return;if(!user){window.location.assign("/login");return}
 const{data,error}=await supabase.auth.mfa.listFactors();if(!active)return;if(error){setError("A kétfaktoros hitelesítés állapota nem ellenőrizhető. Próbáld újra.");setMode("challenge");return}
 const verified=data.totp?.find(f=>f.status==="verified");if(verified){try{sessionStorage.removeItem(pendingKey)}catch{}setFactorId(verified.id);setMode("challenge");return}
 try{const raw=sessionStorage.getItem(pendingKey);if(raw){const pending=JSON.parse(raw) as PendingEnrollment;if(pending.userId===user.id&&pending.factorId&&pending.qr&&pending.secret){setFactorId(pending.factorId);setQr(pending.qr);setSecret(pending.secret);setMode("setup");return}sessionStorage.removeItem(pendingKey)}}catch{}
 const prep=await fetch("/api/mfa/prepare",{method:"POST"});if(!active)return;if(!prep.ok){setError("A kétfaktoros hitelesítés előkészítése sikertelen. Jelentkezz ki, majd próbáld újra.");setMode("setup");return}const prepData=await prep.json() as {mode?:"setup"|"challenge";factorId?:string};if(prepData.mode==="challenge"&&prepData.factorId){setFactorId(prepData.factorId);setMode("challenge");return}
 const{data:enrolled,error:enrollError}=await supabase.auth.mfa.enroll({factorType:"totp"});if(!active)return;if(enrollError||!enrolled){setError("A kétfaktoros hitelesítés beállítása sikertelen. Jelentkezz ki, majd próbáld újra.");setMode("setup");return}
 const pending:PendingEnrollment={userId:user.id,factorId:enrolled.id,qr:enrolled.totp.qr_code,secret:enrolled.totp.secret};try{sessionStorage.setItem(pendingKey,JSON.stringify(pending))}catch{}setFactorId(pending.factorId);setQr(pending.qr);setSecret(pending.secret);setMode("setup")})();return()=>{active=false}},[supabase]);
 async function verify(e:FormEvent){e.preventDefault();setBusy(true);setError("");const clean=code.replace(/\s/g,"");if(!/^\d{6}$/.test(clean)){setError("Adj meg egy 6 jegyű kódot.");setBusy(false);return}const{error}=await supabase.auth.mfa.challengeAndVerify({factorId,code:clean});if(error){if(error.code==="mfa_factor_not_found"){try{sessionStorage.removeItem(pendingKey)}catch{}window.location.reload();return}setError("A kód hibás vagy lejárt. Várd meg az új kódot, és próbáld újra.");setBusy(false);return}try{sessionStorage.removeItem(pendingKey)}catch{}let target=safeNext(new URLSearchParams(window.location.search).get("next"));if(!target){const{data:{user}}=await supabase.auth.getUser();const{data:profile}=user?await supabase.from("profiles").select("role,system_role").eq("id",user.id).maybeSingle():{data:null};target=profile?.system_role==="admin"&&profile?.role==="advisor"?"/system-admin":profile?.role==="advisor"?"/admin":"/dashboard"}window.location.assign(target||"/dashboard")}
 return <main className="login-shell"><form className="login-card" onSubmit={verify}><div className="brand-mark">2FA</div><h1>Kétfaktoros hitelesítés</h1>{mode==="loading"?<p>A fiók biztonságának ellenőrzése…</p>:mode==="setup"?<><p>Az Agrár Mentor használatához állíts be egy authenticator alkalmazást. Olvasd be a QR-kódot Google Authenticatorral, Microsoft Authenticatorral vagy más TOTP alkalmazással.</p>{qr&&<img src={qr} alt="Authenticator QR-kód" style={{display:"block",width:220,maxWidth:"100%",margin:"18px auto",background:"white",padding:8,borderRadius:12}}/>}{secret&&<div className="notice" style={{overflowWrap:"anywhere"}}><b>Kézi beállítási kulcs</b><br/>{secret}</div>}</>:<p>Nyisd meg az authenticator alkalmazást, és írd be az Agrár Mentorhoz tartozó 6 jegyű kódot.</p>} {mode!=="loading"&&<label>6 jegyű hitelesítő kód<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} required/></label>}{error&&<div className="error-box">{error}</div>} {mode!=="loading"&&<button className="btn btn-primary full" disabled={busy||!factorId}>{busy?"Ellenőrzés…":mode==="setup"?"Beállítás megerősítése":"Belépés megerősítése"}</button>}<p style={{fontSize:12,marginTop:18}}>A hitelesítő kód rövid időnként változik. Az authenticator titkos kulcsát ne oszd meg senkivel.</p></form></main>
}
