import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Sidebar} from "@/components/Sidebar";
import {farmMemberRoles,farmMemberRoleLabel} from "@/lib/farmMembers";
import {inviteFarmMember,updateFarmMember} from "./actions";

export default async function TeamPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:profile}=await supabase.from("profiles").select("role,system_role,full_name").eq("id",user.id).maybeSingle();if(profile?.system_role==="admin")redirect("/system-admin");if(profile?.role==="advisor")redirect("/admin");
 const{data:farms}=await supabase.from("farms").select("id,name").eq("owner_id",user.id).order("name");const farmIds=(farms??[]).map(f=>f.id);
 const[{data:members},{data:invites}]=farmIds.length?await Promise.all([supabase.from("farm_members").select("id,farm_id,user_id,member_role,active,created_at").in("farm_id",farmIds).order("created_at"),supabase.from("farm_member_invites").select("id,farm_id,email,full_name,member_role,created_at,accepted_at").in("farm_id",farmIds).is("accepted_at",null).order("created_at",{ascending:false})]):[{data:[]},{data:[]}];
 const userIds=[...new Set((members??[]).map(m=>m.user_id))];const{data:people}=userIds.length?await supabase.from("profiles").select("id,full_name,phone").in("id",userIds):{data:[]};const personMap=new Map((people??[]).map(p=>[p.id,p]));const farmMap=new Map((farms??[]).map(f=>[f.id,f]));
 return <div className="app-shell farmer-app"><Sidebar active="team" userName={profile?.full_name||"Gazdálkodó"}/><main className="dashboard"><header className="topbar"><div><span className="eyebrow">GAZDASÁGI CSAPAT</span><h1>Munkatársak és jogosultságok</h1><p>Adj egyszerű, feladathoz illeszkedő hozzáférést az agronómusnak, traktorosnak vagy kombájnosnak.</p></div><span className="user-pill">{members?.filter(m=>m.active).length??0} aktív munkatárs</span></header>
 <section className="stats-grid"><article className="stat-card"><span>Gazdaságok</span><strong>{farms?.length??0}</strong><small>saját kezelésben</small></article><article className="stat-card"><span>Aktív tagok</span><strong>{members?.filter(m=>m.active).length??0}</strong><small>bejelentkezhetnek</small></article><article className="stat-card"><span>Függő meghívók</span><strong>{invites?.length??0}</strong><small>aktiválásra várnak</small></article><article className="stat-card"><span>Végrehajtók</span><strong>{members?.filter(m=>m.active&&(m.member_role==="operator"||m.member_role==="harvester")).length??0}</strong><small>GPS-validált munkára</small></article></section>
 <section className="panel"><span className="eyebrow">ÚJ MUNKATÁRS</span><h2>Meghívás a gazdaságba</h2><form action={inviteFarmMember} className="admin-form task-create-grid"><label>Gazdaság<select name="farm_id" required><option value="">Válassz gazdaságot</option>{farms?.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Név<input name="full_name" required maxLength={120}/></label><label>E-mail<input name="email" type="email" required/></label><label>Szerepkör<select name="member_role" defaultValue="operator">{farmMemberRoles.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="btn btn-primary">Meghívó küldése</button></form><p style={{fontSize:12,color:"#6f7c74",marginTop:12}}>A munkatárs saját fiókot kap. A traktoros és kombájnos felület szándékosan egyszerű: csak a rá kiosztott munkákat látja.</p></section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">CSAPAT</span><h2>Aktív és korábbi munkatársak</h2></div></div>{members?.length?<div style={{display:"grid",gap:10}}>{members.map(m=>{const p=personMap.get(m.user_id);return <article key={m.id} className="task-admin-row"><span className={`dot ${m.active?"normal":""}`}/><div><strong>{p?.full_name||"Munkatárs"}</strong><small>{farmMap.get(m.farm_id)?.name||"Gazdaság"} · {farmMemberRoleLabel(m.member_role)}{p?.phone?` · ${p.phone}`:""}</small></div><form action={updateFarmMember} style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><input type="hidden" name="member_id" value={m.id}/><input type="hidden" name="farm_id" value={m.farm_id}/><select name="member_role" defaultValue={m.member_role}>{farmMemberRoles.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select name="active" defaultValue={String(m.active)}><option value="true">Aktív</option><option value="false">Felfüggesztve</option></select><button className="ghost-btn">Mentés</button></form></article>})}</div>:<div className="empty-state">Még nincs meghívott munkatárs.</div>}</section>
 {invites?.length?<section className="panel"><span className="eyebrow">FÜGGŐ MEGHÍVÓK</span><h2>Aktiválásra vár</h2><div style={{display:"grid",gap:9}}>{invites.map(i=><div className="task-admin-row" key={i.id}><span className="dot high"/><div><strong>{i.full_name||i.email}</strong><small>{i.email} · {farmMap.get(i.farm_id)?.name} · {farmMemberRoleLabel(i.member_role)}</small></div><span className="user-pill">Meghívva</span></div>)}</div></section>:null}
 </main></div>
}
