import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Sidebar} from "@/components/Sidebar";
import {BlockHelpButton} from "@/components/GuidedTour";
import {approveFieldOperation} from "../actions";

export default async function OperationApprovalsPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role,full_name").eq("id",user.id).maybeSingle();if(profile?.role==="advisor")redirect("/admin/operations");
 const{data:rows,error}=await supabase.from("field_operations").select("id,farm_id,field_id,operation_date,operation_type,product_name,regulatory_category,crop,target,dose,dose_unit,official_dose_max,operator_name,approval_status,approver_name,approved_at").eq("requested_approver_id",user.id).eq("approval_required",true).order("operation_date",{ascending:false});if(error)throw new Error(error.message);
 const farmIds=Array.from(new Set((rows??[]).map(r=>r.farm_id))),fieldIds=Array.from(new Set((rows??[]).map(r=>r.field_id)));const[{data:farms},{data:fields},{data:authorizationRows}]=await Promise.all([farmIds.length?supabase.from("farms").select("id,name").in("id",farmIds):Promise.resolve({data:[]}),fieldIds.length?supabase.from("fields").select("id,name").in("id",fieldIds):Promise.resolve({data:[]}),farmIds.length?supabase.from("farm_plant_protection_approvers").select("farm_id,authorization_level,permit_number,valid_until,active").in("farm_id",farmIds).eq("user_id",user.id):Promise.resolve({data:[]})]);const farmMap=new Map((farms??[]).map(f=>[f.id,f.name])),fieldMap=new Map((fields??[]).map(f=>[f.id,f.name])),authMap=new Map((authorizationRows??[]).map(a=>[a.farm_id,a]));const pending=(rows??[]).filter(r=>r.approval_status==="pending"),approved=(rows??[]).filter(r=>r.approval_status==="approved");
 return <div className="app-shell farmer-app"><Sidebar active="approvals" userName={profile?.full_name||"Gazdasági jogosult"}/><main className="dashboard"><header className="topbar"><div><span className="eyebrow">GAZDASÁGI JÓVÁHAGYÁS</span><h1>Növényvédelmi jóváhagyások</h1><p>Csak azok a műveletek jelennek meg, amelyeknél a gazdaság téged jelölt ki jogosult jóváhagyóként.</p></div><Link className="ghost-btn" href="/operations">Műveleti napló</Link></header>
 <section className="stats-grid"><article className="stat-card"><span>Jóváhagyásra vár</span><strong>{pending.length}</strong><small>kijelölt művelet</small></article><article className="stat-card"><span>Jóváhagyott</span><strong>{approved.length}</strong><small>korábbi jóváhagyás</small></article></section>
 <section className="panel" data-help-block="plant-approval"><div className="panel-heading"><div><span className="eyebrow">FÜGGŐ TÉTELEK</span><h2>Jóváhagyásra váró műveletek</h2></div><BlockHelpButton label="A növényvédelmi jóváhagyás magyarázata" content={{title:"Növényvédelmi művelet jóváhagyása",body:"Ezen a felületen kizárólag azok a műveletek jelennek meg, amelyeknél a gazdaság téged jelölt ki jogosult jóváhagyóként. Jóváhagyás előtt ellenőrizd a készítményt, kultúrát, célt, dózist, végrehajtót és a saját jogosultságod adatait.",important:"A gomb megnyomása szakmai és jogosultsági szempontból jelentős művelet. Ne hagyj jóvá automatikusan egy tételt csak azért, mert a rendszer megjeleníti. A hatályos engedélyokirat, az alkalmazási feltételek és a tényleges jogosultság minden esetben ellenőrzendő.",example:"Példa: kukoricában gyomirtást rögzítettek. Ellenőrzöd, hogy a készítmény az adott kultúrában és célra használható-e, a megadott dózis nem haladja-e meg a hivatalos maximumot, majd a saját engedélyed érvényességét is megnézed. Csak ezután hagyod jóvá.",steps:["Ellenőrizd a gazdaságot és a földtáblát.","Ellenőrizd a készítmény nevét és kategóriáját.","Hasonlítsd össze a kultúrát, célt és dózist a hatályos engedélyokirattal.","Nézd meg a hivatalos maximális dózist és a végrehajtó személyét.","Ellenőrizd a saját jogosultsági szintedet, engedélyszámodat és érvényességedet.","Csak megfelelő adatok esetén nyomd meg a Gazdasági művelet jóváhagyása gombot."]}}/></div>{pending.length?<div className="inspection-list">{pending.map(r=>{const auth=authMap.get(r.farm_id);return <article className="inspection-card" key={r.id}><div className="inspection-head"><div><strong>{r.product_name||"Növényvédelmi művelet"}</strong><small>{farmMap.get(r.farm_id)||"Gazdaság"} · {fieldMap.get(r.field_id)||"Földtábla"} · {r.operation_date}</small></div><span className="field-total">{r.regulatory_category?`${r.regulatory_category}. kategória`:"Engedélyköteles"}</span></div><div className="field-meta"><span><b>{r.crop||"—"}</b><small>Kultúra</small></span><span><b>{r.target||"—"}</b><small>Cél</small></span><span><b>{r.dose!=null?`${r.dose} ${r.dose_unit||""}`:"—"}</b><small>Dózis</small></span><span><b>{r.official_dose_max!=null?`${r.official_dose_max} ${r.dose_unit||""}`:"—"}</b><small>Hivatalos maximum</small></span></div><p>Végrehajtó: <b>{r.operator_name||"nincs megadva"}</b></p><p>Saját jogosultság: <b>{auth?.authorization_level||"—"}. kategória</b>{auth?.permit_number?` · ${auth.permit_number}`:""}{auth?.valid_until?` · érvényes ${auth.valid_until}-ig`:""}</p><form action={approveFieldOperation.bind(null,r.id)}><button className="btn btn-primary" type="submit">Gazdasági művelet jóváhagyása</button></form></article>})}</div>:<div className="empty-state">Nincs jóváhagyásra váró műveleted.</div>}</section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">ELŐZMÉNY</span><h2>Korábban jóváhagyott műveletek</h2></div></div>{approved.length?<div className="inspection-list">{approved.slice(0,30).map(r=><article className="inspection-card" key={r.id}><div className="inspection-head"><div><strong>{r.product_name||"Növényvédelmi művelet"}</strong><small>{farmMap.get(r.farm_id)||"Gazdaság"} · {fieldMap.get(r.field_id)||"Földtábla"}</small></div><span className="field-total">Jóváhagyva</span></div><p>{r.approved_at?new Date(r.approved_at).toLocaleString("hu-HU"):""}</p></article>)}</div>:<div className="empty-state">Még nincs korábbi jóváhagyás.</div>}</section>
 </main></div>;
}
