"use server";

import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {encodeTaskProof,pointInBoundary,nearestBoundaryDistance,distanceMeters} from "@/lib/taskProof";

function optionalNumber(v:FormDataEntryValue|null,label="érték"){const s=String(v||"").trim().replace(",",".");if(!s)return null;const n=Number(s);if(!Number.isFinite(n)||n<0)throw new Error(`Érvénytelen ${label}.`);return n}

export async function completeVerifiedTask(formData:FormData){
 try{
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("A munkamenet lejárt. Jelentkezz be újra.");
  const taskId=String(formData.get("task_id")||""),lat=Number(String(formData.get("lat")||"").replace(",",".")),lng=Number(String(formData.get("lng")||"").replace(",",".")),accuracy=Number(String(formData.get("accuracy")||"").replace(",",".")),photoPath=String(formData.get("photo_path")||"").trim(),photoName=String(formData.get("photo_name")||"").trim();
  const finishedHours=optionalNumber(formData.get("finished_hours"),"záró üzemóra"),workedHectares=optionalNumber(formData.get("worked_hectares"),"megművelt hektár"),actualDose=optionalNumber(formData.get("actual_dose"),"tényleges dózis"),actualArea=optionalNumber(formData.get("actual_area"),"kezelt terület"),actualQuantity=optionalNumber(formData.get("actual_quantity"),"tényleges mennyiség"),doseUnit=String(formData.get("dose_unit")||"").trim(),quantityUnit=String(formData.get("quantity_unit")||"").trim(),weather=String(formData.get("weather")||"").trim(),notes=String(formData.get("execution_notes")||"").trim(),operationDate=String(formData.get("operation_date")||new Date().toISOString().slice(0,10));
  if(!taskId)throw new Error("Hiányzó teendő.");if(!/^\d{4}-\d{2}-\d{2}$/.test(operationDate))throw new Error("Érvénytelen munkavégzési dátum.");if(notes.length>3000||weather.length>1000)throw new Error("A végrehajtási megjegyzés túl hosszú.");
  if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lng)||lng<-180||lng>180)throw new Error("Érvényes GPS-pozíció szükséges a munka beküldéséhez.");if(!Number.isFinite(accuracy)||accuracy<=0||accuracy>200)throw new Error("A GPS pontossága nem megfelelő. Menj szabad ég alá, majd kérj új pozíciót.");if(!photoPath||!photoName)throw new Error("A munka beküldéséhez helyszíni fotó szükséges.");if(!photoPath.startsWith(`${user.id}/task-proofs/${taskId}/`))throw new Error("Érvénytelen fotóhivatkozás.");
  const{data:task,error:taskError}=await supabase.from("tasks").select("id,title,farm_id,field_id,assigned_to,status,task_kind").eq("id",taskId).eq("assigned_to",user.id).maybeSingle();if(taskError||!task)throw new Error("A teendő nem található vagy nincs hozzá jogosultságod.");if(task.status==="done")return{ok:true,submitted:false};if(task.status==="submitted")throw new Error("A munka már szaktanácsadói ellenőrzésre vár.");if(!task.field_id)throw new Error("GPS-validált beküldés csak földtáblához kapcsolt munkánál használható.");
  const[{data:field},{data:farm}]=await Promise.all([supabase.from("fields").select("id,name,center_lat,center_lng,boundary_geojson").eq("id",task.field_id).maybeSingle(),supabase.from("farms").select("id,name").eq("id",task.farm_id).maybeSingle()]);if(!field)throw new Error("A földtábla nem található.");
  const isDemo=farm?.name?.trim().toUpperCase()==="AGRÁR MENTOR DEMÓGAZDASÁG";let validation:"inside_boundary"|"near_boundary"|"near_center"|"demo_override"|null=null,distance:number|null=null;
  if(isDemo){validation="demo_override"}
  else if(field.boundary_geojson){if(pointInBoundary(lat,lng,field.boundary_geojson))validation="inside_boundary";else{distance=nearestBoundaryDistance(lat,lng,field.boundary_geojson);if(distance!==null&&distance<=150)validation="near_boundary"}}
  else if(field.center_lat!=null&&field.center_lng!=null){distance=distanceMeters(lat,lng,Number(field.center_lat),Number(field.center_lng));if(distance<=500)validation="near_center"}
  else throw new Error("Ehhez a táblához még nincs térképi adat. GPS-validált beküldés előtt rögzíteni kell a táblahatárt vagy középpontot.");
  if(!validation)throw new Error(`A GPS alapján nem vagy a munkaterületen${distance!==null?` (kb. ${Math.round(distance)} m távolság)`:""}.`);
  const now=new Date().toISOString(),proof=encodeTaskProof({lat,lng,accuracy,photoPath,photoName,capturedAt:now,distanceMeters:distance,validation});const{error}=await supabase.rpc("submit_verified_task_execution",{p_task_id:taskId,p_proof:proof,p_operation_date:operationDate,p_actual_dose:actualDose,p_dose_unit:doseUnit||null,p_actual_area:actualArea,p_actual_quantity:actualQuantity,p_quantity_unit:quantityUnit||null,p_weather:weather||null,p_notes:notes||null,p_finished_hours:finishedHours,p_worked_hectares:workedHectares});if(error)throw new Error(error.message);
  const href=`/admin/tasks?view=submitted`;const{data:advisors}=await supabase.from("profiles").select("id").eq("role","advisor");if(advisors?.length){await supabase.from("notifications").insert(advisors.map(a=>({user_id:a.id,kind:"task_submitted_review",title:"Munka ellenőrzésre vár",message:`${task.title} · ${field.name}`,href})));for(const a of advisors){try{await supabase.functions.invoke("send-notification-email",{body:{target_user_id:a.id,subject:"Munka ellenőrzésre vár",message:`${task.title}\n${field.name}\nGPS és helyszíni fotó rögzítve. A végrehajtás szaktanácsadói visszaigazolásra vár.`,href}})}catch(e){console.error(e)}}}
  revalidatePath(`/fields/${task.field_id}`);revalidatePath("/dashboard");revalidatePath("/tasks");revalidatePath("/work");revalidatePath("/admin");revalidatePath("/admin/workday");revalidatePath("/admin/tasks");return{ok:true,submitted:true};
 }catch(e){console.error("completeVerifiedTask",e);return{ok:false,submitted:false,error:e instanceof Error?e.message:"A munka beküldése sikertelen."};}
}
