import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {LogoutButton} from "@/components/LogoutButton";
import {TaskProofCompleteForm} from "@/components/TaskProofCompleteForm";
import {farmMemberRoleLabel} from "@/lib/farmMembers";
import {workerTaskStage,workerTaskStageLabel,TASK_ACCEPTED_EVENT,TASK_STARTED_EVENT} from "@/lib/taskWorkflow";
import {setWorkerTaskStage} from "./actions";

function dayKey(v=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Budapest",year:"numeric",month:"2-digit",day:"2-digit"}).format(v)}
function fmt(v:string|null){return v?new Intl.DateTimeFormat("hu-HU",{timeZone:"Europe/Budapest"}).format(new Date(`${v}T12:00:00`)):"Nincs határidő"}
export default async function WorkPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const[{data:profile},{data:memberships}]=await Promise.all([supabase.from("profiles").select("role,full_name").eq("id",user.id).maybeSingle(),supabase.from("farm_members").select("farm_id,member_role,active").eq("user_id",user.id).eq("active",true)]);
 if(profile?.role==="advisor")redirect("/admin");if(!(memberships?.length))redirect("/dashboard");
 const farmIds=memberships.map(m=>m.farm_id);const[{data:tasks},{data:farms}]=await Promise.all([supabase.from("tasks").select("id,title,description,due_date,priority,status,completed_at,field_id,farm_id,created_at").eq("assigned_to",user.id).in("farm_id",farmIds).order("due_date",{ascending:true,nullsFirst:false}).limit(100),supabase.from("farms").select("id,name").in("id",farmIds)]);
 const fieldIds=[...new Set((tasks??[]).map(t=>t.field_id).filter(Boolean))] as string[];const taskIds=(tasks??[]).map(t=>t.id);const[{data:fields},{data:events}]=await Promise.all([fieldIds.length?supabase.from("fields").select("id,name,center_lat,center_lng").in("id",fieldIds):Promise.resolve({data:[]}),taskIds.length?supabase.from("timeline_events").select("source_id,event_type,event_at").in("source_id",taskIds).in("event_type",[TASK_ACCEPTED_EVENT,TASK_STARTED_EVENT]):Promise.resolve({data:[]})]);
 const farmMap=new Map((farms??[]).map(f=>[f.id,f])),fieldMap=new Map((fields??[]).map(f=>[f.id,f])),roleMap=new Map(memberships.map(m=>[m.farm_id,m.member_role]));const today=dayKey();
 const open=(tasks??[]).filter(t=>t.status!=="done"),todayTasks=open.filter(t=>!t.due_date||t.due_date<=today),future=open.filter(t=>t.due_date&&t.due_date>today),done=(tasks??[]).filter(t=>t.status==="done").slice(0,8);
 const card=(t:any)=>{const field=fieldMap.get(t.field_id),farm=farmMap.get(t.farm_id),stage=workerTaskStage(t.status,(events??[]).filter(e=>e.source_id===t.id)),late=t.status!=="done"&&t.due_date&&t.due_date<today;const nav=field?.center_lat!=null&&field?.center_lng!=null?`https://www.google.com/maps/dir/?api=1&destination=${field.center_lat},${field.center_lng}`:null;return <article key={t.id} style={{background:"#fff",border:`1px solid ${late?"#e7b7b0":"#dfe5df"}`,borderRadius:16,padding:18,display:"grid",gap:12,boxShadow:"0 6px 20px rgba(23,74,50,.05)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><span style={{fontSize:11,fontWeight:900,color:late?"#a72f27":"#39752f"}}>{late?"LEJÁRT":"KIOSZTOTT MUNKA"}</span><h2 style={{margin:"4px 0 3px",fontSize:20}}>{t.title}</h2><small style={{color:"#6f7c74"}}>{farm?.name||"Gazdaság"} · {field?.name||"Teljes gazdaság"}</small></div><span className="user-pill">{workerTaskStageLabel(stage)}</span></div>{t.description&&<p style={{margin:0,lineHeight:1.5,color:"#4f5d54"}}>{t.description}</p>}<div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}><div style={{background:"#f6f8f5",borderRadius:10,padding:10}}><small>Határidő</small><strong style={{display:"block",marginTop:3}}>{fmt(t.due_date)}</strong></div><div style={{background:"#f6f8f5",borderRadius:10,padding:10}}><small>Szerepkör</small><strong style={{display:"block",marginTop:3}}>{farmMemberRoleLabel(roleMap.get(t.farm_id))}</strong></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{nav&&<a className="ghost-btn" href={nav} target="_blank" rel="noreferrer">Útvonal a táblához</a>}{t.field_id&&<Link className="ghost-btn" href={`/fields/${t.field_id}`}>Tábla adatlapja</Link>}{stage==="assigned"&&<form action={setWorkerTaskStage}><input type="hidden" name="task_id" value={t.id}/><input type="hidden" name="stage" value="accepted"/><button className="btn btn-primary">Elfogadom</button></form>}{stage==="accepted"&&<form action={setWorkerTaskStage}><input type="hidden" name="task_id" value={t.id}/><input type="hidden" name="stage" value="started"/><button className="btn btn-primary">Munka megkezdése</button></form>}</div>{stage==="started"&&t.field_id&&<div style={{borderTop:"1px solid #e5e9e5",paddingTop:12}}><strong style={{display:"block",marginBottom:8}}>Munka befejezése</strong><TaskProofCompleteForm taskId={t.id}/></div>}{stage==="done"&&<div className="success-box">✓ Munka lezárva és rögzítve.</div>}</article>};
 return <main style={{minHeight:"100vh",background:"#f5f6f2",padding:"20px max(14px,calc((100vw - 760px)/2)) 50px"}}><header style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",marginBottom:20}}><div><span className="eyebrow">AGRÁR MENTOR · MUNKAVÉGZŐ</span><h1 style={{margin:"4px 0 2px"}}>Mai munkáim</h1><p style={{margin:0,color:"#6f7c74"}}>{profile?.full_name||"Munkatárs"} · {open.length} nyitott feladat</p></div><LogoutButton className="ghost-btn"/></header><section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:18}}><div className="stat-card"><span>Ma / lejárt</span><strong>{todayTasks.length}</strong></div><div className="stat-card"><span>Későbbi</span><strong>{future.length}</strong></div><div className="stat-card"><span>Elvégzett</span><strong>{(tasks??[]).filter(t=>t.status==="done").length}</strong></div></section><section style={{display:"grid",gap:12}}>{todayTasks.length?todayTasks.map(card):<div className="panel"><div className="empty-state">Ma nincs elvégzendő munkád.</div></div>}</section>{future.length>0&&<section style={{marginTop:22}}><span className="eyebrow">KÖVETKEZŐ MUNKÁK</span><div style={{display:"grid",gap:12,marginTop:8}}>{future.map(card)}</div></section>}{done.length>0&&<section style={{marginTop:22}}><span className="eyebrow">LEGUTÓBB ELVÉGZETT</span><div style={{display:"grid",gap:12,marginTop:8}}>{done.map(card)}</div></section>}</main>
}
