import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {AdminNav} from "@/components/AdminNav";
import {ADVISOR_VISIT_EVENT,decodeAdvisorVisit} from "@/lib/advisorVisits";

function d(v:string|null|undefined){return v?new Date(v).toLocaleDateString("hu-HU"):"—"}
function condition(v:string|null|undefined){if(v==="critical")return"Kritikus";if(v==="attention")return"Figyelmet igényel";if(v==="good")return"Rendben";return"Nincs szemle"}
function status(v:string|null|undefined){if(v==="done")return"Kész";if(v==="closed")return"Lezárva";if(v==="reviewed")return"Megválaszolva";return"Nyitott"}
function category(v:string|null|undefined){const m:Record<string,string>={talajvizsgalat:"Talajvizsgálat",permetezes:"Permetezés",szerzodes:"Szerződés",szamla:"Számla",foto:"Fotó",egyeb:"Egyéb"};return m[v||""]||"Dokumentum"}

export default async function ClientDetailPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="advisor")redirect("/dashboard");
 const{data:client}=await supabase.from("profiles").select("id,full_name,phone,role").eq("id",id).maybeSingle();if(!client||client.role!=="farmer")notFound();
 const{data:farms}=await supabase.from("farms").select("id,name,settlement,address,owner_id").eq("owner_id",id).order("name");const farmIds=(farms??[]).map(f=>f.id);
 const{data:fields}=farmIds.length?await supabase.from("fields").select("id,name,area_ha,current_crop,crop_year,farm_id").in("farm_id",farmIds).order("name"):{data:[]};const fieldIds=(fields??[]).map(f=>f.id);
 const[{data:tasks},{data:reports},{data:inspections},{data:documents},{data:timeline},{data:visitEvents}]=await Promise.all([
  farmIds.length?supabase.from("tasks").select("id,title,due_date,status,priority,farm_id,field_id,assigned_to").in("farm_id",farmIds).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  fieldIds.length?supabase.from("farmer_reports").select("id,title,status,created_at,field_id,advisor_reply").in("field_id",fieldIds).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  fieldIds.length?supabase.from("inspections").select("id,field_id,inspected_at,condition,recommendation,notes,follow_up_status,next_check_at,issue_status").in("field_id",fieldIds).order("inspected_at",{ascending:false}).limit(200):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("documents").select("id,title,category,created_at,farm_id,field_id").in("farm_id",farmIds).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("timeline_events").select("id,title,description,event_type,event_at,created_at,field_id,farm_id").in("farm_id",farmIds).order("event_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("timeline_events").select("id,farm_id,field_id,description,event_at").in("farm_id",farmIds).eq("event_type",ADVISOR_VISIT_EVENT).order("event_at",{ascending:true}).limit(100):Promise.resolve({data:[]})
 ]);
 const latest=new Map<string,any>();for(const i of inspections??[])if(i.field_id&&!latest.has(i.field_id))latest.set(i.field_id,i);
 const openTasks=(tasks??[]).filter(t=>t.status!=="done"),openReports=(reports??[]).filter(r=>r.status!=="closed"),totalArea=(fields??[]).reduce((s,f)=>s+Number(f.area_ha||0),0);
 const critical=(fields??[]).filter(f=>latest.get(f.id)?.condition==="critical").length,attention=(fields??[]).filter(f=>latest.get(f.id)?.condition==="attention").length;
 const visits=(visitEvents??[]).map(e=>({event:e,visit:decodeAdvisorVisit(e.description)})).filter(x=>x.visit);const nextVisit=visits.find(x=>x.visit?.status==="planned"&&new Date(x.visit.scheduledAt)>=new Date());
 const operations=(timeline??[]).filter(e=>e.event_type==="field_operation");const firstFarm=farms?.[0],firstField=fields?.[0];
 return <main className="admin-shell client-detail-page">
  <header className="admin-header"><div><Link className="back-link" href="/admin/clients">← Vissza az ügyfelekhez</Link><span className="eyebrow">ÜGYFÉL DOSSZIÉ</span><h1>{client.full_name||"Névtelen ügyfél"}</h1><p>{client.phone||"Nincs telefonszám"}</p></div><div className="topbar-actions"><Link className="btn btn-secondary" href={`/admin/visits?farm=${firstFarm?.id||""}${firstField?`&field=${firstField.id}`:""}`}>Látogatás tervezése</Link><Link className="btn btn-secondary" href={`/admin/tasks${firstFarm?`?farm=${firstFarm.id}${firstField?`&field=${firstField.id}`:""}`:""}`}>Új feladat</Link><Link className="btn btn-primary" href={`/admin/inspections${firstField?`?field=${firstField.id}`:""}`}>Új szemle</Link></div></header>
  <AdminNav active="clients"/>
  <nav style={{display:"flex",gap:8,flexWrap:"wrap",margin:"-6px 0 18px"}}><a className="ghost-btn" href="#teruletek">Területek</a><a className="ghost-btn" href="#szemlek">Szemlék</a><a className="ghost-btn" href="#feladatok">Feladatok</a><a className="ghost-btn" href="#kommunikacio">Kommunikáció</a><a className="ghost-btn" href="#muveletek">Műveletek</a><a className="ghost-btn" href="#dokumentumok">Dokumentumok</a><a className="ghost-btn" href="#idovonal">Idővonal</a></nav>
  <section className="admin-overview-grid"><article className="admin-overview-card"><span>Gazdaságok</span><strong>{farms?.length??0}</strong><small>{fields?.length??0} tábla</small></article><article className="admin-overview-card"><span>Összterület</span><strong>{totalArea.toLocaleString("hu-HU",{maximumFractionDigits:1})}</strong><small>hektár</small></article><article className="admin-overview-card"><span>Állapot</span><strong>{critical?`🔴 ${critical}`:attention?`🟡 ${attention}`:"🟢"}</strong><small>{critical} kritikus · {attention} figyelmeztetés</small></article><article className="admin-overview-card"><span>Következő látogatás</span><strong style={{fontSize:18}}>{nextVisit?.visit?.scheduledAt?d(nextVisit.visit.scheduledAt):"—"}</strong><small>{nextVisit?.visit?.purpose||"Nincs tervezve"}</small></article></section>
  <section id="teruletek" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">TERÜLETEK</span><h2>Gazdaságok és földtáblák</h2></div><Link className="ghost-btn" href="/admin/map">Teljes térkép →</Link></div>{farms?.length?farms.map(f=>{const farmFields=(fields??[]).filter(x=>x.farm_id===f.id);return <div className="client-farm-block" key={f.id}><div className="client-farm-head"><div><strong>{f.name}</strong><small>{f.settlement||"Nincs település"}{f.address?` · ${f.address}`:""}</small></div><span>{farmFields.length} tábla · {farmFields.reduce((s,x)=>s+Number(x.area_ha||0),0).toLocaleString("hu-HU",{maximumFractionDigits:1})} ha</span></div><div className="client-field-list">{farmFields.map(field=>{const last=latest.get(field.id);return <Link href={`/fields/${field.id}`} className="client-field-row" key={field.id}><div><strong>{field.name}</strong><small>{field.current_crop||"Nincs kultúra"} · utolsó szemle: {d(last?.inspected_at)}</small></div><span>{field.area_ha?`${field.area_ha} ha`:"—"}</span><span>{condition(last?.condition)}</span><b>Megnyitás →</b></Link>})}</div></div>}):<div className="empty-state">Nincs gazdaság.</div>}</section>
  <section className="admin-grid"><article id="szemlek" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">SZAKTANÁCSADÁS</span><h2>Szemlék és visszaellenőrzések</h2></div><Link className="ghost-btn" href="/admin/inspections">Összes szemle →</Link></div>{inspections?.length?inspections.slice(0,10).map(i=><div className="admin-row compact" key={i.id}><div><strong>{(fields??[]).find(f=>f.id===i.field_id)?.name||"Földtábla"}</strong><small>{d(i.inspected_at)}{i.recommendation?` · ${i.recommendation}`:""}</small></div><span>{condition(i.condition)}</span><Link href={`/fields/${i.field_id}`}>Megnyitás →</Link></div>):<div className="empty-state">Nincs szemle.</div>}</article><article id="feladatok" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">AKTUÁLIS</span><h2>Nyitott feladatok</h2></div><Link className="ghost-btn" href="/admin/tasks">Összes feladat →</Link></div>{openTasks.length?openTasks.slice(0,10).map(t=><div className="task-admin-row" key={t.id}><span className={`dot ${t.priority}`}/><div><strong>{t.title}</strong><small>{t.field_id?(fields??[]).find(f=>f.id===t.field_id)?.name||"Földtábla":"Gazdaság"}</small></div><small>{t.due_date?d(t.due_date):"Nincs határidő"}</small></div>):<div className="empty-state">Nincs nyitott feladat.</div>}</article></section>
  <section className="admin-grid"><article id="kommunikacio" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">KOMMUNIKÁCIÓ</span><h2>Gazdálkodói jelzések</h2></div><Link className="ghost-btn" href="/admin/reports">Összes bejelentés →</Link></div>{reports?.length?reports.slice(0,10).map(r=><div className="admin-row compact" key={r.id}><div><strong>{r.title}</strong><small>{d(r.created_at)}</small></div><span>{status(r.status)}</span>{r.field_id&&<Link href={`/fields/${r.field_id}`}>Megnyitás →</Link>}</div>):<div className="empty-state">Nincs bejelentés.</div>}</article><article id="muveletek" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">GAZDÁLKODÁSI ELŐZMÉNY</span><h2>Legutóbbi műveletek</h2></div><Link className="ghost-btn" href="/admin/operations">Teljes napló →</Link></div>{operations.length?operations.slice(0,10).map(o=><div className="admin-row compact" key={o.id}><div><strong>{o.title}</strong><small>{d(o.event_at||o.created_at)} · {(fields??[]).find(f=>f.id===o.field_id)?.name||"Gazdaság"}</small></div><span>Művelet</span><span/></div>):<div className="empty-state">Nincs rögzített művelet.</div>}</article></section>
  <section className="admin-grid"><article id="dokumentumok" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">DOKUMENTUMOK</span><h2>Kapcsolódó iratok</h2></div><Link className="ghost-btn" href="/admin/documents">Dokumentumtár →</Link></div>{documents?.length?documents.slice(0,10).map(doc=><div className="admin-row compact" key={doc.id}><div><strong>{doc.title}</strong><small>{d(doc.created_at)}</small></div><span>{category(doc.category)}</span><span>{doc.field_id?(fields??[]).find(f=>f.id===doc.field_id)?.name||"Földtábla":"Gazdaság"}</span></div>):<div className="empty-state">Nincs dokumentum.</div>}</article><article id="idovonal" className="panel" style={{scrollMarginTop:20}}><div className="panel-heading"><div><span className="eyebrow">IDŐVONAL</span><h2>Teljes szakmai történet</h2></div><Link className="ghost-btn" href="/admin/timeline">Teljes idővonal →</Link></div>{timeline?.length?<div className="client-timeline">{timeline.slice(0,14).map(e=><div className="client-timeline-row" key={e.id}><span/><div><strong>{e.title}</strong><small>{d(e.event_at||e.created_at)} · {(fields??[]).find(f=>f.id===e.field_id)?.name||"Gazdaság"}</small></div></div>)}</div>:<div className="empty-state">Nincs idővonal-esemény.</div>}</article></section>
 </main>
}
