import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {AdminNav} from "@/components/AdminNav";
import {ADVISOR_VISIT_EVENT,decodeAdvisorVisit} from "@/lib/advisorVisits";
import styles from "./client-workspace.module.css";

function d(v:string|null|undefined){return v?new Date(v).toLocaleDateString("hu-HU"):"—"}
function condition(v:string|null|undefined){if(v==="critical")return"Kritikus";if(v==="attention")return"Figyelmet igényel";if(v==="good")return"Rendben";return"Nincs szemle"}
function stateClass(v:string|null|undefined){if(v==="critical")return `${styles.state} ${styles.critical}`;if(v==="attention")return `${styles.state} ${styles.attention}`;if(v==="good")return styles.state;return `${styles.state} ${styles.neutral}`}
function reportStatus(v:string|null|undefined){if(v==="closed")return"Lezárva";if(v==="reviewed")return"Megválaszolva";return"Nyitott"}

export default async function ClientDetailPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="advisor")redirect("/dashboard");
 const{data:client}=await supabase.from("profiles").select("id,full_name,phone,role").eq("id",id).maybeSingle();if(!client||client.role!=="farmer")notFound();
 const{data:farms}=await supabase.from("farms").select("id,name,settlement,address,owner_id").eq("owner_id",id).order("name");const farmIds=(farms??[]).map(f=>f.id);
 const{data:fields}=farmIds.length?await supabase.from("fields").select("id,name,area_ha,current_crop,crop_year,farm_id").in("farm_id",farmIds).order("name"):{data:[]};const fieldIds=(fields??[]).map(f=>f.id);
 const[{data:tasks},{data:reports},{data:inspections},{data:documents},{data:timeline},{data:visitEvents}]=await Promise.all([
  farmIds.length?supabase.from("tasks").select("id,title,due_date,status,priority,farm_id,field_id,assigned_to").in("farm_id",farmIds).order("created_at",{ascending:false}).limit(200):Promise.resolve({data:[]}),
  fieldIds.length?supabase.from("farmer_reports").select("id,title,status,created_at,field_id,advisor_reply").in("field_id",fieldIds).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  fieldIds.length?supabase.from("inspections").select("id,field_id,inspected_at,condition,recommendation,notes,follow_up_status,next_check_at,issue_status").in("field_id",fieldIds).order("inspected_at",{ascending:false}).limit(300):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("documents").select("id,title,category,created_at,farm_id,field_id").in("farm_id",farmIds).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("timeline_events").select("id,title,description,event_type,event_at,created_at,field_id,farm_id").in("farm_id",farmIds).order("event_at",{ascending:false}).limit(150):Promise.resolve({data:[]}),
  farmIds.length?supabase.from("timeline_events").select("id,farm_id,field_id,description,event_at").in("farm_id",farmIds).eq("event_type",ADVISOR_VISIT_EVENT).order("event_at",{ascending:true}).limit(100):Promise.resolve({data:[]})
 ]);
 const latest=new Map<string,any>();for(const i of inspections??[])if(i.field_id&&!latest.has(i.field_id))latest.set(i.field_id,i);
 const today=new Date().toISOString().slice(0,10),openTasks=(tasks??[]).filter(t=>t.status!=="done"),overdueTasks=openTasks.filter(t=>t.due_date&&t.due_date<today),openReports=(reports??[]).filter(r=>r.status!=="closed"),totalArea=(fields??[]).reduce((s,f)=>s+Number(f.area_ha||0),0);
 const critical=(fields??[]).filter(f=>latest.get(f.id)?.condition==="critical"),attention=(fields??[]).filter(f=>latest.get(f.id)?.condition==="attention"),dueChecks=(inspections??[]).filter(i=>i.issue_status!=="resolved"&&i.next_check_at&&i.next_check_at<=today);
 const visits=(visitEvents??[]).map(e=>({event:e,visit:decodeAdvisorVisit(e.description)})).filter(x=>x.visit);const nextVisit=visits.find(x=>x.visit?.status==="planned"&&new Date(x.visit.scheduledAt)>=new Date());
 const operations=(timeline??[]).filter(e=>e.event_type==="field_operation"),firstFarm=farms?.[0],firstField=fields?.[0],lastInspection=inspections?.[0];
 const attentionCount=critical.length+attention.length+dueChecks.length+overdueTasks.length+openReports.length;
 return <main className="admin-shell">
  <header className={`admin-header ${styles.hero}`}><div><div className={styles.breadcrumb}><Link href="/admin/clients">Ügyfelek</Link><span>›</span><strong>{client.full_name||"Ügyfél"}</strong></div><span className="eyebrow">ÜGYFÉL DOSSZIÉ</span><h1>{client.full_name||"Névtelen ügyfél"}</h1><p>{client.phone||"Nincs telefonszám"} · {farms?.length??0} gazdaság · {fields?.length??0} földtábla</p></div><div className={styles.quickActions}>{firstField&&<Link className="btn btn-primary" href={`/admin/inspections?field=${firstField.id}`}>Új szemle</Link>}<Link className="btn btn-secondary" href={`/admin/tasks${firstFarm?`?farm=${firstFarm.id}${firstField?`&field=${firstField.id}`:""}`:""}`}>Új feladat</Link><Link className="btn btn-secondary" href={`/admin/visits?farm=${firstFarm?.id||""}${firstField?`&field=${firstField.id}`:""}`}>Látogatás</Link><Link className="btn btn-secondary" href="/admin/map">Térkép</Link></div></header>
  <AdminNav active="clients"/>
  <nav className={styles.workspaceNav}><a href="#gazdasagok">Gazdaságok</a><a href="#szemlek">Szemlék</a><a href="#feladatok">Feladatok</a><a href="#kommunikacio">Kommunikáció</a><a href="#muveletek">Műveletek</a><a href="#dokumentumok">Dokumentumok</a><a href="#idovonal">Idővonal</a></nav>
  <section className={styles.clientSummary}><article className={styles.summaryCard}><span>Összterület</span><strong>{totalArea.toLocaleString("hu-HU",{maximumFractionDigits:1})} ha</strong><small>{farms?.length??0} gazdaság · {fields?.length??0} tábla</small></article><article className={styles.summaryCard}><span>Kritikus</span><strong>{critical.length}</strong><small>azonnali figyelem</small></article><article className={styles.summaryCard}><span>Figyelmeztetés</span><strong>{attention.length}</strong><small>ellenőrzendő tábla</small></article><article className={styles.summaryCard}><span>Nyitott ügyek</span><strong>{openTasks.length+openReports.length}</strong><small>{openTasks.length} feladat · {openReports.length} jelzés</small></article><article className={styles.summaryCard}><span>Utolsó szemle</span><strong>{d(lastInspection?.inspected_at)}</strong><small>{nextVisit?.visit?.scheduledAt?`Következő látogatás: ${d(nextVisit.visit.scheduledAt)}`:"Nincs tervezett látogatás"}</small></article></section>
  {attentionCount>0&&<section className="panel" style={{marginBottom:14,borderColor:critical.length?"#e1b3ab":"#ead79f"}}><div className="panel-heading"><div><span className="eyebrow">FIGYELMET IGÉNYEL</span><h2>Aktuális szakmai ügyek</h2></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:8,padding:14}}>{critical.slice(0,4).map(f=><Link key={`c-${f.id}`} className="ghost-btn" href={`/fields/${f.id}`}>🔴 {f.name} · kritikus</Link>)}{attention.slice(0,4).map(f=><Link key={`a-${f.id}`} className="ghost-btn" href={`/fields/${f.id}`}>🟡 {f.name} · ellenőrizendő</Link>)}{dueChecks.slice(0,4).map(i=><Link key={`d-${i.id}`} className="ghost-btn" href={`/fields/${i.field_id}`}>◉ {(fields??[]).find(f=>f.id===i.field_id)?.name||"Tábla"} · visszaellenőrzés</Link>)}{overdueTasks.slice(0,4).map(t=><Link key={`t-${t.id}`} className="ghost-btn" href={t.field_id?`/fields/${t.field_id}`:"/admin/tasks"}>! {t.title} · lejárt</Link>)}</div></section>}
  <section id="gazdasagok" className="panel" style={{scrollMarginTop:74}}><div className="panel-heading"><div><span className="eyebrow">GAZDASÁGOK</span><h2>Gazdaság → földtáblák</h2></div><Link className="ghost-btn" href="/admin/map">Térkép →</Link></div>{farms?.length?<div className={styles.farmGrid}>{farms.map(farm=>{const farmFields=(fields??[]).filter(x=>x.farm_id===farm.id),farmArea=farmFields.reduce((s,x)=>s+Number(x.area_ha||0),0),farmCritical=farmFields.filter(x=>latest.get(x.id)?.condition==="critical").length,farmAttention=farmFields.filter(x=>latest.get(x.id)?.condition==="attention").length;return <article className={styles.farmCard} key={farm.id}><div className={styles.farmHead}><div><strong>{farm.name}</strong><small>{farm.settlement||"Nincs település"}{farm.address?` · ${farm.address}`:""}</small></div><div className={styles.farmHeadMeta}><span className={styles.pill}>{farmFields.length} tábla</span><span className={styles.pill}>{farmArea.toLocaleString("hu-HU",{maximumFractionDigits:1})} ha</span>{farmCritical>0?<span className={`${styles.pill} ${styles.critical}`}>{farmCritical} kritikus</span>:farmAttention>0?<span className={`${styles.pill} ${styles.attention}`}>{farmAttention} figyelmeztetés</span>:<span className={styles.pill}>Rendben</span>}<Link className="ghost-btn" href={`/admin/clients/${id}/farms/${farm.id}`}>Gazdaság megnyitása →</Link></div></div><div className={styles.fieldList}>{farmFields.map(field=>{const last=latest.get(field.id);return <Link href={`/fields/${field.id}`} className={styles.fieldRow} key={field.id}><div><strong>{field.name}</strong><small>{field.current_crop||"Nincs kultúra"}</small></div><span className={styles.fieldMeta}>{field.area_ha?`${field.area_ha} ha`:"—"}</span><span className={styles.fieldMeta}>Szemle: {d(last?.inspected_at)}</span><span className={stateClass(last?.condition)}>{condition(last?.condition)}</span></Link>})}</div></article>})}</div>:<div className={styles.empty}>Nincs gazdaság.</div>}</section>
  <section className={styles.sectionGrid} style={{marginTop:14}}><article id="szemlek" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Szemlék és visszaellenőrzések</h2><span>{inspections?.length??0} bejegyzés</span></div>{inspections?.length?<div className={styles.activityList}>{inspections.slice(0,10).map(i=><Link href={`/fields/${i.field_id}`} className={styles.activityRow} key={i.id}><div><strong>{(fields??[]).find(f=>f.id===i.field_id)?.name||"Földtábla"}</strong><small>{i.recommendation||i.notes||"Nincs külön megjegyzés"}</small></div><span>{d(i.inspected_at)}<br/>{condition(i.condition)}</span></Link>)}</div>:<div className={styles.empty}>Nincs szemle.</div>}</article><article id="feladatok" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Nyitott feladatok</h2><span>{openTasks.length} aktív</span></div>{openTasks.length?<div className={styles.activityList}>{openTasks.slice(0,10).map(t=><Link href={t.field_id?`/fields/${t.field_id}`:"/admin/tasks"} className={styles.activityRow} key={t.id}><div><strong>{t.title}</strong><small>{t.field_id?(fields??[]).find(f=>f.id===t.field_id)?.name||"Földtábla":"Gazdaság"}</small></div><span>{t.due_date?d(t.due_date):"Nincs határidő"}</span></Link>)}</div>:<div className={styles.empty}>Nincs nyitott feladat.</div>}</article></section>
  <section className={styles.sectionGrid} style={{marginTop:14}}><article id="kommunikacio" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Gazdálkodói kommunikáció</h2><span>{openReports.length} nyitott</span></div>{reports?.length?<div className={styles.activityList}>{reports.slice(0,10).map(r=><Link href={r.field_id?`/fields/${r.field_id}`:"/admin/reports"} className={styles.activityRow} key={r.id}><div><strong>{r.title}</strong><small>{r.field_id?(fields??[]).find(f=>f.id===r.field_id)?.name||"Földtábla":"Gazdaság"}</small></div><span>{d(r.created_at)}<br/>{reportStatus(r.status)}</span></Link>)}</div>:<div className={styles.empty}>Nincs bejelentés.</div>}</article><article id="muveletek" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Gazdálkodási előzmények</h2><span>{operations.length} művelet</span></div>{operations.length?<div className={styles.activityList}>{operations.slice(0,10).map(o=><div className={styles.activityRow} key={o.id}><div><strong>{o.title}</strong><small>{o.field_id?(fields??[]).find(f=>f.id===o.field_id)?.name||"Földtábla":"Gazdaság"}</small></div><span>{d(o.event_at||o.created_at)}</span></div>)}</div>:<div className={styles.empty}>Nincs rögzített művelet.</div>}</article></section>
  <section className={styles.sectionGrid} style={{marginTop:14}}><article id="dokumentumok" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Dokumentumok</h2><span>{documents?.length??0} irat</span></div>{documents?.length?<div className={styles.activityList}>{documents.slice(0,10).map(doc=><Link href="/admin/documents" className={styles.activityRow} key={doc.id}><div><strong>{doc.title}</strong><small>{doc.category||"Dokumentum"}{doc.field_id?` · ${(fields??[]).find(f=>f.id===doc.field_id)?.name||"Földtábla"}`:""}</small></div><span>{d(doc.created_at)}</span></Link>)}</div>:<div className={styles.empty}>Nincs dokumentum.</div>}</article><article id="idovonal" className={styles.sectionCard}><div className={styles.sectionHead}><h2>Teljes szakmai történet</h2><span>{timeline?.length??0} esemény</span></div>{timeline?.length?<div className={styles.activityList}>{timeline.slice(0,14).map(e=><div className={styles.activityRow} key={e.id}><div><strong>{e.title}</strong><small>{e.field_id?(fields??[]).find(f=>f.id===e.field_id)?.name||"Földtábla":"Gazdaság"}</small></div><span>{d(e.event_at||e.created_at)}</span></div>)}</div>:<div className={styles.empty}>Nincs idővonal-esemény.</div>}</article></section>
 </main>;
}
