import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {AdminNav} from "@/components/AdminNav";
import {BlockHelpButton} from "@/components/GuidedTour";
import {evaluateFieldHealth} from "@/lib/fieldHealth";
import {decodeSupervisionConfig,defaultSupervisionConfig,SUPERVISION_EVENT} from "@/lib/supervision";
import {decodeHotspot,HOTSPOT_EVENT} from "@/lib/hotspots";

export default async function AdminPrioritiesPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me?.role!=="advisor")redirect("/dashboard");
 const[{data:fields},{data:farms},{data:farmers},{data:inspections},{data:tasks},{data:reports},{data:seasonEvents},{data:hotspotEvents}]=await Promise.all([
  supabase.from("fields").select("id,name,farm_id,area_ha,current_crop").order("name"),
  supabase.from("farms").select("id,name,owner_id").order("name"),
  supabase.from("profiles").select("id,full_name").eq("role","farmer"),
  supabase.from("inspections").select("field_id,condition,inspected_at").order("inspected_at",{ascending:false}),
  supabase.from("tasks").select("field_id,status,due_date,priority,title"),
  supabase.from("farmer_reports").select("field_id,status,created_at,title"),
  supabase.from("timeline_events").select("farm_id,description,event_at,created_at").eq("event_type",SUPERVISION_EVENT).order("event_at",{ascending:false}).limit(500),
  supabase.from("timeline_events").select("id,field_id,description,event_at,created_at").eq("event_type",HOTSPOT_EVENT).order("event_at",{ascending:false}).limit(2000)
 ]);
 const farmMap=new Map((farms??[]).map(x=>[x.id,x]));const ownerMap=new Map((farmers??[]).map(x=>[x.id,x.full_name]));
 const latest=new Map<string,any>();for(const i of inspections??[])if(i.field_id&&!latest.has(i.field_id))latest.set(i.field_id,i);
 const seasonMap=new Map<string,any>();for(const e of seasonEvents??[])if(e.farm_id&&!seasonMap.has(e.farm_id))seasonMap.set(e.farm_id,decodeSupervisionConfig(e.description)||defaultSupervisionConfig);
 const hotspotMap=new Map<string,any[]>();for(const e of hotspotEvents??[]){const h=decodeHotspot(e.description);if(!h||h.resolved||!e.field_id)continue;const list=hotspotMap.get(e.field_id)||[];list.push(h);hotspotMap.set(e.field_id,list)}
 const rows=(fields??[]).map(field=>{const farm=farmMap.get(field.farm_id);const supervision=seasonMap.get(field.farm_id)||defaultSupervisionConfig;const health=evaluateFieldHealth({inspection:latest.get(field.id),tasks:(tasks??[]).filter(t=>t.field_id===field.id),reports:(reports??[]).filter(r=>r.field_id===field.id),hotspots:hotspotMap.get(field.id)||[],supervision});return{field,farm,owner:farm?ownerMap.get(farm.owner_id):null,health,hotspots:hotspotMap.get(field.id)||[]}}).sort((a,b)=>b.health.score-a.health.score||a.field.name.localeCompare(b.field.name,"hu"));
 const actionable=rows.filter(r=>r.health.status!=="inactive"),critical=rows.filter(r=>r.health.status==="critical").length,attention=rows.filter(r=>r.health.status==="attention").length,inactive=rows.filter(r=>r.health.status==="inactive").length,openHotspots=rows.reduce((n,r)=>n+r.hotspots.length,0);
 return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">NAPI MUNKASORREND</span><h1>Mi igényel ma figyelmet?</h1><p>A prioritást a szezonális szemleelvárás, teendők, bejelentések és a térképen rögzített problémagócok együtt határozzák meg.</p></div></header><AdminNav active="priorities"/>
 <section className="admin-overview-grid"><article className="admin-overview-card"><span>Kritikus</span><strong>{critical}</strong><small>azonnali figyelmet igényel</small></article><article className="admin-overview-card"><span>Figyelmeztetés</span><strong>{attention}</strong><small>ellenőrzendő tábla</small></article><article className="admin-overview-card"><span>Nyitott problémagóc</span><strong>{openHotspots}</strong><small>térképen megjelölt hely</small></article><article className="admin-overview-card"><span>Szezonon kívül</span><strong>{inactive}</strong><small>nincs automatikus szemleelvárás</small></article></section>
 <section className="panel" data-help-block="advisor-priorities"><div className="panel-heading"><div><span className="eyebrow">PRIORITÁSI LISTA</span><h2>Mai munkalista</h2></div><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><BlockHelpButton label="A prioritási lista magyarázata" content={{title:"Mai prioritások és automatikus sorrend",body:"A rendszer több jelből állít össze napi munkasorrendet: a legutóbbi szemle állapota, nyitott és sürgős teendők, gazdálkodói bejelentések, GPS-problémagócok és az adott gazdaság beállított szemlézési szezonja együtt alakítják a prioritást.",important:"A rangsor döntéstámogatás, nem helyettesíti a szaktanácsadói szakmai mérlegelést. Egy alacsonyabb helyre sorolt tábla is lehet sürgős, ha új információ érkezik, ezért a 'Miért?' jellegű okcímkéket és a kapcsolódó adatlapokat is ellenőrizd.",example:"Példa: egy tábla kritikus szemleállapotot, egy nyitott problémagócot és lejárt sürgős teendőt is tartalmaz. Ez a kombináció a lista elejére emeli. Az Adatlap, Problémák és Térképen gombokkal gyorsan összegyűjtöd a döntéshez szükséges részleteket.",steps:["Először nézd meg a Kritikus és Figyelmeztetés összesítőket.","Haladj a lista elejétől lefelé, de olvasd el minden tételnél az okcímkéket.","Nyisd meg az Adatlapot a szemlék, teendők és előzmények ellenőrzéséhez.","GPS-problémagóc esetén nyisd meg a Problémák nézetet vagy a térképet.","Ha a szezonális elvárás nem megfelelő, a Szezonok beállítása oldalon módosítsd a gazdaság szemleciklusát.","A végső szakmai sorrendet az aktuális terepi és gazdálkodói információk alapján alakítsd ki."]}}/><Link className="ghost-btn" href="/admin/supervision">Szezonok beállítása</Link><Link className="ghost-btn" href="/admin/map">Térképes nézet →</Link></div></div>
 <div style={{display:"grid",gap:10}}>{actionable.length?actionable.map((r,index)=>{const bg=r.health.status==="critical"?"#fff2f0":r.health.status==="attention"?"#fff8e8":"#f2f8f1";const border=r.health.status==="critical"?"#e6b7b1":r.health.status==="attention"?"#ead59e":"#cfe2cb";const color=r.health.status==="critical"?"#a72f27":r.health.status==="attention"?"#916512":"#34753a";return <article key={r.field.id} style={{display:"grid",gridTemplateColumns:"52px minmax(0,1fr) auto",gap:14,alignItems:"center",padding:"14px 16px",border:`1px solid ${border}`,borderRadius:12,background:bg}}><span style={{width:40,height:40,borderRadius:10,display:"grid",placeItems:"center",fontWeight:900,color,background:"#fff"}}>{index+1}</span><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:15}}>{r.field.name}</strong><span style={{fontSize:10,fontWeight:900,color,border:`1px solid ${border}`,borderRadius:999,padding:"4px 8px",background:"#fff"}}>{r.health.label}</span>{r.hotspots.length>0&&<span style={{fontSize:10,fontWeight:900,color:"#8a3a23",border:"1px solid #edc1b5",borderRadius:999,padding:"4px 8px",background:"#fff"}}>◎ {r.hotspots.length} problémagóc</span>}</div><small style={{display:"block",marginTop:4,color:"#6f7c74"}}>{r.owner||"Gazdálkodó"} · {r.farm?.name||"Gazdaság"} · {r.field.area_ha?`${r.field.area_ha} ha`:"—"} · {r.field.current_crop||"Nincs kultúra"}</small><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8}}>{r.health.reasons.map(reason=><span key={reason} style={{fontSize:10,padding:"4px 7px",borderRadius:7,background:"#fff",border:`1px solid ${border}`,color}}>{reason}</span>)}</div></div><div style={{display:"grid",gap:7,minWidth:130}}><Link className="btn btn-primary" href={`/fields/${r.field.id}`}>Adatlap</Link><Link className="ghost-btn" href={`/fields/${r.field.id}/hotspots`}>Problémák</Link><Link className="ghost-btn" href={`/admin/map?field=${r.field.id}`}>Térképen</Link></div></article>}):<div className="empty-state">Jelenleg nincs aktív vagy problémás földtábla a munkalistán.</div>}</div></section>
 {inactive>0&&<section className="panel" style={{marginTop:14}}><div className="panel-heading"><div><span className="eyebrow">INAKTÍV SZAKTANÁCSADÁSI IDŐSZAK</span><h2>Szezonon kívüli táblák</h2></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{rows.filter(r=>r.health.status==="inactive").map(r=><Link key={r.field.id} className="ghost-btn" href={`/fields/${r.field.id}`}>{r.farm?.name||"Gazdaság"} · {r.field.name}</Link>)}</div></section>}
 </main>
}
