"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";

type ContactInput={contact_type:"phone"|"email";label:string;value:string;is_primary:boolean};
function normalizePhone(v:string){const s=v.trim();const lead=s.startsWith("+")?"+":"";return lead+s.replace(/\D/g,"")}
function normalizeEmail(v:string){return v.trim().toLowerCase()}
function parseContacts(raw:FormDataEntryValue|null):ContactInput[]{let value:unknown;try{value=JSON.parse(String(raw||"[]"))}catch{throw new Error("A kapcsolattartási adatok formátuma hibás.")}if(!Array.isArray(value))throw new Error("A kapcsolattartási adatok formátuma hibás.");const items:ContactInput[]=value.slice(0,30).map((x:any):ContactInput=>{const type:ContactInput["contact_type"]=x?.contact_type==="email"?"email":"phone";const val=type==="email"?normalizeEmail(String(x?.value||"")):normalizePhone(String(x?.value||""));return{contact_type:type,label:String(x?.label||"").trim(),value:val,is_primary:!!x?.is_primary}}).filter((x:ContactInput)=>Boolean(x.value));const seen=new Set<string>();const unique=items.filter(x=>{const key=`${x.contact_type}:${x.value}`;if(seen.has(key))return false;seen.add(key);return true});if(unique.length&&!unique.some(x=>x.is_primary))unique[0].is_primary=true;let primaryUsed=false;return unique.map(x=>{if(x.is_primary&&!primaryUsed){primaryUsed=true;return x}return{...x,is_primary:false}})}
function validateContacts(items:ContactInput[],required=true){if(required&&!items.some(x=>x.contact_type==="phone"))throw new Error("Legalább egy telefonszám megadása kötelező.");if(required&&!items.some(x=>x.contact_type==="email"))throw new Error("Legalább egy e-mail cím megadása kötelező.");for(const x of items){if(x.contact_type==="phone"){if(!x.label)throw new Error("Minden telefonszámhoz add meg a kapcsolattartó nevét.");if(!/^\+?\d{7,15}$/.test(x.value))throw new Error(`Érvénytelen telefonszám: ${x.value}`)}if(x.contact_type==="email"&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x.value))throw new Error(`Érvénytelen e-mail cím: ${x.value}`);if(x.value.length>250||x.label.length>120)throw new Error("Az egyik kapcsolattartási adat túl hosszú.")}}

export async function saveFarmContacts(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const farmId=String(formData.get("farm_id")||"");const items=parseContacts(formData.get("contacts_json"));validateContacts(items,true);const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();const{data:farm}=await supabase.from("farms").select("owner_id").eq("id",farmId).maybeSingle();if(!farm||(me?.role!=="advisor"&&farm.owner_id!==user.id))throw new Error("Nincs jogosultságod a kapcsolattartási adatok módosításához.");const{error:del}=await supabase.from("farm_contacts").delete().eq("farm_id",farmId);if(del)throw new Error(del.message);const{error}=await supabase.from("farm_contacts").insert(items.map(x=>({...x,farm_id:farmId})));if(error)throw new Error(error.message);revalidatePath("/admin/clients");revalidatePath(`/admin/clients/${farm.owner_id}`);revalidatePath(`/admin/clients/${farm.owner_id}/farms/${farmId}`);revalidatePath("/farms")}

export async function saveProfileContacts(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const items=parseContacts(formData.get("contacts_json"));validateContacts(items,true);const{error:del}=await supabase.from("profile_contacts").delete().eq("profile_id",user.id);if(del)throw new Error(del.message);const{error}=await supabase.from("profile_contacts").insert(items.map(x=>({...x,profile_id:user.id,visible_to_counterparty:true})));if(error)throw new Error(error.message);revalidatePath("/dashboard");revalidatePath("/admin")}

export async function markCommunicationSeen(entityType:string,entityId:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");if(!["farmer_report","inspection","task","advisor_message"].includes(entityType)||!entityId)throw new Error("Érvénytelen kommunikációs elem.");const{error}=await supabase.rpc("mark_communication_seen",{p_entity_type:entityType,p_entity_id:entityId});if(error)throw new Error(error.message)}

export async function createPersonalFollowup(formData:FormData):Promise<{id:string}>{const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const entityType=String(formData.get("entity_type")||""),entityId=String(formData.get("entity_id")||""),title=String(formData.get("title")||"").trim(),href=String(formData.get("href")||"").trim(),when=String(formData.get("remind_at")||"");if(!["farmer_report","inspection","task","advisor_message"].includes(entityType)||!entityId||!title||!href)throw new Error("Hiányzó emlékeztető adat.");if(!href.startsWith("/"))throw new Error("Az emlékeztető hivatkozása érvénytelen.");const remindAt=new Date(when);if(Number.isNaN(remindAt.getTime())||remindAt.getTime()<=Date.now())throw new Error("Az emlékeztető időpontja legyen a jövőben.");const{data,error}=await supabase.from("personal_followups").insert({user_id:user.id,entity_type:entityType,entity_id:entityId,title:title.slice(0,180),href,remind_at:remindAt.toISOString()}).select("id").single();if(error){if(error.code==="23505"){const{data:existing}=await supabase.from("personal_followups").select("id").eq("user_id",user.id).eq("entity_type",entityType).eq("entity_id",entityId).eq("remind_at",remindAt.toISOString()).maybeSingle();if(existing)return{id:existing.id}}throw new Error(error.message)}revalidatePath("/notifications");return{id:data.id}}

export async function cancelPersonalFollowup(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const id=String(formData.get("followup_id")||"");if(!id)throw new Error("Hiányzó emlékeztető.");const{error}=await supabase.from("personal_followups").update({status:"cancelled",completed_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id).in("status",["pending","notified"]);if(error)throw new Error(error.message);revalidatePath("/notifications")}

export async function reschedulePersonalFollowup(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const id=String(formData.get("followup_id")||""),when=String(formData.get("remind_at")||"");const remindAt=new Date(when);if(!id||Number.isNaN(remindAt.getTime())||remindAt.getTime()<=Date.now())throw new Error("Érvényes jövőbeli időpont szükséges.");const{error}=await supabase.from("personal_followups").update({status:"pending",remind_at:remindAt.toISOString(),notified_at:null,completed_at:null}).eq("id",id).eq("user_id",user.id);if(error)throw new Error(error.message);revalidatePath("/notifications")}

export async function completePersonalFollowup(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const id=String(formData.get("followup_id")||"");const{error}=await supabase.from("personal_followups").update({status:"done",completed_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);if(error)throw new Error(error.message);revalidatePath("/notifications")}
