"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";

type ContactInput={contact_type:"phone"|"email";label:string;value:string};
function parseContacts(raw:FormDataEntryValue|null):ContactInput[]{let value:unknown;try{value=JSON.parse(String(raw||"[]"))}catch{throw new Error("A kapcsolattartási adatok formátuma hibás.")}if(!Array.isArray(value))throw new Error("A kapcsolattartási adatok formátuma hibás.");return value.slice(0,20).map((x:any)=>({contact_type:x?.contact_type==="email"?"email":"phone",label:String(x?.label||"").trim(),value:String(x?.value||"").trim()})).filter(x=>x.value)}
function validateContacts(items:ContactInput[],required=true){if(required&&!items.some(x=>x.contact_type==="phone"))throw new Error("Legalább egy telefonszám megadása kötelező.");if(required&&!items.some(x=>x.contact_type==="email"))throw new Error("Legalább egy e-mail cím megadása kötelező.");for(const x of items){if(x.contact_type==="phone"&&!x.label)throw new Error("Minden telefonszámhoz add meg a kapcsolattartó nevét.");if(x.contact_type==="email"&&!/^\S+@\S+\.\S+$/.test(x.value))throw new Error(`Érvénytelen e-mail cím: ${x.value}`);if(x.value.length>250||x.label.length>120)throw new Error("Az egyik kapcsolattartási adat túl hosszú.")}}

export async function saveFarmContacts(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const farmId=String(formData.get("farm_id")||"");const items=parseContacts(formData.get("contacts_json"));validateContacts(items,true);const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();const{data:farm}=await supabase.from("farms").select("owner_id").eq("id",farmId).maybeSingle();if(!farm||(me?.role!=="advisor"&&farm.owner_id!==user.id))throw new Error("Nincs jogosultságod a kapcsolattartási adatok módosításához.");const{error:del}=await supabase.from("farm_contacts").delete().eq("farm_id",farmId);if(del)throw new Error(del.message);const{error}=await supabase.from("farm_contacts").insert(items.map((x,i)=>({...x,farm_id:farmId,is_primary:i===0})));if(error)throw new Error(error.message);revalidatePath("/admin/clients");revalidatePath(`/admin/clients/${farm.owner_id}`);revalidatePath("/farms")}

export async function saveProfileContacts(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const items=parseContacts(formData.get("contacts_json"));validateContacts(items,true);await supabase.from("profile_contacts").delete().eq("profile_id",user.id);const{error}=await supabase.from("profile_contacts").insert(items.map((x,i)=>({...x,profile_id:user.id,is_primary:i===0,visible_to_counterparty:true})));if(error)throw new Error(error.message);revalidatePath("/dashboard");revalidatePath("/admin")}

export async function markCommunicationSeen(entityType:string,entityId:string){const supabase=await createClient();const{error}=await supabase.rpc("mark_communication_seen",{p_entity_type:entityType,p_entity_id:entityId});if(error)throw new Error(error.message)}

export async function createPersonalFollowup(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const entityType=String(formData.get("entity_type")||""),entityId=String(formData.get("entity_id")||""),title=String(formData.get("title")||"").trim(),href=String(formData.get("href")||"").trim(),when=String(formData.get("remind_at")||"");if(!["farmer_report","inspection","task","advisor_message"].includes(entityType)||!entityId||!title||!href)throw new Error("Hiányzó emlékeztető adat.");const remindAt=new Date(when);if(Number.isNaN(remindAt.getTime())||remindAt.getTime()<=Date.now())throw new Error("Az emlékeztető időpontja legyen a jövőben.");const{error}=await supabase.from("personal_followups").insert({user_id:user.id,entity_type:entityType,entity_id:entityId,title,href,remind_at:remindAt.toISOString()});if(error&&error.code!=="23505")throw new Error(error.message);revalidatePath("/notifications")}

export async function completePersonalFollowup(formData:FormData){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Jelentkezz be újra.");const id=String(formData.get("followup_id")||"");const{error}=await supabase.from("personal_followups").update({status:"done",completed_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);if(error)throw new Error(error.message);revalidatePath("/notifications")}
