import Link from "next/link";

export default function Home(){return <main className="publicSite">
<nav className="publicNav"><a className="publicBrand" href="#kezdolap">AGRÁR MENTOR</a><div className="publicLinks"><a href="#szaktanacsadas">Szaktanácsadás</a><a href="#hogyan">Hogyan dolgozom?</a><a href="#rendszer">Agrár Mentor rendszer</a><a href="#rolam">Rólam</a><a href="#kapcsolat">Kapcsolat</a></div><Link className="publicLogin" href="/login">Belépés az ügyfélfiókba</Link></nav>
<section className="publicHero" id="kezdolap"><div className="heroInner"><div className="heroCopy"><small>SZEMÉLYES AGRÁR-SZAKTANÁCSADÁS</small><h1>Szaktanácsadás, ami nem ér véget a tábla szélén.</h1><p>Személyes szakmai támogatás a gazdaságodhoz, helyszíni szemlékkel, követhető javaslatokkal és egy saját digitális ügyfélfelülettel.</p><div className="heroButtons"><a className="heroPrimary" href="#kapcsolat">Kapcsolatfelvétel</a><Link className="heroSecondary" href="/login">Belépés az ügyfélfiókba</Link></div></div><aside className="heroPanel"><small>AGRÁR MENTOR</small><h3>Személyes szakértelem. Digitális háttér.</h3><div className="heroPoint"><span>◎</span><div><strong>Helyszíni szemlék</strong><small>A területek valós állapotára építve.</small></div></div><div className="heroPoint"><span>✓</span><div><strong>Követhető javaslatok</strong><small>Feladatok és visszaellenőrzések egy helyen.</small></div></div><div className="heroPoint"><span>▦</span><div><strong>Saját ügyfélfelület</strong><small>Táblák, dokumentumok és szakmai előzmények.</small></div></div></aside></div></section>
<section className="publicSection" id="szaktanacsadas"><div className="sectionIntro"><small>SZAKTANÁCSADÁS</small><h2>Szakmai támogatás a döntések mögött</h2><p>A célom nem egy újabb adminisztrációs rendszer értékesítése, hanem használható szakmai segítség biztosítása a gazdálkodás mindennapi döntéseihez.</p></div><div className="serviceGrid"><article className="serviceCard"><span className="serviceIcon">◉</span><h3>Helyszíni szemle</h3><p>A területek állapotának rendszeres ellenőrzése, problémák felismerése és dokumentálása.</p></article><article className="serviceCard"><span className="serviceIcon">⌁</span><h3>Szakmai javaslatok</h3><p>A szemlék és rendelkezésre álló adatok alapján egyértelmű, visszakereshető teendők és ajánlások.</p></article><article className="serviceCard"><span className="serviceIcon">↻</span><h3>Nyomon követés</h3><p>Nem vész el, mi történt korábban: a szemlék, munkák és visszajelzések időrendben követhetők.</p></article></div></section>
<section className="publicSection" id="hogyan"><div className="sectionIntro"><small>HOGYAN DOLGOZOM?</small><h2>Egyszerű, követhető együttműködés</h2></div><div className="processGrid"><article className="processCard"><div className="processNumber">01</div><h3>Megismerem a gazdaságot</h3><p>Területek, termesztési körülmények és a legfontosabb szakmai célok.</p></article><article className="processCard"><div className="processNumber">02</div><h3>Helyszíni ellenőrzés</h3><p>A döntések alapját lehetőség szerint a területen látott állapot adja.</p></article><article className="processCard"><div className="processNumber">03</div><h3>Javaslat és feladat</h3><p>A szükséges teendők rögzítve és később is visszakereshetően jelennek meg.</p></article><article className="processCard"><div className="processNumber">04</div><h3>Visszakövetés</h3><p>Látható, hogy mi készült el, mi változott és mikor szükséges újabb szemle.</p></article></div></section>
<section className="systemSection" id="rendszer"><div className="systemInner"><div className="systemCopy"><small className="eyebrow">DIGITÁLIS HÁTTÉR</small><h2>Az Agrár Mentor rendszer</h2><p>A szaktanácsadás mellé saját digitális ügyfélfelület tartozik. Nem a szoftver helyettesíti a szakembert: arra szolgál, hogy a közös munka átlátható, dokumentált és később is visszakereshető legyen.</p><div className="checkList"><div><span>✓</span> Saját gazdaságok és földtáblák</div><div><span>✓</span> Szemlék és szakmai javaslatok</div><div><span>✓</span> Teendők és visszaellenőrzések</div><div><span>✓</span> Dokumentumok és fotók</div><div><span>✓</span> Teljes szakmai idővonal</div></div><div className="heroButtons"><Link className="heroPrimary" href="/login">Ügyfélfiók megnyitása</Link></div></div><div className="mockup" aria-label="Agrár Mentor rendszer bemutató"><div className="mockTop"><i/><i/><i/></div><div className="mockBody"><div className="mockSide"/><div className="mockContent"><div className="mockStats"><div/><div/><div/></div><div className="mockRows"><div/><div/></div></div></div></div></div></section>
<section className="publicSection" id="rolam"><div className="aboutGrid"><div className="aboutPortrait">AM</div><div className="aboutCopy"><small>RÓLAM</small><h2>Személyes kapcsolat, közvetlen szakmai támogatás</h2><p>Az Agrár Mentor mögött jelenleg egyetlen szaktanácsadó áll. Ez tudatosan személyes szolgáltatás: nem egy nagy tanácsadó céget szeretnék utánozni, hanem közvetlen, átlátható együttműködést kialakítani azokkal a gazdálkodókkal, akikkel dolgozom.</p><p>A digitális Agrár Mentor felület azért készült, hogy a helyszíni munka és a későbbi kapcsolattartás között se vesszen el információ. Így az ügyfél és én is ugyanazt a szakmai történetet látjuk.</p></div></div></section>
<section className="contactBand" id="kapcsolat"><div className="contactInner"><div><h2>Beszéljünk a gazdaságodról.</h2><p>Ha szaktanácsadást keresel, vedd fel velem a kapcsolatot.</p></div><a className="heroPrimary" href="mailto:kapcsolat@example.hu">Kapcsolatfelvétel</a></div></section>
<footer className="footer"><strong>Agrár Mentor</strong><span>Személyes agrár-szaktanácsadás · Digitális ügyfélfelülettel</span></footer>
</main>}
