"use client";
import {useEffect,useMemo,useState} from "react";
import {usePathname,useRouter} from "next/navigation";

type Role="farmer"|"advisor"|"system-admin";
type Module={id:string;label:string;href:string;menu:string;summary:string;important?:string};
type Step={id:string;title:string;body:string;selector:string;href?:string;menu?:boolean;optional?:boolean;important?:string};

const farmer:Module[]=[
 {id:"dashboard",label:"Áttekintés",href:"/dashboard",menu:'[data-tour="farmer-dashboard"]',summary:"A gazdaság napi állapotképe, figyelmeztetései, határidői és munkaterülete."},
 {id:"fields",label:"Táblák",href:"/fields",menu:'[data-tour="farmer-fields"]',summary:"A földtáblák, kultúrák, szakmai állapotok és előzmények nyilvántartása."},
 {id:"operations",label:"Műveleti napló",href:"/operations",menu:'[data-tour="farmer-operations"]',summary:"A tervezett és elvégzett agrár műveletek teljes naplója.",important:"Növényvédelemnél mindig ellenőrizd a hivatalos korlátokat és a szükséges gazdasági jogosultságot."},
 {id:"approvals",label:"Jóváhagyások",href:"/operations/approvals",menu:'[data-tour="farmer-approvals"]',summary:"A jogosultsághoz kötött műveletek felelős gazdasági jóváhagyása.",important:"Jóváhagyás előtt ellenőrizd a készítményt, kultúrát, célt, dózist és saját jogosultságodat."},
 {id:"tasks",label:"Teendők",href:"/tasks",menu:'[data-tour="farmer-tasks"]',summary:"Határidős munkák, szakmai javaslatok és végrehajtási feladatok."},
 {id:"messages",label:"Üzenetek",href:"/messages",menu:'[data-tour="farmer-messages"]',summary:"Gazdálkodói jelzések, szaktanácsadói válaszok és utánkövetés."},
 {id:"documents",label:"Dokumentumok",href:"/documents",menu:'[data-tour="farmer-documents"]',summary:"A gazdasághoz és táblákhoz tartozó dokumentumok központi tárhelye."},
 {id:"farms",label:"Gazdaságom",href:"/farms",menu:'[data-tour="farmer-farms"]',summary:"Gazdasági alapadatok, kapcsolatok és jogosultságok."},
 {id:"map",label:"Térkép",href:"/map",menu:'[data-tour="farmer-map"]',summary:"A táblák és területek térképes áttekintése."},
 {id:"team",label:"Munkatársak",href:"/team",menu:'[data-tour="farmer-team"]',summary:"A gazdaság tagjai, szerepkörei és hozzáférései."},
 {id:"dispatch",label:"Munkakiosztás",href:"/dispatch",menu:'[data-tour="farmer-dispatch"]',summary:"Feladatok személyhez, táblához és szükség esetén géphez rendelése."},
 {id:"machines",label:"Géppark",href:"/machines",menu:'[data-tour="farmer-machines"]',summary:"A gazdaság gépeinek nyilvántartása és műveleti használata."},
 {id:"timeline",label:"Idővonal",href:"/timeline",menu:'[data-tour="farmer-timeline"]',summary:"A szakmai és gazdasági események kronologikus előzménye."},
 {id:"invoices",label:"Számlák",href:"/invoices",menu:'[data-tour="farmer-invoices"]',summary:"A számlázási és pénzügyi információk központja."},
 {id:"notifications",label:"Értesítések",href:"/notifications",menu:'[data-tour="farmer-notifications"]',summary:"A fontos szakmai és munkafolyamat-események központja."}
];
const advisor:Module[]=[
 {id:"home",label:"Kezdőlap",href:"/admin",menu:'[data-tour="advisor-home"]',summary:"A napi szaktanácsadói munka, prioritások és gyorsmodulok kiindulópontja."},
 {id:"clients",label:"Ügyfelek",href:"/admin/clients",menu:'[data-tour="advisor-clients"]',summary:"Gazdálkodók, gazdaságok, földtáblák és szakmai dossziék kezelése."},
 {id:"contacts",label:"Elérhetőségek",href:"/admin/contacts",menu:'[data-tour="advisor-contacts"]',summary:"Kapcsolattartási adatok és közvetlen ügyfélkommunikáció."},
 {id:"workday",label:"Munkanap",href:"/admin/workday",menu:'[data-tour="advisor-workday"]',summary:"Napi szemlék, feladatok, látogatások, visszaellenőrzések és elmaradások."},
 {id:"operations",label:"Műveletek",href:"/admin/operations",menu:'[data-tour="advisor-operations"]',summary:"Az ügyfélgazdaságok műveleteinek szakmai ellenőrzési nézete.",important:"A szaktanácsadói javaslat és a gazdasági végrehajtási felelősség elkülönül."},
 {id:"plant",label:"Növényvédelem",href:"/admin/plant-protection-import",menu:'[data-tour="advisor-plant"]',summary:"HU/SK hivatalos növényvédőszer-adatok, importok és ellenőrzések."},
 {id:"map",label:"Térkép",href:"/admin/map",menu:'[data-tour="advisor-map"]',summary:"Ügyfelek, gazdaságok és táblák térképes szakmai áttekintése."},
 {id:"documents",label:"Dokumentumok",href:"/admin/documents",menu:'[data-tour="advisor-documents"]',summary:"Az ügyfelekhez és szakmai munkához kapcsolódó dokumentumtár."}
];
const admin:Module[]=[
 {id:"home",label:"Rendszeráttekintés",href:"/system-admin",menu:'[data-admin-tour="admin-home"]',summary:"Rendszerfelügyelet, állapotkép és auditált adminisztrátori munkaterületek."},
 {id:"support",label:"Támogatási központ",href:"/system-admin/support",menu:'[data-admin-tour="admin-support"]',summary:"Felhasználói és munkafolyamat-problémák vizsgálata.",important:"Admin beavatkozás csak indokkal és auditnyommal történjen."},
 {id:"users",label:"Felhasználók",href:"/system-admin/users",menu:'[data-admin-tour="admin-users"]',summary:"Fiókok, üzleti szerepkörök és rendszeradmin-jogok elkülönített kezelése.",important:"A rendszeradmin-jog nem azonos a szaktanácsadói üzleti szerepkörrel."},
 {id:"security",label:"Biztonsági események",href:"/system-admin/security",menu:'[data-admin-tour="admin-security"]',summary:"Hitelesítési, jogosultsági és kockázatos rendszeresemények vizsgálata."},
 {id:"backup",label:"Biztonsági mentés",href:"/system-admin/backup",menu:'[data-admin-tour="admin-backup"]',summary:"A kiemelten védett, szerveroldali rendszermentés felülete.",important:"Az export érzékeny művelet; friss MFA és indokolt adatkezelési cél szükséges."}
];

function build(modules:Module[],role:Role):Step[]{return modules.flatMap(m=>[
 {id:`${m.id}-menu`,title:`${m.label} – menüpont`,body:`Először ezt a menüpontot mutatjuk meg. ${m.summary}`,selector:m.menu,menu:true},
 {id:`${m.id}-header`,title:`${m.label} – oldal`,body:`Most megnyílik a ${m.label} oldal. ${m.summary}`,href:m.href,selector:role==="system-admin"?"main > header, main h1":"main > header, main h1",optional:true,important:m.important},
 {id:`${m.id}-primary`,title:`${m.label} – első munkablokk`,body:"Ez az oldal első érdemi munkablokkja: itt találod az adott modul legfontosabb összesítő, rögzítő vagy navigációs funkcióját.",href:m.href,selector:"main > section:nth-of-type(1), main > div:nth-of-type(1), main form",optional:true},
 {id:`${m.id}-detail`,title:`${m.label} – részletes munkaterület`,body:"Itt dolgozol az adott modul részletes adataival, listáival, státuszaival és kapcsolódó műveleteivel. A túra csak bemutatja a felületet, nem hajt végre mentést vagy jóváhagyást.",href:m.href,selector:"main > section:last-of-type, main > div:last-of-type, main form:last-of-type",optional:true,important:m.important}
]);}
const config={farmer:{version:9,name:"Gazdálkodói teljes rendszerbemutató",steps:build(farmer,"farmer")},advisor:{version:9,name:"Szaktanácsadói teljes rendszerbemutató",steps:build(advisor,"advisor")},"system-admin":{version:5,name:"Rendszeradminisztrátori teljes rendszerbemutató",steps:build(admin,"system-admin")}};

export function ComprehensiveTour({role}:{role:Role}){const cfg=config[role];const steps=useMemo(()=>cfg.steps,[cfg.steps]);const router=useRouter();const pathname=usePathname();const doneKey=`agrar-comprehensive-tour:${role}:v${cfg.version}`;const stateKey=`${doneKey}:state`;const[index,setIndex]=useState<number|null>(null);const[welcome,setWelcome]=useState(false);const[rect,setRect]=useState<DOMRect|null>(null);
 useEffect(()=>{try{const raw=sessionStorage.getItem(stateKey);if(raw!==null){const n=Number(raw);if(Number.isInteger(n)&&n>=0&&n<steps.length){setIndex(n);return}}if(!localStorage.getItem(doneKey))setWelcome(true)}catch{}},[doneKey,stateKey,steps.length]);
 useEffect(()=>{if(index===null)return;const step=steps[index];if(!step){setIndex(null);return}try{sessionStorage.setItem(stateKey,String(index))}catch{}if(step.href&&pathname!==step.href){setRect(null);router.push(step.href);return}let timer=0,tries=0,el:HTMLElement|null=null;const measure=()=>{if(el)setRect(el.getBoundingClientRect())};const advance=()=>setIndex(cur=>cur===null?null:cur+1>=steps.length?null:cur+1);const seek=()=>{el=document.querySelector(step.selector) as HTMLElement|null;if(el){const r=el.getBoundingClientRect();if(step.menu&&(r.width===0||r.height===0||r.right<0||r.left>window.innerWidth)){const launch=document.querySelector('button[aria-label*="Menü megnyitása"],button[aria-label*="Admin menü megnyitása"]') as HTMLButtonElement|null;if(launch){launch.click();timer=window.setTimeout(seek,180);return}}el.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"});measure();timer=window.setTimeout(measure,220);return}tries++;if(tries<15){timer=window.setTimeout(seek,100);return}console.warn(`[ComprehensiveTour] Missing target ${step.selector} on ${pathname}`);advance()};seek();window.addEventListener("resize",measure);window.addEventListener("scroll",measure,true);return()=>{window.clearTimeout(timer);window.removeEventListener("resize",measure);window.removeEventListener("scroll",measure,true)}},[index,pathname,router,stateKey,steps]);
 useEffect(()=>{const ev=`agrar-comprehensive-tour-${role}`;const h=()=>start();window.addEventListener(ev,h);return()=>window.removeEventListener(ev,h)},[role]);
 function mark(){try{localStorage.setItem(doneKey,new Date().toISOString());sessionStorage.removeItem(stateKey)}catch{}}
 function start(){try{localStorage.removeItem(doneKey);sessionStorage.setItem(stateKey,"0")}catch{}setWelcome(false);setIndex(0)}
 function finish(){mark();setIndex(null);setRect(null)}
 function move(delta:number){setIndex(cur=>{if(cur===null)return null;const next=cur+delta;if(next<0)return 0;if(next>=steps.length){mark();setRect(null);return null}try{sessionStorage.setItem(stateKey,String(next))}catch{}return next})}
 const step=index===null?null:steps[index];const cardW=Math.min(410,typeof window!=="undefined"?window.innerWidth-24:410);let left=12,top=12;if(rect&&typeof window!=="undefined"){left=Math.max(12,Math.min(window.innerWidth-cardW-12,rect.left));top=rect.bottom+300<window.innerHeight?rect.bottom+12:Math.max(12,rect.top-286)}
 return <>{welcome&&<div style={{position:"fixed",inset:0,zIndex:20000,background:"rgba(9,18,13,.76)",display:"grid",placeItems:"center",padding:16}}><div style={{width:"min(520px,100%)",background:"#fff",borderRadius:18,padding:22,boxShadow:"0 24px 70px rgba(0,0,0,.35)"}}><small style={{fontWeight:900,color:"#17613d"}}>TELJES RENDSZERBEMUTATÓ</small><h2 style={{margin:"8px 0"}}>{cfg.name}</h2><p style={{lineHeight:1.55,color:"#56635b"}}>A túra menüpontonként halad: megmutatja a menüpontot, megnyitja az oldalt, majd végigvezet az oldal fő munkablokkjain.</p><div style={{display:"flex",gap:8,justifyContent:"flex-end",flexWrap:"wrap"}}><button className="ghost-btn" onClick={()=>{mark();setWelcome(false)}}>Most kihagyom</button><button className="btn btn-primary" onClick={start}>Induljon a teljes túra</button></div></div></div>}{step&&rect&&<><div aria-hidden="true" style={{position:"fixed",zIndex:20001,left:Math.max(6,rect.left-8),top:Math.max(6,rect.top-8),width:Math.min(window.innerWidth-12,rect.width+16),height:Math.min(window.innerHeight-12,rect.height+16),borderRadius:14,boxShadow:"0 0 0 9999px rgba(8,15,11,.76),0 0 0 3px #fff,0 0 0 6px #1c6845",pointerEvents:"none"}}/><section role="dialog" aria-label={step.title} style={{position:"fixed",zIndex:20002,left,top,width:cardW,maxHeight:"min(430px,calc(100vh - 24px))",overflow:"auto",background:"#fff",border:"2px solid #1c6845",borderRadius:16,padding:18,boxShadow:"0 20px 60px rgba(0,0,0,.34)"}}><small style={{fontWeight:900,color:"#1c6845"}}>{index!+1}. LÉPÉS / {steps.length}</small><h3 style={{margin:"8px 0"}}>{step.title}</h3><p style={{lineHeight:1.55,color:"#56635b"}}>{step.body}</p>{step.important&&<div style={{padding:11,borderRadius:10,background:"#f4f7f4",border:"1px solid #d8e3da",fontSize:13}}><b>Fontos: </b>{step.important}</div>}<div style={{height:4,background:"#e6ece7",borderRadius:99,margin:"16px 0"}}><span style={{display:"block",height:"100%",width:`${((index!+1)/steps.length)*100}%`,background:"#1c6845",borderRadius:99}}/></div><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><button className="ghost-btn" onClick={finish}>Kilépés</button><div style={{display:"flex",gap:8}}>{index!>0&&<button className="ghost-btn" onClick={()=>move(-1)}>Vissza</button>}<button className="btn btn-primary" onClick={()=>move(1)}>{index===steps.length-1?"Befejezés":"Tovább"}</button></div></div></section></>}</>}
export function ComprehensiveTourRestart({role}:{role:Role}){return <button type="button" className="ghost-btn" onClick={()=>window.dispatchEvent(new Event(`agrar-comprehensive-tour-${role}`))}>Teljes virtuális túra</button>}
