"use client";
import {useState} from "react";
type Contact={id?:string;contact_type:"phone"|"email";label:string;value:string;is_primary?:boolean};
type Row={id:string;type:"phone"|"email";label:string;value:string;primary:boolean};
function make(type:"phone"|"email",c?:Contact):Row{return{id:c?.id||crypto.randomUUID(),type:c?.contact_type||type,label:c?.label||"",value:c?.value||"",primary:!!c?.is_primary}}
export function ContactFields({name="contacts_json",requirePhone=true,requireEmail=true,initialContacts=[]}:{name?:string;requirePhone?:boolean;requireEmail?:boolean;initialContacts?:Contact[]}){
 const seed=initialContacts.length?initialContacts.map(c=>make(c.contact_type,c)):[make("phone"),make("email")];
 const[rows,setRows]=useState<Row[]>(seed);
 const update=(id:string,p:Partial<Row>)=>setRows(v=>v.map(r=>r.id===id?{...r,...p}:r));
 const remove=(id:string)=>setRows(v=>{const next=v.filter(r=>r.id!==id);return next.length?next:[make("phone"),make("email")]});
 const makePrimary=(id:string)=>setRows(v=>v.map(r=>({...r,primary:r.id===id})));
 const payload=JSON.stringify(rows.filter(r=>r.value.trim()).map(r=>({contact_type:r.type,label:r.label.trim()||(r.type==="email"?"E-mail":"Kapcsolattartó"),value:r.value.trim(),is_primary:r.primary})));
 return <div data-tour="contact-fields" style={{display:"grid",gap:10,minWidth:0}}><input type="hidden" name={name} value={payload}/>{rows.map((r,i)=><div key={r.id} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8,alignItems:"end",minWidth:0,padding:10,border:"1px solid #e4e9e4",borderRadius:10}}><label>Típus<select value={r.type} onChange={e=>update(r.id,{type:e.target.value as Row["type"]})}><option value="phone">Telefon</option><option value="email">E-mail</option></select></label><label>{r.type==="phone"?"Kapcsolattartó neve":"Megnevezés"}<input value={r.label} onChange={e=>update(r.id,{label:e.target.value})} placeholder={r.type==="phone"?"pl. Kovács János":"pl. Iroda"} required={r.type==="phone"&&!!r.value.trim()}/></label><label>{r.type==="phone"?"Telefonszám":"E-mail cím"}<input type={r.type==="email"?"email":"tel"} value={r.value} onChange={e=>update(r.id,{value:e.target.value})} placeholder={r.type==="phone"?"+36 30 123 4567":"gazdasag@pelda.hu"} required={(requirePhone&&r.type==="phone"&&i===rows.findIndex(x=>x.type==="phone"))||(requireEmail&&r.type==="email"&&i===rows.findIndex(x=>x.type==="email"))}/></label><div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center"}}><button type="button" className="ghost-btn" onClick={()=>makePrimary(r.id)} aria-pressed={r.primary}>{r.primary?"★ Elsődleges":"☆ Elsődlegesnek"}</button><button type="button" className="ghost-btn" onClick={()=>remove(r.id)} aria-label="Kapcsolat törlése">Törlés</button></div></div>)}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="ghost-btn" onClick={()=>setRows(v=>[...v,make("phone")])}>＋ Telefonszám</button><button type="button" className="ghost-btn" onClick={()=>setRows(v=>[...v,make("email")])}>＋ E-mail cím</button></div><small>Telefonszámhoz mindig kapcsolattartói név tartozik. Több telefonszám és e-mail is megadható; egy elérhetőség elsődlegesként jelölhető.</small></div>
}

export function ContactLinks({contacts}:{contacts:{id?:string;contact_type:string;label:string;value:string;is_primary?:boolean}[]}){const sorted=[...contacts].sort((a,b)=>Number(!!b.is_primary)-Number(!!a.is_primary));return <div data-tour="contact-links" style={{display:"grid",gap:7,minWidth:0}}>{sorted.map((c,i)=>c.contact_type==="phone"?<a key={c.id||i} className="ghost-btn" style={{justifyContent:"flex-start",maxWidth:"100%",overflowWrap:"anywhere"}} href={`tel:${c.value.replace(/[^+\d]/g,"")}`}>☎ {c.is_primary?"★ ":""}{c.label}: {c.value}</a>:<a key={c.id||i} className="ghost-btn" style={{justifyContent:"flex-start",maxWidth:"100%",overflowWrap:"anywhere"}} href={`mailto:${c.value}`}>✉ {c.is_primary?"★ ":""}{c.label}: {c.value}</a>)}</div>}
