"use client";
import {useState} from "react";
type Row={id:string;type:"phone"|"email";label:string;value:string};
function make(type:"phone"|"email"):Row{return{id:crypto.randomUUID(),type,label:"",value:""}}
export function ContactFields({name="contacts_json",requirePhone=true,requireEmail=true}:{name?:string;requirePhone?:boolean;requireEmail?:boolean}){
 const[rows,setRows]=useState<Row[]>([make("phone"),make("email")]);
 const update=(id:string,p:Partial<Row>)=>setRows(v=>v.map(r=>r.id===id?{...r,...p}:r));
 const remove=(id:string)=>setRows(v=>v.filter(r=>r.id!==id));
 const payload=JSON.stringify(rows.filter(r=>r.value.trim()).map(r=>({contact_type:r.type,label:r.label.trim()||(r.type==="email"?"E-mail":"Kapcsolattartó"),value:r.value.trim()})));
 return <div style={{display:"grid",gap:10}}><input type="hidden" name={name} value={payload}/>{rows.map((r,i)=><div key={r.id} style={{display:"grid",gridTemplateColumns:"minmax(105px,.8fr) minmax(130px,1fr) minmax(150px,1.3fr) auto",gap:8,alignItems:"end"}}><label>Típus<select value={r.type} onChange={e=>update(r.id,{type:e.target.value as Row["type"]})}><option value="phone">Telefon</option><option value="email">E-mail</option></select></label><label>{r.type==="phone"?"Kapcsolattartó neve":"Megnevezés"}<input value={r.label} onChange={e=>update(r.id,{label:e.target.value})} placeholder={r.type==="phone"?"pl. Kovács János":"pl. Iroda"} required={r.type==="phone"&&!!r.value.trim()}/></label><label>{r.type==="phone"?"Telefonszám":"E-mail cím"}<input type={r.type==="email"?"email":"tel"} value={r.value} onChange={e=>update(r.id,{value:e.target.value})} placeholder={r.type==="phone"?"+36 30 123 4567":"gazdasag@pelda.hu"} required={(requirePhone&&r.type==="phone"&&i===rows.findIndex(x=>x.type==="phone"))||(requireEmail&&r.type==="email"&&i===rows.findIndex(x=>x.type==="email"))}/></label><button type="button" className="ghost-btn" onClick={()=>remove(r.id)} disabled={rows.length<=2} aria-label="Kapcsolat törlése">−</button></div>)}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className="ghost-btn" onClick={()=>setRows(v=>[...v,make("phone")])}>＋ Telefonszám</button><button type="button" className="ghost-btn" onClick={()=>setRows(v=>[...v,make("email")])}>＋ E-mail cím</button></div><small>Telefonszámhoz mindig kapcsolattartói név tartozik. Több telefonszám és e-mail is megadható.</small></div>
}

export function ContactLinks({contacts}:{contacts:{id?:string;contact_type:string;label:string;value:string}[]}){return <div style={{display:"grid",gap:7}}>{contacts.map((c,i)=>c.contact_type==="phone"?<a key={c.id||i} className="ghost-btn" style={{justifyContent:"flex-start"}} href={`tel:${c.value.replace(/[^+\d]/g,"")}`}>☎ {c.label}: {c.value}</a>:<a key={c.id||i} className="ghost-btn" style={{justifyContent:"flex-start"}} href={`mailto:${c.value}`}>✉ {c.label}: {c.value}</a>)}</div>}
