"use client";
import {useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import styles from "@/app/documents/documents.module.css";

type Scope={farms:{id:string,name:string}[];fields:{id:string,name:string,farm_id:string}[]};
export function DocumentUploadForm({farms,fields}:Scope){
 const router=useRouter(),inputRef=useRef<HTMLInputElement|null>(null);const[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[fileName,setFileName]=useState(""),[farmId,setFarmId]=useState("");
 const visibleFields=useMemo(()=>farmId?fields.filter(f=>f.farm_id===farmId):fields,[fields,farmId]);
 function choose(file?:File){if(!file||!inputRef.current)return;const dt=new DataTransfer();dt.items.add(file);inputRef.current.files=dt.files;setFileName(file.name)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const form=new FormData(e.currentTarget),file=form.get("file") as File,selectedFarm=String(form.get("farm_id")||""),fieldId=String(form.get("field_id")||"");if(!file?.size||(!selectedFarm&&!fieldId)){setMsg("Válassz gazdaságot vagy földtáblát, és csatolj fájlt.");setBusy(false);return}if(file.size>20*1024*1024){setMsg("A fájl legfeljebb 20 MB lehet.");setBusy(false);return}const allowed=["application/pdf","image/jpeg","image/png","image/webp","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"];if(file.type&&!allowed.includes(file.type)){setMsg("Nem támogatott fájltípus. PDF, JPG, PNG, WebP, DOC vagy DOCX tölthető fel.");setBusy(false);return}const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){setMsg("A munkamenet lejárt. Jelentkezz be újra.");setBusy(false);return}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${user.id}/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from("documents").upload(path,file,{contentType:file.type||undefined});if(up.error){setMsg(`Feltöltési hiba: ${up.error.message}`);setBusy(false);return}const ins=await supabase.from("documents").insert({uploaded_by:user.id,farm_id:selectedFarm||null,field_id:fieldId||null,title:String(form.get("title")||file.name),category:String(form.get("category")||"egyeb"),notes:String(form.get("notes")||"")||null,storage_path:path,file_name:file.name,media_type:file.type||null,file_size:file.size});if(ins.error){await supabase.storage.from("documents").remove([path]);setMsg(`Mentési hiba: ${ins.error.message}`);setBusy(false);return}setMsg("Dokumentum sikeresen feltöltve.");(e.target as HTMLFormElement).reset();setFarmId("");setFileName("");setBusy(false);router.refresh()}
 return <form className={styles.form} onSubmit={submit}><div className={styles.rowFull}><label className={styles.field}><span>Megnevezés</span><input name="title" placeholder="pl. Talajvizsgálat 2026" required/></label></div><div className={styles.rowTwo}><label className={styles.field}><span>Kategória</span><select name="category" defaultValue="talajvizsgalat"><option value="talajvizsgalat">Talajvizsgálat</option><option value="permetezes">Permetezés</option><option value="szerzodes">Szerződés</option><option value="szamla">Számla</option><option value="foto">Fotó</option><option value="egyeb">Egyéb</option></select></label><label className={styles.field}><span>Gazdaság</span><select name="farm_id" value={farmId} onChange={e=>setFarmId(e.target.value)}><option value="">Nincs kiválasztva</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><div className={styles.rowFull}><label className={styles.field}><span>Földtábla <em>(opcionális)</em></span><select name="field_id" defaultValue=""><option value="">Nincs kiválasztva</option>{visibleFields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><div className={styles.rowFull}><label className={styles.field}><span>Megjegyzés <em>(opcionális)</em></span><textarea name="notes" rows={4} maxLength={500} placeholder="Megjegyzés írása..."/></label></div><div className={`${styles.rowFull} ${styles.dropWrap}`}><span className={styles.dropLabel}>Fájl kiválasztása</span><div className={styles.dropzone} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="copy"}} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files?.[0])}} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")inputRef.current?.click()}}><div className={styles.uploadIcon}>⇧</div><strong>{fileName||"Húzd ide a fájlt, vagy kattints a tallózáshoz"}</strong><small>PDF, kép (JPG, PNG, WebP), DOC, DOCX</small><small>Maximum 20 MB</small><input ref={inputRef} name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" required onChange={e=>setFileName(e.target.files?.[0]?.name||"")}/></div></div>{msg&&<div className={styles.message}>{msg}</div>}<button className={`btn btn-primary ${styles.submit}`} disabled={busy}>{busy?"Feltöltés…":"Dokumentum feltöltése"}</button></form>
}
