"use client";
import {useEffect,useRef,useState} from "react";
declare global{interface Window{L:any}}
type Field={id:string;name:string;farmName:string;areaHa:number|null;crop:string|null;lat:number|null;lng:number|null;boundary:any|null;href:string;status?:string};
type Hotspot={id:string;fieldId:string;lat:number;lng:number;title:string;severity:"warning"|"critical";notes?:string;href:string};
function statusText(v:string|undefined){if(v==="critical")return"Kritikus";if(v==="attention")return"Figyelmeztetés";if(v==="inactive")return"Szezonon kívül";if(v==="good")return"Rendben";return"Nincs állapot"}
function styleFor(v:string|undefined){if(v==="critical")return{color:"#8f261f",fillColor:"#d74a40"};if(v==="attention")return{color:"#a96f05",fillColor:"#e7b332"};if(v==="inactive")return{color:"#68736c",fillColor:"#a7aea9"};return{color:"#22653d",fillColor:"#4f9a5b"}}
export function FieldsOverviewMap({fields,hotspots=[],compact=false}:{fields:Field[];hotspots?:Hotspot[];compact?:boolean}){
 const ref=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),meRef=useRef<any>(null);const[ready,setReady]=useState(false),[locating,setLocating]=useState(false),[locError,setLocError]=useState("");
 useEffect(()=>{function css(href:string){if(document.querySelector(`link[href="${href}"]`))return;const l=document.createElement("link");l.rel="stylesheet";l.href=href;document.head.appendChild(l)}function script(src:string){return new Promise<void>((resolve,reject)=>{const f=document.querySelector(`script[src="${src}"]`) as HTMLScriptElement|null;if(f){if(window.L)resolve();else f.addEventListener("load",()=>resolve(),{once:true});return}const s=document.createElement("script");s.src=src;s.async=true;s.onload=()=>resolve();s.onerror=reject;document.body.appendChild(s)})}let cancelled=false;(async()=>{css("https://unpkg.com/leaflet@1.9.4/dist/leaflet.css");await script("https://unpkg.com/leaflet@1.9.4/dist/leaflet.js");if(cancelled||!ref.current||mapRef.current)return;const L=window.L,map=L.map(ref.current,{zoomControl:true}).setView([47.2,19.5],7);mapRef.current=map;
 const satellite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:19,attribution:"Tiles © Esri"});
 const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"});
 satellite.addTo(map);L.control.layers({"Műhold":satellite,"Utcatérkép":street},undefined,{position:"topright",collapsed:false}).addTo(map);
 const bounds:any[]=[];
 fields.forEach(f=>{const popup=`<div style="min-width:160px"><strong>${f.name}</strong><br><small>${f.farmName}</small><br><span>${f.areaHa??"—"} ha · ${f.crop||"Nincs kultúra"}</span><br><b>Állapot: ${statusText(f.status)}</b><br><a href="${f.href}" style="font-weight:800;color:#175a36">Földtábla adatlapja →</a></div>`;if(f.boundary){const st=styleFor(f.status);const layer=L.geoJSON(f.boundary,{style:{...st,weight:3,fillOpacity:f.status==="inactive"?.18:.28}}).addTo(map).bindPopup(popup);try{const b=layer.getBounds();bounds.push(b.getSouthWest(),b.getNorthEast())}catch{}}else if(f.lat!=null&&f.lng!=null){L.circleMarker([f.lat,f.lng],{radius:9,...styleFor(f.status),fillOpacity:.96,weight:3}).addTo(map).bindPopup(popup);bounds.push([f.lat,f.lng])}});
 hotspots.forEach(h=>{const critical=h.severity==="critical",fill=critical?"#cf3f36":"#e9b52e",stroke=critical?"#7f1d18":"#8c5c00";L.circleMarker([h.lat,h.lng],{radius:8,color:"#fff",fillColor:fill,fillOpacity:1,weight:3}).addTo(map).bindPopup(`<strong>${critical?"⚠ Kritikus probléma":"⚠ Figyelmeztetés"}</strong><br>${h.title}${h.notes?`<br>${h.notes}`:""}<br><a href="${h.href}" style="font-weight:800;color:#175a36">Probléma megnyitása →</a>`).bindTooltip(h.title,{direction:"top"});L.circleMarker([h.lat,h.lng],{radius:12,color:stroke,fillOpacity:0,weight:2}).addTo(map);bounds.push([h.lat,h.lng])});
 if(bounds.length)map.fitBounds(bounds,{padding:[30,30],maxZoom:16});setReady(true)})().catch(()=>setLocError("A térkép nem tölthető be."));return()=>{cancelled=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[fields,hotspots]);
 function locate(){setLocError("");if(!navigator.geolocation){setLocError("A böngésző nem támogatja a GPS-helymeghatározást.");return}setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{setLocating(false);const lat=pos.coords.latitude,lng=pos.coords.longitude,L=window.L,map=mapRef.current;if(!L||!map)return;map.setView([lat,lng],17);if(meRef.current)meRef.current.setLatLng([lat,lng]);else meRef.current=L.circleMarker([lat,lng],{radius:9,color:"#fff",fillColor:"#155e42",fillOpacity:1,weight:3}).addTo(map).bindTooltip("Saját GPS-helyzet",{permanent:false}).openTooltip()},()=>{setLocating(false);setLocError("A helymeghatározás nem sikerült. Engedélyezd a GPS-hozzáférést.")},{enableHighAccuracy:true,timeout:12000,maximumAge:5000})}
 return <section className={compact?"field-map-compact":"panel field-map-panel"} data-tour="farmer-real-map">
  {!compact&&<><div className="panel-heading"><div><span className="eyebrow">VALÓS TÉRKÉP</span><h2>Táblák, GPS-helyzet és problémagócok</h2></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span className="user-pill">{fields.filter(f=>f.boundary||f.lat!=null).length} tábla · {hotspots.length} nyitott probléma</span><button type="button" className="ghost-btn" onClick={locate} disabled={locating} data-tour="farmer-map-gps">{locating?"Helyzet keresése…":"⌖ Saját GPS-helyzet"}</button></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"0 0 11px"}}><span className="map-legend good">● Rendben</span><span className="map-legend attention">● Figyelmeztetés</span><span className="map-legend critical">● Kritikus</span><span className="map-legend hotspot">◎ GPS problémagóc</span></div></>}
  <div ref={ref} style={{height:compact?"100%":500,minHeight:compact?360:undefined,width:"100%",borderRadius:compact?10:12,overflow:"hidden",background:"#dfe7df"}}/>
  {!ready&&<p style={{color:"#6f7c74",fontSize:11}}>Térkép betöltése…</p>}{locError&&<p className="error-box" style={{marginTop:8}}>{locError}</p>}
  {!compact&&<p style={{marginTop:9,color:"#6f7c74",fontSize:10.5}}>Alapnézet: műholdkép. A jobb felső vezérlővel utcatérképre válthatsz. A színes táblahatár állapotjelzés, a külön pontok GPS-szel rögzített problémák.</p>}
 </section>
}
