"use client";
import {useEffect,useMemo,useState} from "react";import styles from "./GuidedTour.module.css";
export type HelpContent={title:string;body:string;important?:string;example?:string;steps?:string[]};type Step=HelpContent&{selector:string;helpId:string};export type TourRole="advisor"|"farmer";
const advisor:Step[]=[
 ["advisor-home","Kezdőlap","A napi szakmai állapot, figyelmeztetések és gyorsindítók központja."],["advisor-clients","Ügyfelek és gazdaságok","Itt kezeled a gazdálkodókat, gazdaságaikat, kapcsolattartóikat és földtábláikat."],["advisor-contacts","Elérhetőségek","A gazdaságok telefonos és e-mail kapcsolattartási adatai külön kezelhetők."],["advisor-workday","Munkanap","A napi szemlék, feladatok, visszaellenőrzések és következő teendők munkaterülete."],["advisor-operations","Agrár műveletek","Műveleti tervek, szakmai javaslatok és végrehajtási állapotok követése."],["advisor-plant","Növényvédelem","HU/SK hivatalos növényvédőszer-adatok, dózisok és szabályozási státuszok kezelése."],["advisor-map","Térkép","Gazdaságok és táblák térképes áttekintése és gyors területi navigáció."],["advisor-documents","Dokumentumok","Az ügyfelekhez és szakmai munkához kapcsolódó dokumentumok kezelése."],
].map(([helpId,title,body])=>({helpId,selector:`[data-tour="${helpId}"]`,title,body}));
const farmer:Step[]=[
 ["farmer-dashboard","Áttekintés","A gazdaság napi összefoglalója: figyelmeztetések, terület, teendők és következő határidők."],["farmer-fields","Táblák","Földterületeid, kultúráik, állapotuk, szemléik és előzményeik."],["farmer-operations","Műveleti napló","A tervezett és elvégzett agrár műveletek teljes nyilvántartása."],["farmer-approvals","Jóváhagyások","A jogosultsághoz kötött műveletek gazdasági jóváhagyási felülete."],["farmer-tasks","Teendők","Határidős munkák, szaktanácsadói javaslatok és saját feladatok."],["farmer-messages","Üzenetek","Bejelentések, szaktanácsadói válaszok és szakmai visszajelzések."],["farmer-documents","Dokumentumok","A gazdasághoz és táblákhoz tartozó dokumentumok központi tárhelye."],["farmer-farms","Gazdaságom","A gazdaság alapadatai, kapcsolatai és szervezeti információi."],["farmer-map","Térkép","A táblák és területek térképes áttekintése."],["farmer-team","Munkatársak","A gazdaság tagjai, szerepkörei és hozzáférései."],["farmer-dispatch","Munkakiosztás","Feladatok kiosztása a gazdaság munkatársai számára."],["farmer-machines","Géppark","A gazdaság gépeinek nyilvántartása és műveleti használata."],["farmer-timeline","Idővonal","Szemlék, feladatok, bejelentések és más gazdasági események időrendben."],["farmer-invoices","Számlák","A számlázási modul és a későbbi pénzügyi nyilvántartás helye."],["farmer-notifications","Értesítések","A fontos szakmai és munkafolyamat-események központja."],
].map(([helpId,title,body])=>({helpId,selector:`[data-tour="${helpId}"]`,title,body}));
const tours={advisor:{version:5,name:"Szaktanácsadói teljes rendszerbemutató",intro:"Végigvezetünk a teljes szaktanácsadói portál minden fő modulján.",steps:advisor},farmer:{version:5,name:"Gazdálkodói teljes rendszerbemutató",intro:"Végigvezetünk a teljes gazdálkodói portál minden fő modulján.",steps:farmer}};
function HelpDetails({content}:{content:HelpContent}){return <><p>{content.body}</p>{content.important&&<div className={styles.important}><strong>Fontos tudnivaló</strong><span>{content.important}</span></div>}</>}
export function GuidedTour({role}:{role:TourRole}){const cfg=tours[role];const storageKey=`agrar-mentor-tour:${role}:v${cfg.version}`;const[welcome,setWelcome]=useState(false);const[index,setIndex]=useState<number|null>(null);const[rect,setRect]=useState<DOMRect|null>(null);const steps=useMemo(()=>cfg.steps,[cfg.steps]);useEffect(()=>{try{if(!localStorage.getItem(storageKey))setWelcome(true)}catch{}},[storageKey]);useEffect(()=>{if(index===null)return;const step=steps[index];if(!step){finish();return}const el=document.querySelector(step.selector) as HTMLElement|null;if(!el){setRect(null);return}const update=()=>setRect(el.getBoundingClientRect());el.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"});const timer=window.setTimeout(update,220);update();window.addEventListener("resize",update);window.addEventListener("scroll",update,true);return()=>{clearTimeout(timer);window.removeEventListener("resize",update);window.removeEventListener("scroll",update,true)}},[index,steps]);useEffect(()=>{const handler=()=>start();window.addEventListener(`agrar-tour-${role}`,handler);return()=>window.removeEventListener(`agrar-tour-${role}`,handler)},[role]);function mark(){try{localStorage.setItem(storageKey,new Date().toISOString())}catch{}}function start(){setWelcome(false);setIndex(0)}function finish(){mark();setIndex(null);setRect(null)}function next(){if(index===null)return;if(index>=steps.length-1)finish();else setIndex(index+1)}function prev(){if(index!==null&&index>0)setIndex(index-1)}const step=index===null?null:steps[index];return <>{welcome&&<div className={styles.welcome}><div className={styles.welcomeCard}><span className={styles.eyebrow}>Teljes rendszerbemutató</span><h2>{cfg.name}</h2><p>{cfg.intro}</p><div className={styles.welcomeActions}><button className={styles.button} onClick={start}>Induljon a túra</button><button className={styles.ghost} onClick={()=>{mark();setWelcome(false)}}>Most kihagyom</button></div></div></div>}{step&&rect&&<><div className={styles.spotlight} style={{left:Math.max(6,rect.left-8),top:Math.max(6,rect.top-8),width:Math.min(window.innerWidth-12,rect.width+16),height:rect.height+16}}/><div className={styles.card} style={{left:Math.max(16,Math.min(window.innerWidth-376,rect.left)),top:rect.bottom+330<window.innerHeight?rect.bottom+14:Math.max(16,rect.top-310)}}><button className={styles.close} onClick={finish}>×</button><span className={styles.eyebrow}>{index!+1}. lépés / {steps.length}</span><h3>{step.title}</h3><HelpDetails content={step}/><div className={styles.progress}><span style={{width:`${((index!+1)/steps.length)*100}%`}}/></div><div className={styles.actions}><button className={styles.ghost} onClick={finish}>Kilépés</button><div className={styles.group}>{index!>0&&<button className={styles.ghost} onClick={prev}>Vissza</button>}<button className={styles.button} onClick={next}>{index===steps.length-1?"Befejezés":"Tovább"}</button></div></div></div></>}</>}
export function TourRestartButton({role}:{role:TourRole}){return <button type="button" className={styles.restart} onClick={()=>window.dispatchEvent(new Event(`agrar-tour-${role}`))}>Teljes virtuális túra</button>}
export function BlockHelpButton({content,label="Blokk magyarázata"}:{content:HelpContent;label?:string}){const[open,setOpen]=useState(false);return <><button type="button" className={styles.infoButton} aria-label={label} title={label} onClick={()=>setOpen(true)}>i</button>{open&&<div className={styles.helpOverlay} onMouseDown={()=>setOpen(false)}><div className={styles.helpCard} role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setOpen(false)}>×</button><span className={styles.eyebrow}>Gyors segítség</span><h3>{content.title}</h3><HelpDetails content={content}/><div className={styles.helpFooter}><button className={styles.button} onClick={()=>setOpen(false)}>Értem</button></div></div></div>}</>}
export function TourBlockHelp({role,helpId,label}:{role:TourRole;helpId:string;label?:string}){const content=tours[role].steps.find(s=>s.helpId===helpId);if(!content)return null;return <BlockHelpButton content={content} label={label}/>}
