"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import styles from "./HelpCenter.module.css";

type Role="advisor"|"farmer";
type Topic={title:string;summary:string;example:string;href:string;steps:string[];important?:string};
const advisor:Topic[]=[
 {title:"Ügyfél meghívása",summary:"Új gazdálkodói felhasználó meghívása és az ügyfélkapcsolat létrehozása.",example:"Kovács Pétert meghívod az e-mail-címével, majd a regisztráció után létrehozod a gazdaságát.",href:"/admin/clients",steps:["Nyisd meg az Ügyfelek oldalt.","Indítsd az új ügyfél meghívását.","Add meg a nevet és a helyes e-mail-címet.","Küldd el a meghívást.","A gazdálkodó aktiválása után rendeld hozzá a gazdaságot."],important:"A belépési e-mail és a gazdasági kapcsolattartási elérhetőségek külön adatok."},
 {title:"Gazdaság létrehozása és kapcsolattartók",summary:"Gazdaság rögzítése több telefonszámmal és e-mail címmel.",example:"Kovács Péterhez létrehozod a családi gazdaságot, majd rögzíted a tulajdonos és a telepvezető telefonszámát, valamint az irodai e-mail címet.",href:"/admin/clients",steps:["Válaszd ki a gazdálkodót.","Add meg a gazdaság nevét, települését és címét.","Adj meg legalább egy névhez kötött telefonszámot.","Adj meg legalább egy e-mail címet.","Szükség esetén adj hozzá további kapcsolatokat.","A későbbi módosításokat az Elérhetőségek oldalon végezd el."],important:"A rendszer ellenőrzi az e-mail formátumot, normalizálja a telefonszámot és kiszűri a duplikált elérhetőségeket."},
 {title:"Elérhetőségek kezelése",summary:"Gazdasági és szaktanácsadói telefonszámok/e-mail címek utólagos karbantartása.",example:"A telepvezető telefonszáma megváltozik, ezért átírod az adatot és elsődlegesként jelölöd.",href:"/admin/contacts",steps:["Nyisd meg az Elérhetőségeket.","Válaszd ki a gazdaságot vagy a saját szaktanácsadói elérhetőségeidet.","Módosítsd, töröld vagy egészítsd ki a kapcsolatokat.","Jelöld ki az elsődleges telefon- és e-mail címet.","Mentsd a változásokat."],important:"Telefon esetén mindig legyen egyértelmű kapcsolattartói név. A telefonszámra vagy e-mailre kattintva a készülék megfelelő hívó/levelező alkalmazása nyílik meg."},
 {title:"Földtábla létrehozása",summary:"Új művelt terület kapcsolása a megfelelő gazdasághoz.",example:"A gazdasághoz felveszed a „Déli 12” nevű, 12,4 hektáros kukoricatáblát.",href:"/admin/clients",steps:["Válaszd ki a gazdaságot.","Add meg a tábla nevét.","Rögzítsd a területet hektárban.","Add meg a helyadatokat és a kultúrát, ha az űrlap kéri.","Mentsd a földtáblát, majd ellenőrizd a gazdaság adatlapján."]},
 {title:"Szemle rögzítése és gazdálkodói visszajelzés",summary:"Helyszíni állapot, belső szakmai jegyzet, média és gazdálkodónak szóló észrevétel dokumentálása.",example:"A kukoricatáblán javulást látsz. Belső jegyzetet készítesz, majd külön üzenetben jelzed a gazdának, hogy jelenleg új beavatkozás nem szükséges.",href:"/admin/inspections",steps:["Válaszd ki az ügyfelet, gazdaságot és táblát.","Rögzítsd a szemle dátumát és állapotát.","A belső szakmai megfigyelést a belső mezőbe írd.","A gazdának szánt pozitív vagy negatív visszajelzést a külön gazdálkodói mezőbe írd.","Állítsd be, küldjön-e a rendszer harangértesítést és e-mailt.","Szükség esetén hozz létre teendőt és csatolj képet/videót.","Mentsd a szemlét."],important:"A belső szakmai jegyzet nem kerül gazdálkodói e-mailbe, közös idővonalba vagy automatikus gazdafeladatba. Az e-mail átmeneti hibája nem törli a már sikeresen rögzített szemlét."},
 {title:"Bejelentések, Látta és utánkövetés",summary:"Gazdálkodói jelzések kezelése tényleges megnyitási visszajelzéssel és saját emlékeztetővel.",example:"A gazda levéltünetet jelez. Megnyitod a bejegyzést, válaszolsz, majd holnapra saját emlékeztetőt állítasz be a visszaellenőrzéshez.",href:"/admin/reports",steps:["Nyisd meg az új bejelentést a részletes nézetben.","A rendszer csak ekkor rögzíti a tényleges megtekintést; az átgörgetés nem számít.","Írj szakmai választ vagy adj ki teendőt.","Ellenőrizd később a ✓✓ visszajelzést, hogy a gazdálkodó megnyitotta-e a válaszod.","Ha később akarsz visszatérni rá, állíts be privát emlékeztetőt.","Az emlékeztetőt szükség esetén töröld vagy ütemezd újra."],important:"Az értesítés olvasott állapota és a szakmai tartalom Látta állapota nem ugyanaz. A Látta csak a konkrét tartalom tudatos megnyitásakor keletkezik."},
 {title:"Értesítések",summary:"A gazda–szaktanácsadó munkafolyamat fontos eseményeinek követése.",example:"A gazda beküld egy végrehajtást ellenőrzésre, ezért a harangnál azonnal megjelenik a szaktanácsadói teendő.",href:"/notifications",steps:["Nyisd meg az értesítési központot.","Nézd át az olvasatlan eseményeket.","A Megnyitás gombbal lépj közvetlenül a kapcsolódó tartalomhoz.","A konkrét szakmai bejegyzést is nyisd meg, ha Látta visszajelzést kell rögzíteni.","A feldolgozott értesítéseket jelöld olvasottnak."],important:"A harangértesítés a munkafolyamat jelzése; nem helyettesíti a kapcsolódó szakmai tartalom részletes ellenőrzését."},
 {title:"Növényvédelmi katalógus",summary:"HU/SK hivatalos források, készítmények, engedélyek és szabályozási státuszok áttekintése.",example:"Ellenőrzöd, hogy egy készítmény Magyarországon hatályos, türelmi idő alatt áll vagy már nem alkalmazható.",href:"/admin/plant-protection-import",steps:["Válaszd ki az országot.","Ellenőrizd a forrás és frissítés állapotát.","Keress készítményre vagy engedélyre.","Olvasd el a státuszt és a határidőket.","Eltérés esetén mindig a hatályos engedélyokiratot tekintsd irányadónak."],important:"A katalógus döntéstámogatás; hatósági vagy jogi bizonytalanságnál az aktuális hivatalos dokumentum az irányadó."},
 {title:"Műveleti napló ellenőrzése",summary:"A gazdaság által rögzített műveletek, dózisok és jóváhagyási státuszok szakmai követése.",example:"Megnézed, hogy a javasolt kezelés milyen dózissal és ki által került rögzítésre.",href:"/admin/operations",steps:["Szűrj művelettípusra vagy gazdaságra.","Nyisd meg a műveleti adatlapot.","Ellenőrizd a készítményt, dózist és dátumot.","Tekintsd meg a jóváhagyási és auditadatokat.","Szükség esetén egyeztess a gazdasággal."]},
 {title:"Térkép használata",summary:"Ügyfelek és földtáblák területi áttekintése.",example:"Szemle előtt megkeresed a „Déli 12” táblát és ellenőrzöd a helyét.",href:"/admin/map",steps:["Nyisd meg a térképet.","Válaszd ki az ügyfelet/gazdaságot.","Keresd meg a táblát.","Nagyíts a területre.","Nyisd meg a kapcsolódó adatlapot."]},
 {title:"Dokumentumok",summary:"A gazdaságokhoz kapcsolódó dokumentumok áttekintése.",example:"Egy korábbi jegyzőkönyvet vagy gazdasági dokumentumot keresel vissza.",href:"/admin/documents",steps:["Nyisd meg a Dokumentumokat.","Szűrj a megfelelő ügyfélre vagy gazdaságra.","Nyisd meg a dokumentumot.","Ellenőrizd a kapcsolódó adatokat és dátumot."]}
];
const farmer:Topic[]=[
 {title:"Gazdaságom",summary:"A saját gazdaság alapadatainak és kapcsolódó területeinek áttekintése.",example:"Ellenőrzöd, hogy minden tábla a megfelelő gazdasághoz tartozik.",href:"/farms",steps:["Nyisd meg a Gazdaságom menüt.","Válaszd ki a gazdaságot.","Ellenőrizd az alapadatokat.","Nyisd meg a kapcsolódó táblákat."]},
 {title:"Táblák",summary:"Földterületek, kultúrák és kapcsolódó előzmények megtekintése.",example:"A „Déli 12” táblán ellenőrzöd a területet, kultúrát és előző műveleteket.",href:"/fields",steps:["Nyisd meg a Táblák oldalt.","Válaszd ki a földtáblát.","Ellenőrizd az alapadatokat és kultúrát.","Nézd át a szemléket, teendőket és műveleteket."]},
 {title:"Művelet rögzítése",summary:"Elvégzett agrármunka rögzítése a gazdálkodási naplóban.",example:"Kukorica gyomirtást rögzítesz a hivatalos készítménnyel és engedélyezett dózissal.",href:"/operations",steps:["Válaszd ki a földtáblát.","Add meg a dátumot és művelettípust.","Növényvédelemnél válaszd ki a készítményt és engedélyezett felhasználást.","Válassz hivatalos dózist vagy adj meg annál nem nagyobb egyéni dózist.","Add meg a gépet és végrehajtót, ha szükséges.","Engedélyköteles műveletnél jelöld ki a jogosult jóváhagyót.","Ellenőrizd az adatokat és mentsd a műveletet."],important:"Egyéni dózis nem lehet nagyobb a hivatalosan megengedett maximumnál."},
 {title:"Jóváhagyások",summary:"Jogosultsághoz kötött kijuttatások gazdasági jóváhagyása.",example:"A kijelölt jogosult személy ellenőrzi az engedélyköteles kezelést és jóváhagyja végrehajtás előtt.",href:"/operations/approvals",steps:["Nyisd meg a Jóváhagyásokat.","Válaszd ki a függőben lévő műveletet.","Ellenőrizd a szert, dózist, táblát és dátumot.","Ellenőrizd a saját jogosultságodat.","Csak megfelelő adatok esetén hagyd jóvá."],important:"A jóváhagyás felelősségi művelet; ne hagyj jóvá olyan kijuttatást, amelyhez nincs megfelelő érvényes jogosultság."},
 {title:"Teendők",summary:"Határidős feladatok és szaktanácsadói javaslatok követése.",example:"A szemléből létrejött „Gyomirtás augusztus 30-ig” feladatot elvégzés után lezárod.",href:"/tasks",steps:["Nyisd meg a Teendőket.","Ellenőrizd a határidőt és a kapcsolódó táblát.","Nyisd meg a részleteket.","Végezd el vagy szervezd ki a munkát.","Teljesítés után frissítsd a státuszt."]},
 {title:"Munkatársak és jogosultság",summary:"A gazdaságban dolgozó személyek és feladataik kezelése.",example:"Felveszed a növényvédelmi munkát végző jogosult személyt a gazdaság csapatába.",href:"/team",steps:["Nyisd meg a Munkatársakat.","Ellenőrizd a meglévő személyeket.","Add hozzá a szükséges munkatársat.","Rögzítsd a rendszer által kért szerep/jogosultsági adatokat.","Ellenőrizd az érvényességet."]},
 {title:"Munkakiosztás",summary:"Feladatok kiosztása a gazdaság munkatársainak.",example:"A permetezési feladatot a megfelelő gépkezelőhöz rendeled.",href:"/dispatch",steps:["Nyisd meg a Munkakiosztást.","Válaszd ki a munkát.","Jelöld ki a végrehajtót.","Add meg a határidőt és szükséges megjegyzést.","Mentsd a kiosztást."]},
 {title:"Géppark",summary:"Traktorok, permetezők és más gépek nyilvántartása.",example:"Felveszed a gazdaság permetezőgépét, hogy műveletnél kiválasztható legyen.",href:"/machines",steps:["Nyisd meg a Gépparkot.","Indíts új gép felvételét.","Add meg a gép nevét és típusát.","Töltsd ki a gyártó/modell adatokat, ha ismertek.","Mentsd és ellenőrizd, hogy aktívként megjelent."]},
 {title:"Üzenetek, Látta és emlékeztető",summary:"Kapcsolattartás a szaktanácsadóval tényleges megtekintési visszajelzéssel és saját utánkövetéssel.",example:"A szaktanácsadó válaszol egy bejelentésedre. Megnyitod a választ, majd holnapra emlékeztetőt állítasz be, hogy elvégezd a javasolt ellenőrzést.",href:"/messages",steps:["Nyisd meg az Üzeneteket.","A konkrét bejegyzést nyisd meg a részletek megtekintéséhez.","A rendszer csak ekkor jelöli ténylegesen megtekintettnek; az átgörgetés nem számít.","Ha most nincs időd foglalkozni vele, állíts be privát emlékeztetőt.","Az emlékeztetőt később törölheted vagy új időpontra teheted."],important:"Az emlékeztetőd privát. A szaktanácsadó nem látja. Az értesítés olvasott állapota és a szakmai bejegyzés Látta állapota két külön dolog."},
 {title:"Szaktanácsadó közvetlen elérése",summary:"A megosztott telefonszám és e-mail cím közvetlen használata.",example:"A szaktanácsadó telefonszámára kattintasz, és a telefon hívási felülete megnyílik.",href:"/farms",steps:["Keresd meg a szaktanácsadó megosztott elérhetőségét.","Telefon esetén koppints a számra a hívási funkció megnyitásához.","E-mail esetén koppints a címre a levelezőprogram megnyitásához.","Írd meg az üzenetet a saját levelezőalkalmazásodban."],important:"A kattintás önmagában nem küld el e-mailt és nem indít automatikusan hívást jóváhagyás nélkül; a készülék megfelelő alkalmazását nyitja meg."},
 {title:"Értesítések",summary:"Szaktanácsadói válaszok, szemleészrevételek és munkafolyamat-események követése.",example:"A szaktanácsadó új szemleészrevételt küld, amely megjelenik a harangnál.",href:"/notifications",steps:["Nyisd meg az értesítési központot.","Nézd meg az olvasatlan eseményeket.","A Megnyitás gombbal lépj közvetlenül a kapcsolódó tartalomhoz.","A konkrét szakmai bejegyzést is nyisd meg, ha Látta visszajelzést szeretnél rögzíteni.","A feldolgozott értesítéseket jelöld olvasottnak."],important:"Az értesítés olvasottnak jelölése önmagában nem jelent szakmai Látta visszajelzést."},
 {title:"Dokumentumok és idővonal",summary:"Korábbi események és dokumentumok visszakeresése.",example:"Egy régi szemle vagy művelet időpontját keresed vissza ellenőrzéshez.",href:"/timeline",steps:["Nyisd meg az Idővonalat.","Keresd meg az időszakot vagy eseményt.","Nyisd meg a kapcsolódó adatlapot.","Dokumentum esetén válts a Dokumentumok menüre."]}
];
export function HelpCenter({role}:{role:Role}){const topics=role==="advisor"?advisor:farmer;const[open,setOpen]=useState(false);const[q,setQ]=useState("");const filtered=useMemo(()=>topics.filter(t=>(t.title+" "+t.summary+" "+t.example).toLowerCase().includes(q.toLowerCase())),[topics,q]);return <><button type="button" className={styles.launch} onClick={()=>setOpen(true)}>?</button>{open&&<div className={styles.overlay} onMouseDown={()=>setOpen(false)}><section className={styles.panel} onMouseDown={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setOpen(false)}>×</button><span className={styles.eyebrow}>AGRÁR MENTOR SÚGÓKÖZPONT</span><h2>Miben segíthetünk?</h2><p>Keress rá egy feladatra, vagy válassz az oktatóanyagok közül.</p><input className={styles.search} value={q} onChange={e=>setQ(e.target.value)} placeholder="Például: művelet, gazdaság, jóváhagyás…"/><div className={styles.list}>{filtered.map(t=><details key={t.title} className={styles.topic}><summary>{t.title}<small>{t.summary}</small></summary><div className={styles.body}>{t.important&&<aside><b>Fontos</b>{t.important}</aside>}<div className={styles.example}><b>Gyakorlati példa</b>{t.example}</div><b>Lépésről lépésre</b><ol>{t.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><Link href={t.href} onClick={()=>setOpen(false)}>Nyisd meg ezt a funkciót →</Link></div></details>)}</div></section></div>}</>}
