"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import styles from "./HelpCenter.module.css";

type Role="advisor"|"farmer";
type Topic={title:string;summary:string;example:string;href:string;steps:string[];important?:string};
const advisor:Topic[]=[
 {title:"Ügyfél meghívása",summary:"Új gazdálkodói felhasználó meghívása és az ügyfélkapcsolat létrehozása.",example:"Kovács Pétert meghívod az e-mail-címével, majd a regisztráció után létrehozod a gazdaságát.",href:"/admin/clients",steps:["Nyisd meg az Ügyfelek oldalt.","Indítsd az új ügyfél meghívását.","Add meg a nevet és a helyes e-mail-címet.","Küldd el a meghívást.","A gazdálkodó aktiválása után rendeld hozzá a gazdaságot."],important:"Meghívás előtt ellenőrizd az e-mail-címet; a fiók és a gazdasági adatok külön fogalmak."},
 {title:"Gazdaság létrehozása",summary:"Gazdaság rögzítése egy már létező gazdálkodóhoz.",example:"Kovács Péterhez létrehozod a „Kovács Családi Gazdaság” gazdaságot Nagykátán.",href:"/admin",steps:["Nyisd le az ügyfél/gazdaság/földtábla felvételi részt.","Válaszd ki a gazdálkodót.","Add meg a gazdaság nevét.","Add meg a települést és szükség esetén a címet.","Nyomd meg a Gazdaság létrehozása gombot." ]},
 {title:"Földtábla létrehozása",summary:"Új művelt terület kapcsolása a megfelelő gazdasághoz.",example:"A gazdasághoz felveszed a „Déli 12” nevű, 12,4 hektáros kukoricatáblát.",href:"/admin",steps:["Válaszd ki a gazdaságot.","Add meg a tábla nevét.","Rögzítsd a területet hektárban.","Add meg a helyadatokat és a kultúrát, ha az űrlap kéri.","Mentsd a földtáblát, majd ellenőrizd a gazdaság adatlapján." ]},
 {title:"Szemle rögzítése",summary:"Helyszíni állapot, megfigyelés, média és szakmai javaslat dokumentálása.",example:"A kukoricatáblán erős gyomosodást észlelsz, fényképet csatolsz és gyomirtási javaslatot adsz.",href:"/admin/workday",steps:["Válaszd ki az ügyfelet, gazdaságot és táblát.","Rögzítsd a szemle dátumát és az állapotot.","Írd le a megfigyelést.","Csatolj képet/videót, ha szükséges.","Adj szakmai javaslatot és határidős teendőt.","Mentsd a szemlét."],important:"A szaktanácsadói javaslat nem azonos a gazdaság kijuttatási jóváhagyásával."},
 {title:"Növényvédelmi katalógus",summary:"HU/SK hivatalos források, készítmények, engedélyek és szabályozási státuszok áttekintése.",example:"Ellenőrzöd, hogy egy készítmény Magyarországon hatályos, türelmi idő alatt áll vagy már nem alkalmazható.",href:"/admin/plant-protection-import",steps:["Válaszd ki az országot.","Ellenőrizd a forrás és frissítés állapotát.","Keress készítményre vagy engedélyre.","Olvasd el a státuszt és a határidőket.","Eltérés esetén mindig a hatályos engedélyokiratot tekintsd irányadónak."],important:"A katalógus döntéstámogatás; hatósági vagy jogi bizonytalanságnál az aktuális hivatalos dokumentum az irányadó."},
 {title:"Műveleti napló ellenőrzése",summary:"A gazdaság által rögzített műveletek, dózisok és jóváhagyási státuszok szakmai követése.",example:"Megnézed, hogy a javasolt kezelés milyen dózissal és ki által került rögzítésre.",href:"/admin/operations",steps:["Szűrj művelettípusra vagy gazdaságra.","Nyisd meg a műveleti adatlapot.","Ellenőrizd a készítményt, dózist és dátumot.","Tekintsd meg a jóváhagyási és auditadatokat.","Szükség esetén egyeztess a gazdasággal." ]},
 {title:"Térkép használata",summary:"Ügyfelek és földtáblák területi áttekintése.",example:"Szemle előtt megkeresed a „Déli 12” táblát és ellenőrzöd a helyét.",href:"/admin/map",steps:["Nyisd meg a térképet.","Válaszd ki az ügyfelet/gazdaságot.","Keresd meg a táblát.","Nagyíts a területre.","Nyisd meg a kapcsolódó adatlapot." ]},
 {title:"Dokumentumok",summary:"A gazdaságokhoz kapcsolódó dokumentumok áttekintése.",example:"Egy korábbi jegyzőkönyvet vagy gazdasági dokumentumot keresel vissza.",href:"/admin/documents",steps:["Nyisd meg a Dokumentumokat.","Szűrj a megfelelő ügyfélre vagy gazdaságra.","Nyisd meg a dokumentumot.","Ellenőrizd a kapcsolódó adatokat és dátumot." ]}
];
const farmer:Topic[]=[
 {title:"Gazdaságom",summary:"A saját gazdaság alapadatainak és kapcsolódó területeinek áttekintése.",example:"Ellenőrzöd, hogy minden tábla a megfelelő gazdasághoz tartozik.",href:"/farms",steps:["Nyisd meg a Gazdaságom menüt.","Válaszd ki a gazdaságot.","Ellenőrizd az alapadatokat.","Nyisd meg a kapcsolódó táblákat." ]},
 {title:"Táblák",summary:"Földterületek, kultúrák és kapcsolódó előzmények megtekintése.",example:"A „Déli 12” táblán ellenőrzöd a területet, kultúrát és előző műveleteket.",href:"/fields",steps:["Nyisd meg a Táblák oldalt.","Válaszd ki a földtáblát.","Ellenőrizd az alapadatokat és kultúrát.","Nézd át a szemléket, teendőket és műveleteket." ]},
 {title:"Művelet rögzítése",summary:"Elvégzett agrármunka rögzítése a gazdálkodási naplóban.",example:"Kukorica gyomirtást rögzítesz a hivatalos készítménnyel és engedélyezett dózissal.",href:"/operations",steps:["Válaszd ki a földtáblát.","Add meg a dátumot és művelettípust.","Növényvédelemnél válaszd ki a készítményt és engedélyezett felhasználást.","Válassz hivatalos dózist vagy adj meg annál nem nagyobb egyéni dózist.","Add meg a gépet és végrehajtót, ha szükséges.","Engedélyköteles műveletnél jelöld ki a jogosult jóváhagyót.","Ellenőrizd az adatokat és mentsd a műveletet."],important:"Egyéni dózis nem lehet nagyobb a hivatalosan megengedett maximumnál."},
 {title:"Jóváhagyások",summary:"Jogosultsághoz kötött kijuttatások gazdasági jóváhagyása.",example:"A kijelölt jogosult személy ellenőrzi az engedélyköteles kezelést és jóváhagyja végrehajtás előtt.",href:"/operations/approvals",steps:["Nyisd meg a Jóváhagyásokat.","Válaszd ki a függőben lévő műveletet.","Ellenőrizd a szert, dózist, táblát és dátumot.","Ellenőrizd a saját jogosultságodat.","Csak megfelelő adatok esetén hagyd jóvá."],important:"A jóváhagyás felelősségi művelet; ne hagyj jóvá olyan kijuttatást, amelyhez nincs megfelelő érvényes jogosultság."},
 {title:"Teendők",summary:"Határidős feladatok és szaktanácsadói javaslatok követése.",example:"A szemléből létrejött „Gyomirtás augusztus 30-ig” feladatot elvégzés után lezárod.",href:"/tasks",steps:["Nyisd meg a Teendőket.","Ellenőrizd a határidőt és a kapcsolódó táblát.","Nyisd meg a részleteket.","Végezd el vagy szervezd ki a munkát.","Teljesítés után frissítsd a státuszt." ]},
 {title:"Munkatársak és jogosultság",summary:"A gazdaságban dolgozó személyek és feladataik kezelése.",example:"Felveszed a növényvédelmi munkát végző jogosult személyt a gazdaság csapatába.",href:"/team",steps:["Nyisd meg a Munkatársakat.","Ellenőrizd a meglévő személyeket.","Add hozzá a szükséges munkatársat.","Rögzítsd a rendszer által kért szerep/jogosultsági adatokat.","Ellenőrizd az érvényességet." ]},
 {title:"Munkakiosztás",summary:"Feladatok kiosztása a gazdaság munkatársainak.",example:"A permetezési feladatot a megfelelő gépkezelőhöz rendeled.",href:"/dispatch",steps:["Nyisd meg a Munkakiosztást.","Válaszd ki a munkát.","Jelöld ki a végrehajtót.","Add meg a határidőt és szükséges megjegyzést.","Mentsd a kiosztást." ]},
 {title:"Géppark",summary:"Traktorok, permetezők és más gépek nyilvántartása.",example:"Felveszed a gazdaság permetezőgépét, hogy műveletnél kiválasztható legyen.",href:"/machines",steps:["Nyisd meg a Gépparkot.","Indíts új gép felvételét.","Add meg a gép nevét és típusát.","Töltsd ki a gyártó/modell adatokat, ha ismertek.","Mentsd és ellenőrizd, hogy aktívként megjelent." ]},
 {title:"Üzenetek",summary:"Kapcsolattartás a szaktanácsadóval.",example:"Képet és kérdést küldesz egy frissen észlelt növényvédelmi problémáról.",href:"/messages",steps:["Nyisd meg az Üzeneteket.","Válaszd ki a beszélgetést.","Írd le röviden és pontosan a kérdést.","Csatolj releváns információt vagy képet, ha lehetséges.","Küldd el az üzenetet." ]},
 {title:"Dokumentumok és idővonal",summary:"Korábbi események és dokumentumok visszakeresése.",example:"Egy régi szemle vagy művelet időpontját keresed vissza ellenőrzéshez.",href:"/timeline",steps:["Nyisd meg az Idővonalat.","Keresd meg az időszakot vagy eseményt.","Nyisd meg a kapcsolódó adatlapot.","Dokumentum esetén válts a Dokumentumok menüre." ]}
];
export function HelpCenter({role}:{role:Role}){const topics=role==="advisor"?advisor:farmer;const[open,setOpen]=useState(false);const[q,setQ]=useState("");const filtered=useMemo(()=>topics.filter(t=>(t.title+" "+t.summary+" "+t.example).toLowerCase().includes(q.toLowerCase())),[topics,q]);return <><button type="button" className={styles.launch} onClick={()=>setOpen(true)}>?</button>{open&&<div className={styles.overlay} onMouseDown={()=>setOpen(false)}><section className={styles.panel} onMouseDown={e=>e.stopPropagation()}><button className={styles.close} onClick={()=>setOpen(false)}>×</button><span className={styles.eyebrow}>AGRÁR MENTOR SÚGÓKÖZPONT</span><h2>Miben segíthetünk?</h2><p>Keress rá egy feladatra, vagy válassz az oktatóanyagok közül.</p><input className={styles.search} value={q} onChange={e=>setQ(e.target.value)} placeholder="Például: művelet, gazdaság, jóváhagyás…"/ ><div className={styles.list}>{filtered.map(t=><details key={t.title} className={styles.topic}><summary>{t.title}<small>{t.summary}</small></summary><div className={styles.body}>{t.important&&<aside><b>Fontos</b>{t.important}</aside>}<div className={styles.example}><b>Gyakorlati példa</b>{t.example}</div><b>Lépésről lépésre</b><ol>{t.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><Link href={t.href} onClick={()=>setOpen(false)}>Nyisd meg ezt a funkciót →</Link></div></details>)}</div></section></div>}</>}
