"use client";
import {useEffect,useRef,useState} from "react";
import {createHotspot} from "@/app/fields/[id]/hotspot-actions";
import {hotspotTypes} from "@/lib/hotspots";
declare global{interface Window{L:any}}
export function HotspotForm({fieldId,boundary,lat,lng,isAdvisor}:{fieldId:string;boundary:any|null;lat:number|null;lng:number|null;isAdvisor:boolean}){
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),markerRef=useRef<any>(null);const[pLat,setPLat]=useState<number|null>(null),[pLng,setPLng]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{function css(href:string){if(document.querySelector(`link[href="${href}"]`))return;const l=document.createElement("link");l.rel="stylesheet";l.href=href;document.head.appendChild(l)}function script(src:string){return new Promise<void>((resolve,reject)=>{const f=document.querySelector(`script[src="${src}"]`) as HTMLScriptElement|null;if(f){if(window.L)resolve();else f.addEventListener("load",()=>resolve(),{once:true});return}const s=document.createElement("script");s.src=src;s.async=true;s.onload=()=>resolve();s.onerror=reject;document.body.appendChild(s)})}let cancelled=false;(async()=>{css("https://unpkg.com/leaflet@1.9.4/dist/leaflet.css");await script("https://unpkg.com/leaflet@1.9.4/dist/leaflet.js");if(cancelled||!mapEl.current||mapRef.current)return;const L=window.L,map=L.map(mapEl.current).setView(lat!=null&&lng!=null?[lat,lng]:[47.2,19.5],lat!=null?15:7);mapRef.current=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; OpenStreetMap közreműködők'}).addTo(map);if(boundary){const layer=L.geoJSON(boundary,{style:{color:"#287a35",fillColor:"#49a557",weight:2,fillOpacity:.14}}).addTo(map);try{map.fitBounds(layer.getBounds(),{padding:[20,20]})}catch{}}function setPoint(a:number,b:number){setPLat(a);setPLng(b);if(markerRef.current)markerRef.current.setLatLng([a,b]);else markerRef.current=L.circleMarker([a,b],{radius:9,color:"#7a1f1a",fillColor:"#d93d36",fillOpacity:1,weight:3}).addTo(map)}map.on("click",(e:any)=>setPoint(e.latlng.lat,e.latlng.lng));})();return()=>{cancelled=true;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[boundary,lat,lng]);
 function myLocation(){if(!navigator.geolocation){setMessage("A böngésző nem támogatja a helymeghatározást.");return}navigator.geolocation.getCurrentPosition(p=>{const a=p.coords.latitude,b=p.coords.longitude;setPLat(a);setPLng(b);const L=window.L;if(mapRef.current){mapRef.current.setView([a,b],17);if(markerRef.current)markerRef.current.setLatLng([a,b]);else markerRef.current=L.circleMarker([a,b],{radius:9,color:"#7a1f1a",fillColor:"#d93d36",fillOpacity:1,weight:3}).addTo(mapRef.current)}},()=>setMessage("A helymeghatározás nem sikerült."),{enableHighAccuracy:true,timeout:10000})}
 async function submit(fd:FormData){setBusy(true);setMessage("");try{await createHotspot(fd);setMessage("A problémagóc rögzítve.");setTimeout(()=>window.location.reload(),500)}catch(e){setMessage(e instanceof Error?e.message:"A mentés sikertelen.");setBusy(false)}}
 return <form action={submit} style={{display:"grid",gap:14}}><input type="hidden" name="field_id" value={fieldId}/><input type="hidden" name="lat" value={pLat??""}/><input type="hidden" name="lng" value={pLng??""}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><label>Probléma típusa<select name="type" required defaultValue="weed">{hotspotTypes.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Súlyosság<select name="severity" defaultValue="warning"><option value="warning">Figyelmeztetés</option><option value="critical">Kritikus</option></select></label>{isAdvisor&&<label>Határidő, ha teendő is készül<input type="date" name="due_date"/></label>}</div><div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:8}}><strong>Probléma helye</strong><button type="button" className="ghost-btn" onClick={myLocation}>Saját GPS-helyzetem</button></div><div ref={mapEl} style={{height:360,borderRadius:12,overflow:"hidden",background:"#e7ece7"}}/><small style={{display:"block",marginTop:7,color:"#6f7c74"}}>{pLat!=null?`Kijelölt pont: ${pLat.toFixed(6)}, ${pLng?.toFixed(6)}`:"Kattints a térképen arra a pontra, ahol a problémát észlelted."}</small></div><label>Megjegyzés<textarea name="notes" rows={4} maxLength={4000} placeholder="Mit látsz, mekkora területet érint, mire kell figyelni?"/></label>{isAdvisor&&<label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" name="create_task" value="yes"/> Készüljön belőle automatikusan teendő a gazdálkodónak</label>}{message&&<div className={message.includes("rögzítve")?"success-box":"error-box"}>{message}</div>}<button className="btn btn-primary" disabled={busy||pLat==null}>{busy?"Mentés…":"Problémagóc rögzítése"}</button></form>}
