"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import styles from "./LandingLoginModal.module.css";
export function LandingLoginModal({triggerLabel,triggerClassName,initialOpen=false,next=null}:{triggerLabel:string;triggerClassName?:string;initialOpen?:boolean;next?:string|null}){
 const supabase=useMemo(()=>createClient(),[]),[open,setOpen]=useState(initialOpen),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow="hidden";const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("keydown",esc);return()=>{document.body.style.overflow=prev;document.removeEventListener("keydown",esc)}},[open]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setBusy(false);setError("Sikertelen belépés. Ellenőrizd az e-mail címet és a jelszót.");return}window.location.assign(next?`/mfa?next=${encodeURIComponent(next)}`:"/mfa")}
 async function recover(){setError("");setMessage("");if(!email){setError("Add meg előbb az e-mail címedet.");return}setBusy(true);const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setBusy(false);if(error){setError("A jelszó-visszaállító e-mail küldése sikertelen.");return}setMessage("Elküldtük a jelszó-visszaállító e-mailt.")}
 return <><button type="button" className={triggerClassName} onClick={()=>setOpen(true)}>{triggerLabel}</button>{open&&<div className={styles.overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="agrar-login-title"><button className={styles.close} type="button" aria-label="Bejelentkezés bezárása" onClick={()=>setOpen(false)}>×</button><div className={styles.brand}><span><svg viewBox="0 0 42 54"><path d="M21 51V8"/><path d="M21 17C14 14 10 10 9 5c7 1 11 5 12 12Z"/><path d="M21 25c7-3 11-7 12-12-7 1-11 5-12 12Z"/><path d="M21 32c-7-3-11-7-12-12 7 1 11 5 12 12Z"/><path d="M21 40c7-3 11-7 12-12-7 1-11 5-12 12Z"/><path d="M21 47c-7-3-11-7-12-12 7 1 11 5 12 12Z"/></svg></span><div><strong>AGRÁR MENTOR</strong><small>TUDÁS. TERV. EREDMÉNY.</small></div></div><h2 id="agrar-login-title">Belépés az ügyfélfelületre</h2><p>Lépj be az Agrár Mentor digitális ügyfélfelületére.</p><form onSubmit={submit}><label>E-mail cím<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required autoFocus/></label><label>Jelszó<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.success}>{message}</div>}<button className={styles.primary} disabled={busy}>{busy?"Belépés…":"Belépés"}</button><button type="button" className={styles.secondary} onClick={recover} disabled={busy}>Elfelejtett jelszó</button></form><small className={styles.security}>Biztonságos belépés személyes agronómiai háttérrel.</small></section></div>}</>
}
