"use client";

import {useEffect,useMemo,useState} from "react";
import {createPlannedOperationTask} from "@/app/admin/tasks/operation-actions";
import {operationTypes} from "@/lib/operations";
import {fertilizerCatalog,soilWork,type CountryCode} from "@/lib/operationCatalog";
import {PlantProtectionUseDetails} from "@/components/PlantProtectionUseDetails";

type Field={id:string;farmId:string;farmName:string;name:string;areaHa:number|null;crop:string|null;countryCode:CountryCode};
type Person={id:string;farmId:string;name:string;roleLabel:string};
type Machine={id:string;farmId:string;name:string;detail?:string};
type CatalogItem={id:string;name:string;category:string;metadata?:Record<string,unknown>};
type Product={id:string;name:string;authorization_number:string|null;function_type:string|null;regulatory_category:string|null;professional_use_only:boolean;prescription_required:boolean;approval_required:boolean};
type Use={id:string;product_id:string;crop:string;target:string|null;dose_min:number|null;dose_max:number|null;dose_unit:string|null;application_method:string|null;phi_days:number|null;bbch_min?:number|null;bbch_max?:number|null;max_applications?:number|null;application_interval_days?:number|null;water_volume_min?:number|null;water_volume_max?:number|null;water_volume_unit?:string|null;application_timing?:string|null;restrictions?:string|null;source_reference?:string|null};
type Approver={id:string;full_name:string|null;authorization_level:"I"|"II"|"III";permit_number:string|null;valid_until:string|null;role:string|null};
type CatalogResponse={catalog:CatalogItem[];products:Product[];uses:Use[];approvers?:Approver[];error?:string};
const methodTypes=new Set(["soil_work","sowing","harvest","irrigation","mowing","other"]);

export function OperationTaskPlanForm({fields,people,machines}:{fields:Field[];people:Person[];machines:Machine[]}){
 const[fieldId,setFieldId]=useState(""),[type,setType]=useState("spraying"),[catalog,setCatalog]=useState<CatalogItem[]>([]),[products,setProducts]=useState<Product[]>([]),[uses,setUses]=useState<Use[]>([]),[approvers,setApprovers]=useState<Approver[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[productId,setProductId]=useState(""),[useId,setUseId]=useState(""),[crop,setCrop]=useState(""),[productName,setProductName]=useState(""),[customProduct,setCustomProduct]=useState(""),[dose,setDose]=useState(""),[machineId,setMachineId]=useState("");
 const field=fields.find(f=>f.id===fieldId),farmId=field?.farmId||"",country=field?.countryCode||"HU",spraying=type==="spraying"||type==="plant_protection",fert=type==="fertilizing",method=methodTypes.has(type);
 useEffect(()=>{if(!field)return;let live=true;setLoading(true);setError("");setCatalog([]);setProducts([]);setUses([]);setApprovers([]);setProductId("");setUseId("");setCrop(field.crop||"");setProductName("");setCustomProduct("");setDose("");fetch(`/api/operation-catalog?country=${country}&type=${encodeURIComponent(type)}&farm=${encodeURIComponent(farmId)}`,{cache:"no-store"}).then(async r=>{const b=await r.json() as CatalogResponse;if(!r.ok)throw new Error(b.error||"A katalógus betöltése sikertelen.");return b}).then(b=>{if(!live)return;setCatalog(b.catalog||[]);setProducts(b.products||[]);setUses(b.uses||[]);setApprovers(b.approvers||[])}).catch(e=>{if(live)setError(e instanceof Error?e.message:"A katalógus betöltése sikertelen.")}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[fieldId,type,country,farmId]);
 const cropOptions=useMemo(()=>Array.from(new Set(uses.map(u=>u.crop).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"hu")),[uses]),filteredProducts=useMemo(()=>!spraying||!crop?products:products.filter(p=>uses.some(u=>u.product_id===p.id&&u.crop===crop)),[products,uses,crop,spraying]),productUses=useMemo(()=>uses.filter(u=>u.product_id===productId&&(!crop||u.crop===crop)),[uses,productId,crop]),selectedUse=productUses.find(u=>u.id===useId),selectedProduct=products.find(p=>p.id===productId);
 const category=(selectedProduct?.regulatory_category||"").toUpperCase().replace(".","").trim(),approvalNeeded=!!selectedProduct&&(selectedProduct.approval_required||selectedProduct.professional_use_only||selectedProduct.prescription_required||(country==="HU"&&(category==="I"||category==="II"))),eligibleApprovers=approvers.filter(a=>a.role!=="advisor"&&(category==="I"?a.authorization_level==="I":category==="II"?["I","II"].includes(a.authorization_level):true));
 const availablePeople=people.filter(p=>p.farmId===farmId),availableMachines=machines.filter(m=>m.farmId===farmId),fertOptions=catalog.length?catalog.map(x=>x.name):fertilizerCatalog.map(x=>x.name),methodOptions=catalog.length?catalog.map(x=>x.name):(type==="soil_work"?soilWork:[]),effectiveProduct=productName==="Egyéb"?customProduct:productName;
 function chooseUse(id:string){setUseId(id);const u=productUses.find(x=>x.id===id);if(u?.dose_max!=null)setDose(String(u.dose_max).replace(".",","));else setDose("")}
 async function submit(fd:FormData){setBusy(true);setError("");try{await createPlannedOperationTask(fd);window.location.reload()}catch(e){setError(e instanceof Error?e.message:"A műveleti terv mentése sikertelen.");setBusy(false)}}
 return <form action={submit} className="admin-form operation-form" style={{marginTop:14}}>
  <label>Földtábla<select name="field_id" value={fieldId} onChange={e=>setFieldId(e.target.value)} required><option value="">Válassz földtáblát</option>{fields.map(f=><option key={f.id} value={f.id}>{f.farmName} — {f.name}{f.crop?` · ${f.crop}`:""}</option>)}</select></label><input type="hidden" name="farm_id" value={farmId}/>
  <label>Ország<div style={{minHeight:46,display:"flex",alignItems:"center",padding:"0 12px",border:"1px solid #dce5dc",borderRadius:10,background:"#f7faf7",fontWeight:800}}>{country==="HU"?"🇭🇺 Magyarország":"🇸🇰 Szlovákia"}</div></label>
  <label>Művelet<select name="operation_type" value={type} onChange={e=>setType(e.target.value)}>{operationTypes.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
  <label>Végrehajtó<select name="assigned_to"><option value="">Gazdaság tulajdonosa</option>{availablePeople.map(p=><option key={p.id} value={p.id}>{p.name} · {p.roleLabel}</option>)}</select></label>
  <label>Határidő<input name="due_date" type="date"/></label><label>Prioritás<select name="priority" defaultValue="normal"><option value="normal">Normál</option><option value="high">Fontos</option><option value="urgent">Sürgős</option></select></label>
  {method&&<label>Munkafolyamat<select name="subtype"><option value="">Válassz</option>{methodOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb</option></select></label>}
  {fert&&<><label>Műtrágya / anyag<select value={productName} onChange={e=>setProductName(e.target.value)}><option value="">Válassz</option>{fertOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb / saját</option></select><input type="hidden" name="product" value={effectiveProduct}/></label>{productName==="Egyéb"&&<label>Saját termék<input value={customProduct} onChange={e=>setCustomProduct(e.target.value)} required/></label>}</>}
  {spraying&&<>{uses.length>0&&<label>Kultúra<select name="crop" value={crop} onChange={e=>{setCrop(e.target.value);setProductId("");setUseId("");setDose("")}} required><option value="">Válassz kultúrát</option>{cropOptions.map(c=><option key={c}>{c}</option>)}</select></label>}<label>Készítmény<select name="product_id" value={productId} onChange={e=>{setProductId(e.target.value);setUseId("");setDose("")}} disabled={loading||!crop} required><option value="">{loading?"Betöltés…":crop?"Válassz készítményt":"Előbb kultúrát válassz"}</option>{filteredProducts.map(p=><option key={p.id} value={p.id}>{p.name}{p.regulatory_category?` · ${p.regulatory_category}. kategória`:""}</option>)}</select></label>{productId&&<label>Engedélyezett felhasználás<select name="use_id" value={useId} onChange={e=>chooseUse(e.target.value)} required><option value="">Válassz célt / felhasználást</option>{productUses.map(u=><option key={u.id} value={u.id}>{u.target||u.application_method||u.crop}{u.dose_max!=null?` · max. ${u.dose_max} ${u.dose_unit||""}`:""}</option>)}</select></label>}{selectedUse&&<PlantProtectionUseDetails use={selectedUse} country={country}/>}</>}
  {(spraying||fert)&&<><label>Tervezett dózis<input name="planned_dose" value={dose} onChange={e=>setDose(e.target.value)} inputMode="decimal" required={spraying}/>{selectedUse?.dose_min!=null||selectedUse?.dose_max!=null?<small>Engedélyezett: {selectedUse.dose_min??"—"}–{selectedUse.dose_max??"—"} {selectedUse.dose_unit||""}</small>:null}</label><label>Dózis egysége{selectedUse?.dose_unit?<><input value={selectedUse.dose_unit} readOnly/><input type="hidden" name="dose_unit" value={selectedUse.dose_unit}/></>:<select name="dose_unit" defaultValue={fert?"kg/ha":"l/ha"}><option>l/ha</option><option>kg/ha</option><option>g/ha</option><option>ml/ha</option></select>}</label></>}
  <label>Tervezett terület (ha)<input name="planned_area" inputMode="decimal" defaultValue={field?.areaHa??""}/></label><label>Tervezett összes mennyiség<input name="planned_quantity" inputMode="decimal"/></label><label>Mennyiség egysége<select name="quantity_unit" defaultValue={fert?"kg":"l"}><option>l</option><option>kg</option><option>g</option><option>db</option><option>m³</option><option>t</option></select></label>
  <label>Gép / eszköz<select name="machine_id" value={machineId} onChange={e=>setMachineId(e.target.value)}><option value="">Nincs hozzárendelve</option>{availableMachines.map(m=><option key={m.id} value={m.id}>{m.name}{m.detail?` · ${m.detail}`:""}</option>)}</select></label>
  {approvalNeeded&&<div className="operation-wide" style={{padding:14,border:"1px solid #e1b95d",borderRadius:12,background:"#fffaf0"}}><b>⚠ Gazdasági növényvédelmi jóváhagyás szükséges</b>{eligibleApprovers.length?<label style={{marginTop:8}}>Jóváhagyó<select name="requested_approver_id" required><option value="">Válassz jogosult személyt</option>{eligibleApprovers.map(a=><option key={a.id} value={a.id}>{a.full_name||"Jogosult személy"} · {a.authorization_level}. kategória{a.valid_until?` · ${a.valid_until}-ig`:""}</option>)}</select></label>:<div className="error-box" style={{marginTop:8}}>Nincs megfelelő aktív jóváhagyó beállítva ennél a gazdaságnál.</div>}</div>}
  <label className="operation-wide">Végrehajtási utasítás / megjegyzés<textarea name="notes" rows={3} placeholder="Mikor, milyen körülmények között, mire figyeljen a végrehajtó?"/></label>
  {spraying&&selectedProduct&&selectedUse&&<div className="operation-wide" style={{padding:12,border:"1px solid #dce5dc",borderRadius:12,background:"#f8faf8",fontSize:13}}><b>Hivatalos tervalap</b><br/>{selectedProduct.name}{selectedProduct.authorization_number?` · ${selectedProduct.authorization_number}`:""} · {selectedUse.crop}{selectedUse.target?` · ${selectedUse.target}`:""}{selectedUse.bbch_min!=null?` · BBCH ${selectedUse.bbch_min}${selectedUse.bbch_max!=null?`–${selectedUse.bbch_max}`:""}`:""}{selectedUse.phi_days!=null?` · ÉVI ${selectedUse.phi_days} nap`:""}</div>}
  {error&&<div className="error-box operation-wide">{error}</div>}<button className="btn btn-primary" disabled={busy||loading||!fieldId||(approvalNeeded&&eligibleApprovers.length===0)}>{busy?"Terv mentése…":"Műveleti terv kiadása"}</button>
 </form>
}
