"use client";

import {useEffect,useMemo,useState} from "react";
import {createFieldOperation} from "@/app/operations/actions";
import {operationTypes} from "@/lib/operations";
import {fertilizerCatalog,soilWork,type CountryCode} from "@/lib/operationCatalog";

type FieldOption={id:string;farmId:string;name:string;farmName:string;areaHa:number|null;countryCode?:CountryCode};
type MachineOption={id:string;farmId:string;name:string;detail?:string};
type CatalogItem={id:string;name:string;category:string;metadata?:Record<string,unknown>};
type Product={id:string;name:string;authorization_number:string|null;function_type:string|null;regulatory_category:string|null;professional_use_only:boolean;prescription_required:boolean;approval_required:boolean};
type Use={id:string;product_id:string;crop:string;target:string|null;dose_min:number|null;dose_max:number|null;dose_unit:string|null;application_method:string|null;phi_days:number|null};
type Ingredient={product_id:string;ingredient:string;concentration:number|null;concentration_unit:string|null};
type Approver={id:string;full_name:string|null};
type Source={source_name:string;source_url:string;status:"pending"|"ready"|"stale"|"error";last_imported_at:string|null;product_count:number;use_count:number;notes:string|null};
type CatalogResponse={catalog:CatalogItem[];products:Product[];uses:Use[];ingredients?:Ingredient[];approvers?:Approver[];source?:Source|null;error?:string};
const methodTypes=new Set(["soil_work","sowing","harvest","irrigation","mowing","other"]);

export function OperationForm({fields,machines=[],defaultFieldId=""}:{fields:FieldOption[];machines?:MachineOption[];defaultFieldId?:string}){
 const initial=fields.find(f=>f.id===defaultFieldId);const[busy,setBusy]=useState(false),[loadingCatalog,setLoadingCatalog]=useState(false),[error,setError]=useState("");
 const[type,setType]=useState("spraying"),[fieldId,setFieldId]=useState(defaultFieldId),[product,setProduct]=useState(""),[customProduct,setCustomProduct]=useState(""),[productId,setProductId]=useState(""),[useId,setUseId]=useState(""),[catalogCrop,setCatalogCrop]=useState(""),[dose,setDose]=useState(""),[doseMode,setDoseMode]=useState<"official_max"|"custom">("custom"),[machineId,setMachineId]=useState(""),[customMachine,setCustomMachine]=useState("");
 const[catalog,setCatalog]=useState<CatalogItem[]>([]),[products,setProducts]=useState<Product[]>([]),[uses,setUses]=useState<Use[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[approvers,setApprovers]=useState<Approver[]>([]),[source,setSource]=useState<Source|null>(null);
 const selectedField=fields.find(f=>f.id===fieldId)||initial,country:CountryCode=selectedField?.countryCode||"HU",spraying=type==="spraying"||type==="plant_protection",fert=type==="fertilizing",inputLike=fert||spraying,hasMethod=methodTypes.has(type);
 useEffect(()=>{let active=true;setLoadingCatalog(true);setError("");setCatalog([]);setProducts([]);setUses([]);setIngredients([]);setApprovers([]);setSource(null);setProduct("");setCustomProduct("");setProductId("");setUseId("");setCatalogCrop("");setDose("");setDoseMode("custom");fetch(`/api/operation-catalog?country=${country}&type=${encodeURIComponent(type)}`,{cache:"no-store"}).then(async r=>{const body=await r.json() as CatalogResponse;if(!r.ok)throw new Error(body.error||"A katalógus betöltése sikertelen.");return body}).then(body=>{if(!active)return;setCatalog(body.catalog||[]);setProducts(body.products||[]);setUses(body.uses||[]);setIngredients(body.ingredients||[]);setApprovers(body.approvers||[]);setSource(body.source||null)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"A katalógus betöltése sikertelen.")}).finally(()=>{if(active)setLoadingCatalog(false)});return()=>{active=false}},[country,type]);
 useEffect(()=>{setMachineId("");setCustomMachine("")},[fieldId]);
 const cropOptions=useMemo(()=>Array.from(new Set(uses.map(x=>x.crop).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"hu")),[uses]);
 const filteredProducts=useMemo(()=>!catalogCrop?products:products.filter(p=>uses.some(u=>u.product_id===p.id&&u.crop===catalogCrop)),[products,uses,catalogCrop]);
 const productUses=useMemo(()=>uses.filter(x=>x.product_id===productId&&(!catalogCrop||x.crop===catalogCrop)),[uses,productId,catalogCrop]),selectedUse=useMemo(()=>productUses.find(x=>x.id===useId),[productUses,useId]),selectedProduct=useMemo(()=>products.find(x=>x.id===productId),[products,productId]);
 const activeIngredient=useMemo(()=>ingredients.filter(x=>x.product_id===productId).map(x=>`${x.ingredient}${x.concentration==null?"":` ${x.concentration}${x.concentration_unit?` ${x.concentration_unit}`:""}`}`).join(", "),[ingredients,productId]);
 const approvalNeeded=!!selectedProduct&&(selectedProduct.approval_required||selectedProduct.professional_use_only||selectedProduct.prescription_required||(country==="HU"&&["I","II","I.","II."].includes((selectedProduct.regulatory_category||"").toUpperCase())));
 const fertilizerOptions=catalog.length?catalog.map(x=>x.name):fertilizerCatalog.map(x=>x.name),methodOptions=catalog.length?catalog.map(x=>x.name):(type==="soil_work"?soilWork:[]),availableMachines=machines.filter(m=>!selectedField||m.farmId===selectedField.farmId),selectedMachine=machines.find(m=>m.id===machineId),effectiveProduct=product==="Egyéb"?customProduct:product;
 const nutrientSummary=useMemo(()=>{if(!fert||!effectiveProduct)return"";const d=Number(dose.replace(",","."));if(!Number.isFinite(d)||d<=0)return"";const item=catalog.find(x=>x.name===effectiveProduct)||fertilizerCatalog.find(x=>x.name===effectiveProduct);const meta=item?.metadata||{};return Object.entries(meta).filter(([,v])=>typeof v==="number").map(([k,v])=>`${k}: ${Math.round(d*(v as number))/100} kg/ha`).join(" · ")},[fert,effectiveProduct,dose,catalog]);
 function chooseUse(next:string){setUseId(next);const u=productUses.find(x=>x.id===next);if(u?.dose_max!=null){setDoseMode("official_max");setDose(String(u.dose_max).replace(".",","))}else{setDoseMode("custom");setDose("")}}
 function chooseDoseMode(mode:"official_max"|"custom"){setDoseMode(mode);if(mode==="official_max"&&selectedUse?.dose_max!=null)setDose(String(selectedUse.dose_max).replace(".",","));else setDose("")}
 async function submit(formData:FormData){setBusy(true);setError("");try{await createFieldOperation(formData);window.location.reload()}catch(e){setError(e instanceof Error?e.message:"A művelet mentése sikertelen.");setBusy(false)}}
 return <form action={submit} className="admin-form operation-form">
  <label>Földtábla<select name="field_id" value={fieldId} onChange={e=>setFieldId(e.target.value)} required><option value="">Válassz földtáblát</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name} – {f.farmName}{f.areaHa?` (${f.areaHa} ha)`:""}</option>)}</select></label>
  <label>Dátum<input type="date" name="operation_date" defaultValue={new Date().toISOString().slice(0,10)} required/></label>
  <label>Engedélyezési ország<div style={{minHeight:46,display:"flex",alignItems:"center",padding:"0 12px",border:"1px solid #dce5dc",borderRadius:10,background:"#f7faf7",fontWeight:700}}>{country==="HU"?"🇭🇺 Magyarország":"🇸🇰 Szlovákia"}</div></label>
  <label>Művelet<select name="operation_type" value={type} onChange={e=>setType(e.target.value)}>{operationTypes.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>
  {hasMethod&&<label>Munkafolyamat<select name="subtype" defaultValue="" key={type}><option value="">Válassz munkafolyamatot</option>{methodOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb / saját művelet</option></select></label>}
  {fert?<><label>Műtrágya / anyag<select value={product} onChange={e=>{setProduct(e.target.value);setCustomProduct("")}}><option value="">Válassz műtrágyát</option>{fertilizerOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb / saját termék</option></select><input type="hidden" name="product" value={effectiveProduct}/></label>{product==="Egyéb"&&<label>Saját termék megnevezése<input value={customProduct} onChange={e=>setCustomProduct(e.target.value)} required/></label>}</>:spraying?<>
   {products.length>0&&<label>Kultúra<select value={catalogCrop} onChange={e=>{setCatalogCrop(e.target.value);setProductId("");setUseId("");setProduct("");setDose("")}} required><option value="">Válassz kultúrát</option>{cropOptions.map(c=><option key={c}>{c}</option>)}</select></label>}
   <label>Készítmény / szer<select name="product_id" value={productId} onChange={e=>{const id=e.target.value;setProductId(id);setUseId("");setDose("");setProduct(products.find(x=>x.id===id)?.name||"")}} disabled={loadingCatalog||products.length>0&&!catalogCrop} required={products.length>0}><option value="">{loadingCatalog?"Katalógus betöltése…":products.length?(catalogCrop?"Válassz engedélyezett készítményt":"Előbb válassz kultúrát"):"Nincs betöltött hivatalos készítmény"}</option>{filteredProducts.map(x=><option key={x.id} value={x.id}>{x.name}{x.regulatory_category?` · ${x.regulatory_category}. kategória`:""}{x.authorization_number?` · ${x.authorization_number}`:""}</option>)}</select>{products.length?<input type="hidden" name="product" value={product}/>:null}</label>
   {!products.length&&!loadingCatalog&&<label>Készítmény kézi megnevezése<input name="product" value={product} onChange={e=>setProduct(e.target.value)} placeholder={`${country} készítmény neve`}/></label>}
   {productId&&<label>Engedélyezett felhasználás / cél<select name="use_id" value={useId} onChange={e=>chooseUse(e.target.value)} required><option value="">Válassz engedélyezett felhasználást</option>{productUses.map(u=><option key={u.id} value={u.id}>{u.target||u.application_method||u.crop}{u.dose_min!=null||u.dose_max!=null?` (${u.dose_min??"?"}–${u.dose_max??"?"} ${u.dose_unit||""})`:""}</option>)}</select></label>}
   {!products.length&&!loadingCatalog&&<><label>Kultúra<input name="crop"/></label><label>Célkárosító / cél<input name="target"/></label></>}
   <label>Hatóanyag(ok){productId?<input name="active_ingredient" value={activeIngredient} readOnly/>:<input name="active_ingredient"/>}</label>
  </>:type==="sowing"?<label>Vetőmag / fajta<input name="product" value={product} onChange={e=>setProduct(e.target.value)}/></label>:null}
  {inputLike&&<>{spraying&&selectedUse?.dose_max!=null?<><label>Dózis választása<select name="dose_mode" value={doseMode} onChange={e=>chooseDoseMode(e.target.value as "official_max"|"custom")}><option value="official_max">Hivatalos maximális dózis: {selectedUse.dose_max} {selectedUse.dose_unit||""}</option><option value="custom">Egyéni dózis</option></select><small>Az egyéni dózis nem lehet nagyobb a hivatalos maximumnál.</small></label>{doseMode==="custom"&&<label>Egyéni dózis<input name="dose" value={dose} onChange={e=>setDose(e.target.value)} inputMode="decimal" min={selectedUse.dose_min??undefined} max={selectedUse.dose_max} required/><small>Engedélyezett tartomány: {selectedUse.dose_min??0}–{selectedUse.dose_max} {selectedUse.dose_unit||""}</small></label>}{doseMode==="official_max"&&<input type="hidden" name="dose" value={selectedUse.dose_max}/>}</>:<label>Dózis<input name="dose" value={dose} onChange={e=>setDose(e.target.value)} inputMode="decimal"/></label>}<label>Dózis egysége{selectedUse?.dose_unit?<><select value={selectedUse.dose_unit} disabled><option>{selectedUse.dose_unit}</option></select><input type="hidden" name="dose_unit" value={selectedUse.dose_unit}/></>:<select name="dose_unit" defaultValue={spraying?"l/ha":"kg/ha"}><option>l/ha</option><option>kg/ha</option><option>g/ha</option><option>ml/ha</option><option>kg</option><option>l</option></select>}</label></>}
  {approvalNeeded&&<div className="operation-wide" style={{padding:14,border:"1px solid #e1b95d",borderRadius:12,background:"#fffaf0"}}><b>⚠ Jogosultsághoz kötött készítmény</b><p style={{margin:"6px 0 10px"}}>A művelet csak kijelölt jogosult személy tényleges jóváhagyása után tekinthető jóváhagyottnak.</p><label>Engedélyező / jóváhagyó személy<select name="requested_approver_id" required><option value="">Válassz jogosult szaktanácsadót</option>{approvers.map(a=><option key={a.id} value={a.id}>{a.full_name||"Szaktanácsadó"}</option>)}</select></label></div>}
  <label>Kezelt terület (ha)<input name="treated_area" inputMode="decimal"/></label><label>Összes mennyiség<input name="quantity" inputMode="decimal"/></label><label>Mennyiség egysége<select name="quantity_unit" defaultValue="l"><option>l</option><option>kg</option><option>g</option><option>db</option><option>m³</option><option>t</option></select></label>
  <label>Gép / eszköz<select name="machine_id" value={machineId} onChange={e=>{setMachineId(e.target.value);setCustomMachine("")}}><option value="">Nincs kiválasztott gép</option>{availableMachines.map(m=><option key={m.id} value={m.id}>{m.name}{m.detail?` – ${m.detail}`:""}</option>)}<option value="manual">Egyéb / külső gép</option></select><input type="hidden" name="machine" value={machineId==="manual"?customMachine:selectedMachine?.name||""}/></label>{machineId==="manual"&&<label>Gép kézi megnevezése<input value={customMachine} onChange={e=>setCustomMachine(e.target.value)} required/></label>}
  <label>Végrehajtó<input name="operator"/></label><label className="operation-wide">Időjárás / körülmények<input name="weather"/></label><label className="operation-wide">Megjegyzés<textarea name="notes" rows={3}/></label>
  {spraying&&<div className="operation-wide" style={{padding:12,border:"1px solid #dce5dc",borderRadius:12,fontSize:13}}><b>{country==="HU"?"🇭🇺 Magyar":"🇸🇰 Szlovák"} növényvédelmi kör</b><br/>{selectedProduct?<>Kiválasztva: <b>{selectedProduct.name}</b>{selectedProduct.regulatory_category?` · ${selectedProduct.regulatory_category}. forgalmi kategória`:""}{selectedProduct.authorization_number?` · engedély: ${selectedProduct.authorization_number}`:""}. </>:null}{selectedUse?<>Kultúra: <b>{selectedUse.crop}</b>{selectedUse.target?` · cél: ${selectedUse.target}`:""}{selectedUse.phi_days!=null?` · ÉVI: ${selectedUse.phi_days} nap`:""}.</>:source?.status==="ready"?"Az engedélyezett felhasználás kiválasztása kötelező.":"A hivatalos katalógus importja még nem teljes."}</div>}
  {fert&&nutrientSummary&&<div className="operation-wide"><small>Hatóanyag kijuttatás: {nutrientSummary}</small></div>}{error&&<div className="error-box operation-wide">{error}</div>}<button className="btn btn-primary" type="submit" disabled={busy||loadingCatalog}>{busy?"Mentés…":loadingCatalog?"Katalógus betöltése…":"Művelet rögzítése"}</button>
 </form>;
}
