"use client";

import {useEffect,useMemo,useState} from "react";
import {createFieldOperation} from "@/app/operations/actions";
import {operationTypes} from "@/lib/operations";
import {fertilizerCatalog,soilWork,type CountryCode} from "@/lib/operationCatalog";

type FieldOption={id:string;farmId:string;name:string;farmName:string;areaHa:number|null;countryCode?:CountryCode};
type MachineOption={id:string;farmId:string;name:string;detail?:string};
type CatalogItem={id:string;name:string;category:string;metadata?:Record<string,unknown>};
type Product={id:string;name:string;authorization_number:string|null;function_type:string|null};
type Use={id:string;product_id:string;crop:string;target:string|null;dose_min:number|null;dose_max:number|null;dose_unit:string|null;application_method:string|null;phi_days:number|null};
type Ingredient={product_id:string;ingredient:string;concentration:number|null;concentration_unit:string|null};
type Source={source_name:string;source_url:string;status:"pending"|"ready"|"stale"|"error";last_imported_at:string|null;product_count:number;use_count:number;notes:string|null};
type CatalogResponse={catalog:CatalogItem[];products:Product[];uses:Use[];ingredients?:Ingredient[];source?:Source|null;error?:string};

export function OperationForm({fields,machines=[],defaultFieldId=""}:{fields:FieldOption[];machines?:MachineOption[];defaultFieldId?:string}){
 const initial=fields.find(f=>f.id===defaultFieldId);const[busy,setBusy]=useState(false),[loadingCatalog,setLoadingCatalog]=useState(false),[error,setError]=useState("");
 const[type,setType]=useState("spraying"),[fieldId,setFieldId]=useState(defaultFieldId),[product,setProduct]=useState(""),[customProduct,setCustomProduct]=useState(""),[productId,setProductId]=useState(""),[useId,setUseId]=useState(""),[dose,setDose]=useState(""),[machineId,setMachineId]=useState(""),[customMachine,setCustomMachine]=useState("");
 const[catalog,setCatalog]=useState<CatalogItem[]>([]),[products,setProducts]=useState<Product[]>([]),[uses,setUses]=useState<Use[]>([]),[ingredients,setIngredients]=useState<Ingredient[]>([]),[source,setSource]=useState<Source|null>(null);
 const selectedField=fields.find(f=>f.id===fieldId)||initial,country:CountryCode=selectedField?.countryCode||"HU",spraying=type==="spraying"||type==="plant_protection",fert=type==="fertilizing",inputLike=fert||spraying;
 useEffect(()=>{let active=true;setLoadingCatalog(true);setError("");setCatalog([]);setProducts([]);setUses([]);setIngredients([]);setSource(null);setProduct("");setCustomProduct("");setProductId("");setUseId("");fetch(`/api/operation-catalog?country=${country}&type=${encodeURIComponent(type)}`,{cache:"no-store"}).then(async r=>{const body=await r.json() as CatalogResponse;if(!r.ok)throw new Error(body.error||"A katalógus betöltése sikertelen.");return body}).then(body=>{if(!active)return;setCatalog(body.catalog||[]);setProducts(body.products||[]);setUses(body.uses||[]);setIngredients(body.ingredients||[]);setSource(body.source||null)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"A katalógus betöltése sikertelen.")}).finally(()=>{if(active)setLoadingCatalog(false)});return()=>{active=false}},[country,type]);
 useEffect(()=>{setMachineId("");setCustomMachine("")},[fieldId]);
 const productUses=useMemo(()=>uses.filter(x=>x.product_id===productId),[uses,productId]),selectedUse=useMemo(()=>productUses.find(x=>x.id===useId),[productUses,useId]),selectedProduct=useMemo(()=>products.find(x=>x.id===productId),[products,productId]);
 const activeIngredient=useMemo(()=>ingredients.filter(x=>x.product_id===productId).map(x=>`${x.ingredient}${x.concentration==null?"":` ${x.concentration}${x.concentration_unit?` ${x.concentration_unit}`:""}`}`).join(", "),[ingredients,productId]);
 const fertilizerOptions=catalog.length?catalog.map(x=>x.name):fertilizerCatalog.map(x=>x.name),soilOptions=catalog.length?catalog.map(x=>x.name):soilWork,availableMachines=machines.filter(m=>!selectedField||m.farmId===selectedField.farmId),selectedMachine=machines.find(m=>m.id===machineId);
 const effectiveProduct=product==="Egyéb"?customProduct:product;
 const nutrientSummary=useMemo(()=>{if(!fert||!effectiveProduct)return"";const d=Number(dose.replace(",","."));if(!Number.isFinite(d)||d<=0)return"";const item=catalog.find(x=>x.name===effectiveProduct)||fertilizerCatalog.find(x=>x.name===effectiveProduct);const meta=item?.metadata||{};return Object.entries(meta).filter(([,v])=>typeof v==="number").map(([k,v])=>`${k}: ${Math.round(d*(v as number))/100} kg/ha`).join(" · ")},[fert,effectiveProduct,dose,catalog]);
 async function submit(formData:FormData){setBusy(true);setError("");try{await createFieldOperation(formData);window.location.reload()}catch(e){setError(e instanceof Error?e.message:"A művelet mentése sikertelen.");setBusy(false)}}
 return <form action={submit} className="admin-form operation-form">
  <label>Földtábla<select name="field_id" value={fieldId} onChange={e=>setFieldId(e.target.value)} required><option value="">Válassz földtáblát</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name} – {f.farmName}{f.areaHa?` (${f.areaHa} ha)`:""}</option>)}</select></label>
  <label>Dátum<input type="date" name="operation_date" defaultValue={new Date().toISOString().slice(0,10)} required/></label>
  <label>Engedélyezési ország<div style={{minHeight:46,display:"flex",alignItems:"center",padding:"0 12px",border:"1px solid #dce5dc",borderRadius:10,background:"#f7faf7",fontWeight:700}}>{country==="HU"?"🇭🇺 Magyarország":"🇸🇰 Szlovákia"}</div><small>A gazdaság alapján automatikus; mentéskor a szerver újra ellenőrzi.</small></label>
  <label>Művelet<select name="operation_type" value={type} onChange={e=>setType(e.target.value)}>{operationTypes.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>
  {type==="soil_work"&&<label>Munkafolyamat<select name="subtype" defaultValue=""><option value="">Válassz talajmunkát</option>{soilOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb / saját művelet</option></select></label>}
  {fert?<><label>Műtrágya / anyag<select value={product} onChange={e=>{setProduct(e.target.value);setCustomProduct("")}}><option value="">Válassz műtrágyát</option>{fertilizerOptions.map(x=><option key={x}>{x}</option>)}<option value="Egyéb">Egyéb / saját termék</option></select><input type="hidden" name="product" value={effectiveProduct}/></label>{product==="Egyéb"&&<label>Saját termék megnevezése<input value={customProduct} onChange={e=>setCustomProduct(e.target.value)} placeholder="műtrágya / tápanyag neve" required/></label>}</>:spraying?<>
   <label>Készítmény / szer<select name="product_id" value={productId} onChange={e=>{const id=e.target.value;setProductId(id);setUseId("");setProduct(products.find(x=>x.id===id)?.name||"")}} disabled={loadingCatalog}><option value="">{loadingCatalog?"Katalógus betöltése…":products.length?"Válassz engedélyezett készítményt":"Nincs betöltött hivatalos készítmény"}</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}{x.authorization_number?` – ${x.authorization_number}`:""}</option>)}</select>{products.length?<input type="hidden" name="product" value={product}/>:null}{!products.length&&!loadingCatalog&&<small>{source?.source_name||"Hivatalos katalógus"}: az import még nincs kész, ezért kézi rögzítés engedélyezett.</small>}</label>
   {!products.length&&!loadingCatalog&&<label>Készítmény kézi megnevezése<input name="product" value={product} onChange={e=>setProduct(e.target.value)} placeholder={`${country} készítmény neve`}/></label>}
   {productId&&<label>Kultúra / engedélyezett felhasználás<select name="use_id" value={useId} onChange={e=>{const next=e.target.value;setUseId(next);const u=productUses.find(x=>x.id===next);if(u?.dose_min!=null&&u.dose_max!=null&&u.dose_min===u.dose_max)setDose(String(u.dose_min).replace(".",","))}}><option value="">Válassz kultúrát / felhasználást</option>{productUses.map(u=><option key={u.id} value={u.id}>{u.crop}{u.target?` – ${u.target}`:""}{u.dose_min!=null||u.dose_max!=null?` (${u.dose_min??"?"}–${u.dose_max??"?"} ${u.dose_unit||""})`:""}</option>)}</select></label>}
   {!productId&&<label>Kultúra<input name="crop" placeholder="pl. őszi búza"/></label>}{!productId&&<label>Célkárosító / cél<input name="target" placeholder="pl. lisztharmat, gyomfaj"/></label>}
   <label>Hatóanyag(ok){productId?<input name="active_ingredient" value={activeIngredient} readOnly placeholder="hatóanyag és koncentráció"/>:<input name="active_ingredient" placeholder="hatóanyag és koncentráció"/>}</label>
  </>:type!=="soil_work"&&<label>{type==="sowing"?"Vetőmag / fajta":"Anyag / megnevezés"}<input name="product" value={product} onChange={e=>setProduct(e.target.value)} placeholder="opcionális"/></label>}
  {inputLike&&<><label>Dózis<input name="dose" value={dose} onChange={e=>setDose(e.target.value)} inputMode="decimal" placeholder="pl. 2,5"/>{fert&&nutrientSummary&&<small>Hatóanyag kijuttatás: {nutrientSummary}</small>}{spraying&&selectedUse&&(selectedUse.dose_min!=null||selectedUse.dose_max!=null)&&<small>Engedélyezett tartomány: {selectedUse.dose_min??"?"}–{selectedUse.dose_max??"?"} {selectedUse.dose_unit||""}</small>}</label><label>Dózis egysége{selectedUse?.dose_unit?<><select value={selectedUse.dose_unit} disabled><option>{selectedUse.dose_unit}</option></select><input type="hidden" name="dose_unit" value={selectedUse.dose_unit}/></>:<select name="dose_unit" defaultValue={spraying?"l/ha":"kg/ha"}><option>l/ha</option><option>kg/ha</option><option>g/ha</option><option>ml/ha</option><option>kg</option><option>l</option></select>}</label></>}
  <label>Kezelt terület (ha)<input name="treated_area" inputMode="decimal" placeholder="pl. 4,2"/></label><label>Összes mennyiség<input name="quantity" inputMode="decimal" placeholder="opcionális"/></label><label>Mennyiség egysége<select name="quantity_unit" defaultValue="l"><option>l</option><option>kg</option><option>g</option><option>db</option><option>m³</option><option>t</option></select></label>
  <label>Gép / eszköz<select name="machine_id" value={machineId} onChange={e=>{setMachineId(e.target.value);setCustomMachine("")}}><option value="">Nincs kiválasztott gép</option>{availableMachines.map(m=><option key={m.id} value={m.id}>{m.name}{m.detail?` – ${m.detail}`:""}</option>)}<option value="manual">Egyéb / külső gép</option></select><input type="hidden" name="machine" value={machineId==="manual"?customMachine:selectedMachine?.name||""}/></label>{machineId==="manual"&&<label>Gép kézi megnevezése<input value={customMachine} onChange={e=>setCustomMachine(e.target.value)} placeholder="gép / eszköz neve" required/></label>}
  <label>Végrehajtó<input name="operator" placeholder="név vagy vállalkozó"/></label><label className="operation-wide">Időjárás / körülmények<input name="weather" placeholder="pl. 19 °C, gyenge szél, száraz levélzet"/></label><label className="operation-wide">Megjegyzés<textarea name="notes" rows={3} placeholder="Minden további szakmai megjegyzés..."/></label>
  {spraying&&<div className="operation-wide" style={{padding:12,border:"1px solid #dce5dc",borderRadius:12,fontSize:13}}><b>{country==="HU"?"🇭🇺 Magyar":"🇸🇰 Szlovák"} növényvédelmi kör</b><br/>{selectedProduct?<>Kiválasztva: <b>{selectedProduct.name}</b>{selectedProduct.authorization_number?` · engedély: ${selectedProduct.authorization_number}`:""}. </>:null}{selectedUse?<>Kultúra: <b>{selectedUse.crop}</b>{selectedUse.target?` · cél: ${selectedUse.target}`:""}{selectedUse.phi_days!=null?` · ÉVI: ${selectedUse.phi_days} nap`:""}.</>:source?.status==="ready"?"Válassz engedélyezett felhasználást; a dózist mentéskor is ellenőrizzük.":"A hivatalos katalógusforrás regisztrálva van, de az adatimport még nem áll kész állapotban."}</div>}
  {error&&<div className="error-box operation-wide">{error}</div>}<button className="btn btn-primary" type="submit" disabled={busy||loadingCatalog}>{busy?"Mentés…":loadingCatalog?"Katalógus betöltése…":"Művelet rögzítése"}</button>
 </form>;
}
