"use client";

import {FormEvent,useState} from "react";

export function SensitiveExportButton(){
 const[open,setOpen]=useState(false);const[code,setCode]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/security/step-up",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"export",code})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"A megerősítés sikertelen.");setBusy(false);return}setOpen(false);setCode("");setBusy(false);window.location.assign("/admin/backup/export")}
 return <><button type="button" className="btn btn-primary" onClick={()=>{setOpen(true);setError("")}}>Biztonsági mentés letöltése</button>{open&&<div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:200,background:"rgba(4,22,14,.55)",display:"grid",placeItems:"center",padding:18}} onMouseDown={()=>!busy&&setOpen(false)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} style={{width:"min(440px,100%)",background:"white",borderRadius:18,padding:24,boxShadow:"0 24px 80px rgba(0,0,0,.28)"}}><span className="eyebrow">KIEMELTEN VÉDETT MŰVELET</span><h2>Export újbóli hitelesítése</h2><p style={{color:"#6f7c74",lineHeight:1.55}}>A teljes adatmentés akkor is új authenticator-kódot kér, ha már kétfaktorosan jelentkeztél be. A sikeres megerősítés 5 percig érvényes erre az exportműveletre.</p><label style={{display:"block",fontWeight:800}}>6 jegyű authenticator-kód<input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} style={{width:"100%",marginTop:7,padding:13,border:"1px solid #dfe5df",borderRadius:10,font:"inherit"}} required/></label>{error&&<div className="error-box">{error}</div>}<div style={{display:"flex",gap:10,marginTop:16,flexWrap:"wrap"}}><button className="btn btn-primary" disabled={busy||code.length!==6}>{busy?"Ellenőrzés…":"Megerősítés és letöltés"}</button><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>setOpen(false)}>Mégse</button></div></form></div>}</>
}
