"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {completeTask} from "@/app/fields/[id]/actions";

export function TaskProofCompleteForm({taskId}:{taskId:string}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(""),[position,setPosition]=useState<{lat:number;lng:number;accuracy:number}|null>(null),[photo,setPhoto]=useState<File|null>(null);
 const supabase=createClient();
 function locate(){setError("");if(!navigator.geolocation){setError("A készülék nem támogatja a helymeghatározást.");return}setBusy(true);navigator.geolocation.getCurrentPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy});setBusy(false)},e=>{setError(e.message||"A GPS-pozíció lekérése sikertelen.");setBusy(false)},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 async function submit(){setBusy(true);setError("");try{if(!position)throw new Error("Előbb kérd le a GPS-pozíciódat.");if(position.accuracy>200)throw new Error(`A GPS pontossága jelenleg kb. ${Math.round(position.accuracy)} m. Kérj új pozíciót szabad ég alatt.`);if(!photo)throw new Error("Készíts vagy válassz helyszíni fotót.");if(!photo.type.startsWith("image/"))throw new Error("A bizonyíték csak fénykép lehet.");if(photo.size>15*1024*1024)throw new Error("A fotó maximum 15 MB lehet.");const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("A munkamenet lejárt.");const safe=photo.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${user.id}/task-proofs/${taskId}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("farmer-report-media").upload(path,photo,{contentType:photo.type});if(uploadError)throw new Error(uploadError.message);const fd=new FormData();fd.set("task_id",taskId);fd.set("lat",String(position.lat));fd.set("lng",String(position.lng));fd.set("accuracy",String(position.accuracy));fd.set("photo_path",path);fd.set("photo_name",photo.name);await completeTask(fd);window.location.reload()}catch(e){setError(e instanceof Error?e.message:"A munka lezárása sikertelen.");setBusy(false)}}
 return <div style={{display:"grid",gap:8,minWidth:220}}><button type="button" className="ghost-btn" onClick={locate} disabled={busy}>{position?`✓ GPS · ±${Math.round(position.accuracy)} m`:"1. GPS pozíció rögzítése"}</button><label className="ghost-btn" style={{cursor:"pointer",textAlign:"center"}}>2. Helyszíni fotó<input type="file" accept="image/*" capture="environment" style={{display:"none"}} onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label>{photo&&<small style={{color:"#39752f",fontWeight:700}}>✓ {photo.name}</small>}<button type="button" className="btn btn-primary" onClick={submit} disabled={busy||!position||!photo}>{busy?"Ellenőrzés…":"3. Munka lezárása"}</button>{error&&<small style={{color:"#b3342b",maxWidth:280}}>{error}</small>}</div>
}
