"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

type Row=Record<string,string>;
export type SyncResult={ok:boolean;error?:string;rows?:number;inserted_products?:number;inserted_uses?:number;inserted_ingredients?:number;source_url?:string};
const aliases:Record<string,string>={
 "növényvédő szer neve":"name","novenyvedo szer neve":"name","novenyvedo_szer_neve":"name","készítmény":"name","keszitmeny":"name","obchodný názov prípravku":"name","obchodny nazov pripravku":"name","obchodny_nazov_pripravku":"name",
 "engedély száma":"authorization_number","engedely szama":"authorization_number","engedelyszam":"authorization_number","číslo autorizácie":"authorization_number","cislo autorizacie":"authorization_number","cislo_autorizacie":"authorization_number",
 "forgalmazási kategória":"regulatory_category","forgalmazasi kategoria":"regulatory_category","forg kategória":"regulatory_category","forg kategoria":"regulatory_category","kategória":"regulatory_category","kategoria":"regulatory_category",
 "rendeltetés":"function_type","rendeltetes":"function_type","typ funkcie prípravku":"function_type","typ funkcie pripravku":"function_type",
 "kultúra":"crop","kultura":"crop","plodina":"crop","plodina alebo oblasť použitia":"crop","plodina alebo oblast pouzitia":"crop",
 "károsító":"target","karosito":"target","cél":"target","cel":"target","škodlivý organizmus alebo iný účel použitia":"target","skodlivy organizmus alebo iny ucel pouzitia":"target",
 "dózis min":"dose_min","dozis min":"dose_min","min dózis":"dose_min","min dozis":"dose_min","dose_min":"dose_min",
 "dózis max":"dose_max","dozis max":"dose_max","max dózis":"dose_max","max dozis":"dose_max","dose_max":"dose_max",
 "dózis egység":"dose_unit","dozis egyseg":"dose_unit","jednotka dávky":"dose_unit","jednotka davky":"dose_unit",
 "kijuttatás módja":"application_method","kijuttatas modja":"application_method","spôsob aplikácie":"application_method","sposob aplikacie":"application_method",
 "évi":"phi_days","evi":"phi_days","várakozási idő":"phi_days","varakozasi ido":"phi_days","phi_days":"phi_days",
 "hatóanyag":"ingredient","hatoanyag":"ingredient","hatóanyag összetétel":"ingredient","hatoanyag osszetetel":"ingredient","názov účinnej látky":"ingredient","nazov ucinnej_latky":"ingredient"
};
function norm(s:string){return s.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[._-]+/g," ").replace(/\s+/g," ")}
function parseCsv(input:string){const text=input.replace(/^\uFEFF/,"").trim();if(!text)return[] as Row[];const first=text.split("\n")[0];const counts={";":(first.match(/;/g)?.length||0),",":(first.match(/,/g)?.length||0),"\t":(first.match(/\t/g)?.length||0)};const sep=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||";";const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&q&&n==='"'){cell+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===sep&&!q){row.push(cell.trim());cell="";continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell="";continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];const header=rows[0].map(h=>aliases[norm(h)]||norm(h).replace(/\s+/g,"_"));return rows.slice(1).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]||""]))).filter(r=>r.name||r.product_name||r.keszitmeny||r.novenyvedo_szer_neve)}

async function advisorContext(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role!=="advisor")throw new Error("Csak szaktanácsadó/admin indíthat katalógusimportot.");return{supabase,user}}
async function runImport(country:"HU"|"SK",sourceName:string,sourceUrl:string,rows:Row[],notes:string){if(!rows.length)throw new Error("Nem találtam importálható sort.");const{supabase}=await advisorContext();const{data,error}=await supabase.rpc("import_plant_protection_catalog",{p_country_code:country,p_source_name:sourceName,p_source_url:sourceUrl,p_rows:rows,p_notes:notes});if(error)throw new Error(error.message);revalidatePath("/admin/plant-protection-import");revalidatePath("/operations");return data}

export async function importPlantProtectionCsv(formData:FormData){const country=String(formData.get("country_code")||"HU")==="SK"?"SK":"HU",sourceName=String(formData.get("source_name")||"").trim()||`${country} hivatalos növényvédőszer-katalógus`,sourceUrl=String(formData.get("source_url")||"").trim(),notes=String(formData.get("notes")||"").trim(),csv=String(formData.get("csv")||"");const rows=parseCsv(csv);if(!rows.length)throw new Error("Nem találtam importálható sort. Ellenőrizd, hogy az első sor fejléc legyen, utána jöjjenek az adatsorok.");return runImport(country,sourceName,sourceUrl,rows,notes)}

async function fetchOfficialUksupCsv(){const urls=["https://www.uksup.sk/storage/app/uploads/public/604/080/af4/604080af43e18263270214.csv","https://beta.uksup.sk/storage/app/uploads/public/604/080/af4/604080af43e18263270214.csv"];const problems:string[]=[];for(const url of urls){for(let attempt=1;attempt<=2;attempt++){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);const r=await fetch(url,{cache:"no-store",signal:controller.signal,headers:{"user-agent":"Agrar-Mentor/1.0 official-catalog-sync","accept":"text/csv,text/plain,*/*"}});clearTimeout(timer);if(!r.ok){problems.push(`${new URL(url).host}: HTTP ${r.status}`);continue}const text=await r.text();if(text.length<100){problems.push(`${new URL(url).host}: túl rövid válasz`);continue}return{text,url}}catch(e){problems.push(`${new URL(url).host}: ${e instanceof Error?e.name:"hálózati hiba"}`)}}}throw new Error(`Az ÚKSÚP hivatalos adatforrása jelenleg nem érhető el megbízhatóan a szerverről. ${problems.slice(-4).join("; ")}`)}

export async function syncUksupOfficialCatalog():Promise<SyncResult>{try{await advisorContext();const{text,url}=await fetchOfficialUksupCsv();const rows=parseCsv(text);if(!rows.length)return{ok:false,error:"Az ÚKSÚP fájl letöltődött, de a jelenlegi fejlécből nem sikerült készítményadatokat felismerni. A forrásformátum megváltozhatott."};const data:any=await runImport("SK","ÚKSÚP ISPOR – Prípravky na ochranu rastlín.csv",url,rows,`Automatikus hivatalos szinkron; feldolgozott sorok: ${rows.length}.`);return{ok:true,source_url:url,rows:Number(data?.rows||rows.length),inserted_products:Number(data?.inserted_products||0),inserted_uses:Number(data?.inserted_uses||0),inserted_ingredients:Number(data?.inserted_ingredients||0)}}catch(e){return{ok:false,error:e instanceof Error?e.message:"Az ÚKSÚP szinkron ismeretlen hiba miatt megszakadt."}}}
