"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

type Row=Record<string,string>;
const aliases:Record<string,string>={
 "növényvédő szer neve":"name","novenyvedo szer neve":"name","novenyvedo_szer_neve":"name","készítmény":"name","keszitmeny":"name","obchodný názov prípravku":"name","obchodny nazov pripravku":"name","obchodny_nazov_pripravku":"name","názov prípravku":"name","nazov pripravku":"name",
 "engedély száma":"authorization_number","engedely szama":"authorization_number","engedelyszam":"authorization_number","číslo autorizácie":"authorization_number","cislo autorizacie":"authorization_number","cislo_autorizacie":"authorization_number","registračné číslo":"authorization_number","registracne cislo":"authorization_number",
 "forgalmazási kategória":"regulatory_category","forgalmazasi kategoria":"regulatory_category","forg kategória":"regulatory_category","forg kategoria":"regulatory_category","kategória":"regulatory_category","kategoria":"regulatory_category",
 "rendeltetés":"function_type","rendeltetes":"function_type","typ funkcie prípravku":"function_type","typ funkcie pripravku":"function_type","funkcia prípravku":"function_type","funkcia pripravku":"function_type",
 "kultúra":"crop","kultura":"crop","plodina":"crop","plodina alebo oblasť použitia":"crop","plodina alebo oblast pouzitia":"crop",
 "károsító":"target","karosito":"target","cél":"target","cel":"target","škodlivý organizmus alebo iný účel použitia":"target","skodlivy organizmus alebo iny ucel pouzitia":"target",
 "dózis min":"dose_min","dozis min":"dose_min","min dózis":"dose_min","min dozis":"dose_min","dose_min":"dose_min",
 "dózis max":"dose_max","dozis max":"dose_max","max dózis":"dose_max","max dozis":"dose_max","dose_max":"dose_max",
 "dózis egység":"dose_unit","dozis egyseg":"dose_unit","jednotka dávky":"dose_unit","jednotka davky":"dose_unit",
 "dávka":"dose_raw","davka":"dose_raw","dávka prípravku":"dose_raw","davka pripravku":"dose_raw","aplikačná dávka":"dose_raw","aplikacna davka":"dose_raw",
 "kijuttatás módja":"application_method","kijuttatas modja":"application_method","spôsob aplikácie":"application_method","sposob aplikacie":"application_method",
 "évi":"phi_days","evi":"phi_days","várakozási idő":"phi_days","varakozasi ido":"phi_days","phi_days":"phi_days","ochranná doba":"phi_days","ochranna doba":"phi_days","ochranná lehota":"phi_days","ochranna lehota":"phi_days",
 "hatóanyag":"ingredient","hatoanyag":"ingredient","hatóanyag összetétel":"ingredient","hatoanyag osszetetel":"ingredient","názov účinnej látky":"ingredient","nazov ucinnej latky":"ingredient","účinná látka":"ingredient","ucinna latka":"ingredient"
};
function norm(s:string){return s.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[._-]+/g," ").replace(/\s+/g," ")}
function parseDose(raw:string){const s=raw.replace(/,/g,".").replace(/\s+/g," ").trim();if(!s)return{dose_min:"",dose_max:"",dose_unit:""};const nums=[...s.matchAll(/\d+(?:\.\d+)?/g)].map(m=>Number(m[0])).filter(Number.isFinite);const unit=(s.match(/(?:kg|g|l|ml)\s*\/?\s*(?:ha|100\s*l|hl)?/i)?.[0]||"").replace(/\s+/g,"").toLowerCase();return{dose_min:nums.length>1?String(Math.min(...nums)):nums.length?String(nums[0]):"",dose_max:nums.length?String(Math.max(...nums)):"",dose_unit:unit}}
function normalizeRow(row:Row){if(row.dose_raw&&(!row.dose_min||!row.dose_max)){const d=parseDose(row.dose_raw);row={...row,dose_min:row.dose_min||d.dose_min,dose_max:row.dose_max||d.dose_max,dose_unit:row.dose_unit||d.dose_unit}}return row}
function parseCsv(input:string){const text=input.replace(/^\uFEFF/,"").trim();if(!text)return[] as Row[];const first=text.split("\n")[0];const counts={";":(first.match(/;/g)?.length||0),",":(first.match(/,/g)?.length||0),"\t":(first.match(/\t/g)?.length||0)};const sep=(Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||";");const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&q&&n==='"'){cell+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===sep&&!q){row.push(cell.trim());cell="";continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell="";continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];const header=rows[0].map(h=>aliases[norm(h)]||norm(h).replace(/\s+/g,"_"));return rows.slice(1).map(r=>normalizeRow(Object.fromEntries(header.map((h,i)=>[h,r[i]||""])))).filter(r=>r.name||r.product_name||r.keszitmeny||r.novenyvedo_szer_neve)}

async function advisorContext(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role!=="advisor")throw new Error("Csak szaktanácsadó/admin indíthat katalógusimportot.");return{supabase,user}}
async function runImport(country:"HU"|"SK",sourceName:string,sourceUrl:string,rows:Row[],notes:string){if(!rows.length)throw new Error("Nem találtam importálható sort.");const{supabase}=await advisorContext();const chunks:Array<Row[]>=[];for(let i=0;i<rows.length;i+=750)chunks.push(rows.slice(i,i+750));let totals={rows:0,inserted_products:0,inserted_uses:0,inserted_ingredients:0};for(const chunk of chunks){const{data,error}=await supabase.rpc("import_plant_protection_catalog",{p_country_code:country,p_source_name:sourceName,p_source_url:sourceUrl,p_rows:chunk,p_notes:notes});if(error)throw new Error(error.message);const r:any=data||{};totals={rows:totals.rows+Number(r.rows||chunk.length),inserted_products:totals.inserted_products+Number(r.inserted_products||0),inserted_uses:totals.inserted_uses+Number(r.inserted_uses||0),inserted_ingredients:totals.inserted_ingredients+Number(r.inserted_ingredients||0)}}revalidatePath("/admin/plant-protection-import");revalidatePath("/operations");return totals}

export async function importPlantProtectionCsv(formData:FormData){const country=String(formData.get("country_code")||"HU")==="SK"?"SK":"HU",sourceName=String(formData.get("source_name")||"").trim()||`${country} hivatalos növényvédőszer-katalógus`,sourceUrl=String(formData.get("source_url")||"").trim(),notes=String(formData.get("notes")||"").trim(),csv=String(formData.get("csv")||"");const rows=parseCsv(csv);if(!rows.length)throw new Error("Nem találtam importálható sort. Ellenőrizd, hogy az első sor fejléc legyen, utána jöjjenek az adatsorok.");return runImport(country,sourceName,sourceUrl,rows,notes)}

export async function importPlantProtectionFile(formData:FormData){const country=String(formData.get("country_code")||"HU")==="SK"?"SK":"HU",file=formData.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Válassz CSV/XLS/XLSX fájlt.");if(file.size>25*1024*1024)throw new Error("A fájl legfeljebb 25 MB lehet.");const sourceName=String(formData.get("source_name")||"").trim()||`${country} hivatalos növényvédőszer-katalógus`,sourceUrl=String(formData.get("source_url")||"").trim(),notes=String(formData.get("notes")||"").trim();let rows:Row[]=[];const lower=file.name.toLowerCase();if(lower.endsWith(".csv")||lower.endsWith(".txt")){rows=parseCsv(await file.text())}else if(lower.endsWith(".xlsx")||lower.endsWith(".xls")){const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false});for(const sheetName of wb.SheetNames){const rawRows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[sheetName],{defval:"",raw:false});if(!rawRows.length)continue;for(const raw of rawRows){const mapped:Row={};for(const[k,v]of Object.entries(raw)){mapped[aliases[norm(k)]||norm(k).replace(/\s+/g,"_")]=String(v??"").trim()}const nr=normalizeRow(mapped);if(nr.name)rows.push(nr)}}}else throw new Error("Csak CSV, TXT, XLS vagy XLSX fájl támogatott.");if(!rows.length)throw new Error("A fájlban nem találtam felismerhető készítményadatokat.");return runImport(country,sourceName,sourceUrl,rows,`${notes}${notes?" · ":""}Fájl: ${file.name}; sorok: ${rows.length}`)}

export async function syncUksupOfficialCatalog(){await advisorContext();const url="https://www.uksup.sk/storage/app/uploads/public/604/080/af4/604080af43e18263270214.csv";const r=await fetch(url,{cache:"no-store",headers:{"user-agent":"Agrar-Mentor/1.0 official-catalog-sync","accept":"text/csv,text/plain,*/*"}});if(!r.ok)throw new Error(`Az ÚKSÚP hivatalos dataset letöltése sikertelen (HTTP ${r.status}).`);const text=await r.text();const rows=parseCsv(text);if(!rows.length)throw new Error("Az ÚKSÚP dataset letöltődött, de a jelenlegi oszlopstruktúrából nem sikerült készítményadatot felismerni. Használd a fájlfeltöltést, és jelezd a fejlécet.");return runImport("SK","ÚKSÚP ISPOR – Prípravky na ochranu rastlín.csv",url,rows,`Automatikus hivatalos dataset-szinkron; feldolgozott sorok: ${rows.length}.`)}
