"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

// Deployment trigger: UKSUP Z7 fallback parser production sync.
type Row=Record<string,string>;
export type SyncResult={ok:boolean;error?:string;rows?:number;inserted_products?:number;inserted_uses?:number;inserted_ingredients?:number;source_url?:string};
const aliases:Record<string,string>={
 "növényvédő szer neve":"name","novenyvedo szer neve":"name","novenyvedo_szer_neve":"name","készítmény":"name","keszitmeny":"name","obchodny nazov pripravku":"name","nazov pripravku":"name",
 "engedély száma":"authorization_number","engedely szama":"authorization_number","engedelyszam":"authorization_number","cislo autorizacie":"authorization_number",
 "forgalmazási kategória":"regulatory_category","forgalmazasi kategoria":"regulatory_category","forg kategoria":"regulatory_category","kategoria":"regulatory_category",
 "rendeltetés":"function_type","rendeltetes":"function_type","typ funkcie pripravku":"function_type","funkcia pripravku":"function_type",
 "kultúra":"crop","kultura":"crop","plodina":"crop","plodina alebo oblast pouzitia":"crop",
 "károsító":"target","karosito":"target","cél":"target","cel":"target","skodlivy organizmus alebo iny ucel pouzitia":"target",
 "dózis min":"dose_min","dozis min":"dose_min","min dozis":"dose_min","dose_min":"dose_min",
 "dózis max":"dose_max","dozis max":"dose_max","max dozis":"dose_max","dose_max":"dose_max",
 "dózis egység":"dose_unit","dozis egyseg":"dose_unit","jednotka davky":"dose_unit",
 "kijuttatás módja":"application_method","kijuttatas modja":"application_method","sposob aplikacie":"application_method",
 "évi":"phi_days","evi":"phi_days","várakozási idő":"phi_days","varakozasi ido":"phi_days","phi_days":"phi_days",
 "hatóanyag":"ingredient","hatoanyag":"ingredient","hatóanyag összetétel":"ingredient","hatoanyag osszetetel":"ingredient","nazov ucinnej latky":"ingredient","ucinna latka":"ingredient","chemicka latka":"ingredient"
};
const numberedAliases:Record<string,string>={"1":"name","2":"ingredient","3":"authorization_number","6":"function_type","8":"regulatory_category"};
const MAC_CE_HIGH="ÄĀāÉĄÖÜáąČäčĆćéŹźĎíďĒēĖóėôöõúĚěü†°Ę£§•¶ß®©™ę¨≠ģĮįĪ≤≥īĶ∂∑łĻļĽľĹĺŅņŃ¬√ńŇ∆«»… ňŐÕőŌ–—“”‘’÷◊ōŔŕŘ‹›řŖŗŠ‚„šŚśÁŤťÍŽžŪÓÔūŮÚůŰűŲųÝýķŻŁżĢˇ";
function decodeMacCE(buf:ArrayBuffer){const b=new Uint8Array(buf);let out="";for(const x of b)out+=x<128?String.fromCharCode(x):MAC_CE_HIGH[x-128]||"�";return out}
function norm(s:string){return s.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[._-]+/g," ").replace(/\s+/g," ")}
function headerKey(s:string){const raw=norm(s);const num=raw.match(/^(\d+)[a-z]?\s+/)?.[1];if(num&&numberedAliases[num])return numberedAliases[num];const n=raw.replace(/^\d+[a-z]?\s*/,"");return aliases[n]||n.replace(/\s+/g,"_")}
function looksLikeUksupHeader(line:string){const n=norm(line);return n.includes("nazov pripravku")||n.includes("obchodny nazov pripravku")||(/^;*\s*1\s+/.test(line)&&/;\s*2\s+/.test(line)&&/;\s*3\s+/.test(line))}
function parseCsv(input:string){let text=input.replace(/^\uFEFF/,"").trim();if(!text)return[] as Row[];const lines=text.split(/\r?\n/);const headerIndex=lines.findIndex((line,i)=>i<30&&(looksLikeUksupHeader(line)||(()=>{const n=norm(line);return n.includes("novenyvedo szer neve")||n.includes("authorization_number")})()));if(headerIndex>0)text=lines.slice(headerIndex).join("\n");const first=text.split("\n")[0];const counts={";":(first.match(/;/g)?.length||0),",":(first.match(/,/g)?.length||0),"\t":(first.match(/\t/g)?.length||0)};const sep=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||";";const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&q&&n==='"'){cell+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===sep&&!q){row.push(cell.trim());cell="";continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell="";continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];const header=rows[0].map(headerKey);return rows.slice(1).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]||""]))).filter(r=>r.name||r.product_name||r.keszitmeny||r.novenyvedo_szer_neve)}
function parseUksupZ7Fallback(input:string){const out:Row[]=[];const seen=new Set<string>();for(const rawLine of input.replace(/^\uFEFF/,"").split(/\r?\n/)){if((rawLine.match(/;/g)?.length||0)<10)continue;const c=rawLine.split(";").map(v=>v.trim());if(c.length<12)continue;const name=(c[1]||"").trim();if(!name||/^1\s/i.test(name)||/zoznam/i.test(norm(name)))continue;const authorization=(c[3]||"").trim();const ingredient=(c[2]||"").trim();const functionType=(c[7]||"").trim();const category=(c[10]||"").trim();if(!authorization&&!ingredient)continue;const key=`${name.toLowerCase()}|${authorization.toLowerCase()}`;if(seen.has(key))continue;seen.add(key);out.push({name,ingredient,authorization_number:authorization,function_type:functionType,regulatory_category:category});}return out}
function scoreUksupText(text:string){const first=text.split(/\r?\n/).slice(0,12).join("\n");let score=0;if(/Názov prípravku/i.test(first))score+=20;if(/Číslo autorizácie/i.test(first))score+=10;if(/Zoznam prípravkov/i.test(first))score+=5;if(first.split(/\r?\n/).some(looksLikeUksupHeader))score+=5;score-=(first.match(/�/g)?.length||0)*2;return score}
function decodeUksup(buf:ArrayBuffer){const candidates=[new TextDecoder("utf-8",{fatal:false}).decode(buf),new TextDecoder("windows-1250").decode(buf),decodeMacCE(buf)];return candidates.sort((a,b)=>scoreUksupText(b)-scoreUksupText(a))[0]}

async function advisorContext(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role!=="advisor")throw new Error("Csak szaktanácsadó/admin indíthat katalógusimportot.");return{supabase,user}}
async function runImport(country:"HU"|"SK",sourceName:string,sourceUrl:string,rows:Row[],notes:string){if(!rows.length)throw new Error("Nem találtam importálható sort.");const{supabase}=await advisorContext();let totals={rows:0,inserted_products:0,inserted_uses:0,inserted_ingredients:0};for(let i=0;i<rows.length;i+=700){const chunk=rows.slice(i,i+700);const{data,error}=await supabase.rpc("import_plant_protection_catalog",{p_country_code:country,p_source_name:sourceName,p_source_url:sourceUrl,p_rows:chunk,p_notes:notes});if(error)throw new Error(error.message);const d:any=data||{};totals.rows+=Number(d.rows||chunk.length);totals.inserted_products+=Number(d.inserted_products||0);totals.inserted_uses+=Number(d.inserted_uses||0);totals.inserted_ingredients+=Number(d.inserted_ingredients||0)}revalidatePath("/admin/plant-protection-import");revalidatePath("/operations");return totals}

export async function importPlantProtectionCsv(formData:FormData){const country=String(formData.get("country_code")||"HU")==="SK"?"SK":"HU",sourceName=String(formData.get("source_name")||"").trim()||`${country} hivatalos növényvédőszer-katalógus`,sourceUrl=String(formData.get("source_url")||"").trim(),notes=String(formData.get("notes")||"").trim(),csv=String(formData.get("csv")||"");const rows=parseCsv(csv);if(!rows.length)throw new Error("Nem találtam importálható sort. Ellenőrizd a fejlécet és a forrásformátumot.");return runImport(country,sourceName,sourceUrl,rows,notes)}

async function fetchOfficialUksupCsv(){const urls=["https://www.uksup.sk/storage/app/uploads/public/604/080/af4/604080af43e18263270214.csv","https://beta.uksup.sk/storage/app/uploads/public/604/080/af4/604080af43e18263270214.csv","https://raw.githubusercontent.com/challangeguild-ai/Agr-r-mentor/main/data/official/uksup/plant_protection.csv"];const problems:string[]=[];for(const url of urls){const attempts=url.includes("raw.githubusercontent.com")?1:2;for(let attempt=1;attempt<=attempts;attempt++){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),url.includes("raw.githubusercontent.com")?8000:12000);const r=await fetch(url,{cache:"no-store",signal:controller.signal,headers:{"user-agent":"Agrar-Mentor/1.0 official-catalog-sync","accept":"text/csv,text/plain,*/*"}});clearTimeout(timer);if(!r.ok){problems.push(`${new URL(url).host}: HTTP ${r.status}`);continue}const buf=await r.arrayBuffer();if(buf.byteLength<100){problems.push(`${new URL(url).host}: túl rövid válasz`);continue}const text=decodeUksup(buf);return{text,url}}catch(e){problems.push(`${new URL(url).host}: ${e instanceof Error?e.name:"hálózati hiba"}`)}}}throw new Error(`Az ÚKSÚP élő adatforrása és a legutóbbi hivatalos snapshot sem érhető el. ${problems.slice(-5).join("; ")}`)}

export async function syncUksupOfficialCatalog():Promise<SyncResult>{try{await advisorContext();const{text,url}=await fetchOfficialUksupCsv();let rows=parseCsv(text);let fallback=false;if(!rows.length){rows=parseUksupZ7Fallback(text);fallback=true}if(!rows.length)return{ok:false,error:"Az ÚKSÚP fájl letöltődött, de sem a fejléc-alapú, sem a Z7 oszloppozíciós feldolgozó nem talált készítményrekordot."};const snapshot=url.includes("raw.githubusercontent.com");const data:any=await runImport("SK","ÚKSÚP ISPOR – Prípravky na ochranu rastlín.csv",url,rows,`${snapshot?"Hivatalos ÚKSÚP snapshotból helyreállított szinkron":"Automatikus hivatalos élő szinkron"}; ${fallback?"Z7 oszloppozíciós fallback; ":""}feldolgozott sorok: ${rows.length}. A nyilvános Z7 dataset terméktörzs; ahol nincs külön felhasználási/dózis rekord, az alkalmazás engedélyokirat-ellenőrzést kér.`);return{ok:true,source_url:url,rows:Number(data?.rows||rows.length),inserted_products:Number(data?.inserted_products||0),inserted_uses:Number(data?.inserted_uses||0),inserted_ingredients:Number(data?.inserted_ingredients||0)}}catch(e){return{ok:false,error:e instanceof Error?e.message:"Az ÚKSÚP szinkron ismeretlen hiba miatt megszakadt."}}}
