"use client";

import {useState} from "react";
import {importPlantProtectionCsv,syncUksupOfficialCatalog} from "./actions";
import {importUksupDetailedUsesCsv} from "./sk-detailed-actions";
import {startUksupOfficialDetailedSync,processUksupOfficialDetailedSyncChunk,type UksupSyncState} from "./sk-official-batched-actions";
import {syncNebihWithdrawnSnapshot} from "./hu-actions";
import {BlockHelpButton} from "@/components/GuidedTour";

export function ImportForm(){
 const[busy,setBusy]=useState(false),[syncBusy,setSyncBusy]=useState(false),[skDetailedBusy,setSkDetailedBusy]=useState(false),[skAutoBusy,setSkAutoBusy]=useState(false),[huBusy,setHuBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null),[skProgress,setSkProgress]=useState<UksupSyncState|null>(null);
 async function run(formData:FormData){setBusy(true);setError("");setResult(null);try{const r=await importPlantProtectionCsv(formData);setResult(r)}catch(e){setError(e instanceof Error?e.message:"Az import sikertelen.")}finally{setBusy(false)}}
 async function runSk(){setSyncBusy(true);setError("");setResult(null);try{const r=await syncUksupOfficialCatalog();if(!r.ok){setError(r.error||"Az ÚKSÚP szinkron sikertelen.");return}setResult(r)}catch{setError("Az ÚKSÚP szinkron nem fejeződött be. Próbáld újra később; a rendszer nem módosította a meglévő katalógust.")}finally{setSyncBusy(false)}}
 async function runSkAuto(){setSkAutoBusy(true);setError("");setResult(null);try{let r=await startUksupOfficialDetailedSync();if(!r.ok||!r.job_id){setError(r.error||"Az ÚKSÚP részletes szinkron előkészítése sikertelen.");return}setSkProgress(r);let guard=0;while(!r.done&&guard<100){guard++;r=await processUksupOfficialDetailedSyncChunk(r.job_id);if(!r.ok){setSkProgress(r);setError(`${r.error||"A részletes ÚKSÚP szinkron egyik lépése megszakadt."} A már feldolgozott részek megmaradtak; ugyanennek a gombnak az újbóli megnyomásával a folyamat folytatható.`);return}setSkProgress(r);if(!r.done)await new Promise(resolve=>setTimeout(resolve,80))}if(!r.done){setError("A szinkron biztonsági lépésszám-korlátba ütközött. Nyomd meg újra a gombot a folytatáshoz.");return}setResult(r)}catch(e){setError(`${e instanceof Error?e.message:"A kapcsolat megszakadt a részletes ÚKSÚP szinkron közben."} A folyamat állapota az adatbázisban megmarad; nyomd meg újra a gombot a folytatáshoz.`)}finally{setSkAutoBusy(false)}}
 async function runSkDetailed(formData:FormData){setSkDetailedBusy(true);setError("");setResult(null);try{const r=await importUksupDetailedUsesCsv(formData);if(!r.ok){setError(r.error||"Az ÚKSÚP részletes felhasználási import sikertelen.");return}setResult(r)}catch(e){setError(e instanceof Error?e.message:"Az ÚKSÚP részletes felhasználási import nem fejeződött be.")}finally{setSkDetailedBusy(false)}}
 async function runHu(){setHuBusy(true);setError("");setResult(null);try{const r=await syncNebihWithdrawnSnapshot();if(!r.ok){setError(r.error||"A Nébih snapshot szinkron sikertelen.");return}setResult(r)}catch{setError("A Nébih snapshot frissítése nem fejeződött be. A meglévő katalógus változatlan maradt.")}finally{setHuBusy(false)}}
 const anyBusy=busy||syncBusy||skDetailedBusy||skAutoBusy||huBusy;
 const progressTotal=skProgress?.total_rows||0,progressDone=skProgress?.processed_rows||0,progressPct=progressTotal?Math.min(100,Math.round(progressDone/progressTotal*100)):0;
 return <div style={{display:"grid",gap:18}} data-help-block="plant-catalog-import">
  <div style={{display:"flex",justifyContent:"flex-end"}}><BlockHelpButton label="A növényvédelmi katalógus frissítésének magyarázata" content={{title:"Növényvédelmi katalógus frissítése",body:"Ez az adminisztrációs felület a magyar és szlovák növényvédőszer-adatok frissítésére szolgál. A szlovák terméktörzs és a részletes felhasználási XLSX is automatikusan szinkronizálható az ÚKSÚP hivatalos oldaláról; szükség esetén a részletes export kézzel is importálható.",important:"A rendszerben tárolt katalógus döntéstámogatás. Kijuttatásnál mindig az adott ország aktuális hivatalos engedélyokirata és hatályos szabályozása az irányadó.",example:"Példa: először frissíted az ÚKSÚP terméktörzset, majd az automatikus részletes szinkronnal betöltöd a kultúra, célkárosító, dózis, BBCH, kezelésszám és alkalmazási korlátozás adatokat is.",steps:["Frissítsd az ÚKSÚP terméktörzset.","Indítsd az automatikus részletes ÚKSÚP XLSX szinkront.","Ellenőrizd a feldolgozási folyamat százalékos állapotát.","Nézd meg az adatlefedettségi mutatókat.","A műveletfelvitelnél ellenőrizd a kultúra szerinti szűrést és a részletes engedélyezési adatokat.","Ha a kapcsolat megszakad, ugyanazzal a gombbal folytatható a félbehagyott szinkron."]}}/></div>
  <section style={{padding:16,border:"1px solid #dce5dc",borderRadius:14,background:"#fff"}}><h3 style={{marginTop:0}}>Magyar visszavont/lejárt készítmények – Nébih snapshot</h3><p>A Nébih nyilvános, folyamatosan frissülő <b>Visszavont és lejárt érvényességű növényvédő szerek</b> listájából készített verziózott GitHub snapshotot tölti be.</p><button className="btn btn-primary" type="button" onClick={runHu} disabled={anyBusy}>{huBusy?"Nébih snapshot frissítése…":"Nébih visszavont/lejárt lista szinkronizálása"}</button></section>
  <section style={{padding:16,border:"1px solid #dce5dc",borderRadius:14,background:"#fff"}}><h3 style={{marginTop:0}}>Szlovák hivatalos katalógus – automatikus terméktörzs-szinkron</h3><p>Az ÚKSÚP nyilvános <b>Prípravky na ochranu rastlín.csv</b> datasetjét tölti le és importálja közvetlenül a hivatalos forrásból. Ez a készítménytörzs és a hatóanyagok alapja.</p><button className="btn btn-primary" type="button" onClick={runSk} disabled={anyBusy}>{syncBusy?"ÚKSÚP szinkron folyamatban…":"ÚKSÚP hivatalos katalógus szinkronizálása"}</button></section>
  <section style={{padding:16,border:"1px solid #b7d7bd",borderRadius:14,background:"#f3fbf4"}}><h3 style={{marginTop:0}}>Szlovák részletes felhasználások – automatikus hivatalos XLSX</h3><p>A részletes XLSX feldolgozása rövid, különálló szakaszokban történik. A haladás az adatbázisban tárolódik, ezért mobilkapcsolat- vagy böngészőmegszakítás után a következő indítás ugyanonnan folytatja.</p><button className="btn btn-primary" type="button" onClick={runSkAuto} disabled={anyBusy}>{skAutoBusy?`ÚKSÚP feldolgozás… ${progressPct}%`:skProgress&&!skProgress.done?"Félbehagyott ÚKSÚP szinkron folytatása":"ÚKSÚP részletes felhasználások automatikus szinkronizálása"}</button>{skProgress&&<div style={{marginTop:12,padding:12,border:"1px solid #c8dfcb",borderRadius:10,background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,fontSize:13}}><b>Feldolgozás: {progressDone} / {progressTotal} sor</b><b>{progressPct}%</b></div><div style={{height:10,marginTop:8,borderRadius:999,background:"#e7efe8",overflow:"hidden"}}><div style={{width:`${progressPct}%`,height:"100%",background:"#2f7d32",transition:"width .2s ease"}}/></div>{skProgress.with_target!=null&&<small style={{display:"block",marginTop:8}}>Forrásellenőrzés: {skProgress.products??0} készítmény · {skProgress.crops??0} kultúra · célkárosító/céllal {skProgress.with_target??0} rekord · dózissal {skProgress.with_dose??0} rekord.</small>}</div>}<small style={{display:"block",marginTop:8}}>Hibás vagy gyanús XLSX esetén az import még a staging előtt leáll. Már elkezdett, érvényes import megszakítás után folytatható.</small></section>
  <form action={runSkDetailed} className="admin-form" style={{gridTemplateColumns:"1fr 1fr",padding:16,border:"1px solid #c8dfcb",borderRadius:14,background:"#f7fbf7"}}>
   <div className="operation-wide"><h3 style={{margin:"0 0 6px"}}>Tartalék: kézi ÚKSÚP ISPOR részletes import</h3><p style={{margin:"0 0 8px"}}>A hivatalos ISPOR exportból kézzel is betölthető a kultúra, célkárosító/cél, dózis, kijuttatási mód, ÉVI, BBCH, kezelésszám, kezelési intervallum, vízmennyiség és korlátozás.</p></div>
   <label className="operation-wide">Hivatalos ISPOR export URL-je<input name="sk_detailed_source_url" placeholder="https://www.uksup.sk/... vagy az ISPOR export forrása"/></label>
   <label className="operation-wide">Részletes ÚKSÚP táblázat<textarea name="sk_detailed_csv" rows={10} required placeholder={'Obchodný názov prípravku;Číslo autorizácie;Plodina alebo oblasť použitia;Škodlivý organizmus alebo iný účel použitia;Dávka;Jednotka dávky;Spôsob aplikácie;Ochranná doba;BBCH od;BBCH do;Maximálny počet aplikácií;Interval medzi aplikáciami;Množstvo vody od;Množstvo vody do;Obmedzenia'}></textarea></label>
   <button className="btn btn-primary" type="submit" disabled={anyBusy}>{skDetailedBusy?"Részletes ÚKSÚP import folyamatban…":"Kézi ÚKSÚP részletes import"}</button>
  </form>
  <form action={run} className="admin-form" style={{gridTemplateColumns:"1fr 1fr"}}>
   <label>Ország<select name="country_code" defaultValue="HU"><option value="HU">Magyarország / Nébih</option><option value="SK">Szlovákia / ÚKSÚP ISPOR</option></select></label>
   <label>Forrás neve<input name="source_name" placeholder="Nébih növényvédő szer adatbázis"/></label>
   <label className="operation-wide">Forrás URL<input name="source_url" placeholder="https://novenyvedoszer.nebih.gov.hu/Engedelykereso/Kereso"/></label>
   <label className="operation-wide">Megjegyzés<input name="notes" placeholder="Import dátuma, export szűrése, ellenőrzési megjegyzés"/></label>
   <label className="operation-wide">Hivatalos CSV / Excelből kimásolt táblázat<textarea name="csv" rows={10} required placeholder={'name;authorization_number;regulatory_category;function_type;crop;target;dose_min;dose_max;dose_unit;application_method;phi_days;ingredient'}></textarea><small>Az első sor legyen fejléc. A hatályos engedélyokirat szövege minden esetben irányadó.</small></label>
   <button className="btn btn-primary" type="submit" disabled={anyBusy}>{busy?"Import folyamatban…":"Általános katalógus importálása"}</button>
  </form>
  {error&&<div className="error-box"><b>A szinkron nem futott le.</b><br/>{error}</div>}
  {result&&<div style={{padding:14,border:"1px solid #b7d7bd",borderRadius:12,background:"#f3fbf4"}}><div>Import eredmény: <b>{result.total_rows??result.rows??0}</b> sor feldolgozva, <b>{result.inserted_products??0}</b> új készítmény{result.updated_products!=null?<> · <b>{result.updated_products}</b> frissített készítmény</>:null}{result.inserted_uses!=null?<> · <b>{result.inserted_uses}</b> új felhasználás</>:null}{result.updated_uses!=null?<> · <b>{result.updated_uses}</b> frissített felhasználás</>:null}{result.inserted_ingredients!=null?<> · <b>{result.inserted_ingredients}</b> új hatóanyag</>:null}{result.sheets!=null?<> · <b>{result.sheets}</b> munkalap</>:null}.</div>{result.products!=null&&<div style={{marginTop:8,fontSize:13}}>Forrásellenőrzés: <b>{result.products}</b> készítmény · <b>{result.crops}</b> kultúra · dózissal <b>{result.with_dose}</b> rekord · célkárosító/céllal <b>{result.with_target}</b> rekord.</div>}</div>}
 </div>
}
