"use client";

import {useState} from "react";
import {importPlantProtectionCsv,syncUksupOfficialCatalog} from "./actions";
import {syncNebihWithdrawnSnapshot} from "./hu-actions";
import {BlockHelpButton} from "@/components/GuidedTour";

export function ImportForm(){
 const[busy,setBusy]=useState(false),[syncBusy,setSyncBusy]=useState(false),[huBusy,setHuBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null);
 async function run(formData:FormData){setBusy(true);setError("");setResult(null);try{const r=await importPlantProtectionCsv(formData);setResult(r)}catch(e){setError(e instanceof Error?e.message:"Az import sikertelen.")}finally{setBusy(false)}}
 async function runSk(){setSyncBusy(true);setError("");setResult(null);try{const r=await syncUksupOfficialCatalog();if(!r.ok){setError(r.error||"Az ÚKSÚP szinkron sikertelen.");return}setResult(r)}catch{setError("Az ÚKSÚP szinkron nem fejeződött be. Próbáld újra később; a rendszer nem módosította a meglévő katalógust.")}finally{setSyncBusy(false)}}
 async function runHu(){setHuBusy(true);setError("");setResult(null);try{const r=await syncNebihWithdrawnSnapshot();if(!r.ok){setError(r.error||"A Nébih snapshot szinkron sikertelen.");return}setResult(r)}catch{setError("A Nébih snapshot frissítése nem fejeződött be. A meglévő katalógus változatlan maradt.")}finally{setHuBusy(false)}}
 return <div style={{display:"grid",gap:18}} data-help-block="plant-catalog-import">
  <div style={{display:"flex",justifyContent:"flex-end"}}><BlockHelpButton label="A növényvédelmi katalógus frissítésének magyarázata" content={{title:"Növényvédelmi katalógus frissítése",body:"Ez az adminisztrációs felület a magyar és szlovák növényvédőszer-adatok frissítésére szolgál. A szlovák katalógus közvetlen ÚKSÚP szinkront használ, a magyar visszavont/lejárt lista pedig verziózott Nébih snapshotból frissíthető. Szükség esetén kézi hivatalos CSV-import is végezhető.",important:"A rendszerben tárolt katalógus döntéstámogatás. Kijuttatásnál mindig az adott ország aktuális hivatalos engedélyokirata és hatályos szabályozása az irányadó. Kézi importba csak ellenőrzött hatósági forrásból származó adat kerülhet.",example:"Példa: a szlovák katalógus frissítéséhez az ÚKSÚP szinkront indítod. Ha a magyar visszavont lista változott, a Nébih snapshot szinkront futtatod. Egyedi hivatalos export esetén az országot, forrást és a táblázatot kézzel adod meg.",steps:["Döntsd el, melyik ország adatait frissíted.","Szlovákiánál indítsd az ÚKSÚP hivatalos katalógus szinkronizálását.","Magyar visszavont/lejárt adatoknál indítsd a Nébih snapshot frissítést.","Kézi importnál válaszd ki az országot és add meg a hivatalos forrás nevét/URL-jét.","Illeszd be a fejlécet is tartalmazó hivatalos CSV vagy Excel-adatot.","Futtatás után ellenőrizd a feldolgozott, új és frissített rekordok számát, valamint az esetleges hibát."]}}/></div>
  <section style={{padding:16,border:"1px solid #dce5dc",borderRadius:14,background:"#fff"}}><h3 style={{marginTop:0}}>Magyar visszavont/lejárt készítmények – Nébih snapshot</h3><p>A Nébih nyilvános, folyamatosan frissülő <b>Visszavont és lejárt érvényességű növényvédő szerek</b> listájából készített verziózott GitHub snapshotot tölti be. A készítmények megmaradnak történeti keresésre; a rendszer a visszavonás és a felhasználási türelmi idő alapján dönti el, hogy egy adott műveleti dátumon még alkalmazhatóak-e.</p><button className="btn btn-primary" type="button" onClick={runHu} disabled={huBusy||syncBusy||busy}>{huBusy?"Nébih snapshot frissítése…":"Nébih visszavont/lejárt lista szinkronizálása"}</button></section>
  <section style={{padding:16,border:"1px solid #dce5dc",borderRadius:14,background:"#fff"}}><h3 style={{marginTop:0}}>Szlovák hivatalos katalógus – automatikus szinkron</h3><p>Az ÚKSÚP nyilvános <b>Prípravky na ochranu rastlín.csv</b> datasetjét tölti le és importálja közvetlenül a hivatalos forrásból. A rendszer elsődleges és tartalék ÚKSÚP végponttal, időkorláttal és újrapróbálással dolgozik.</p><button className="btn btn-primary" type="button" onClick={runSk} disabled={syncBusy||busy||huBusy}>{syncBusy?"ÚKSÚP szinkron folyamatban…":"ÚKSÚP hivatalos katalógus szinkronizálása"}</button></section>
  <form action={run} className="admin-form" style={{gridTemplateColumns:"1fr 1fr"}}>
   <label>Ország<select name="country_code" defaultValue="HU"><option value="HU">Magyarország / Nébih</option><option value="SK">Szlovákia / ÚKSÚP ISPOR</option></select></label>
   <label>Forrás neve<input name="source_name" placeholder="Nébih növényvédő szer adatbázis"/></label>
   <label className="operation-wide">Forrás URL<input name="source_url" placeholder="https://novenyvedoszer.nebih.gov.hu/Engedelykereso/Kereso"/></label>
   <label className="operation-wide">Megjegyzés<input name="notes" placeholder="Import dátuma, export szűrése, ellenőrzési megjegyzés"/></label>
   <label className="operation-wide">Hivatalos CSV / Excelből kimásolt táblázat<textarea name="csv" rows={14} required placeholder={'name;authorization_number;regulatory_category;function_type;crop;target;dose_min;dose_max;dose_unit;application_method;phi_days;ingredient\nMinta készítmény;ABC-123;II;gyomirtó;kukorica;egyszikű gyomok;0,8;1,2;l/ha;permetezés;56;hatóanyag'}></textarea><small>Az első sor legyen fejléc. Magyar és szlovák oszlopneveket is felismer a rendszer. A Nébih esetében csak hivatalos keresőből/engedélyokiratból származó adat tölthető be. A hatályos engedélyokirat szövege minden esetben irányadó.</small></label>
   <button className="btn btn-primary" type="submit" disabled={busy||syncBusy||huBusy}>{busy?"Import folyamatban…":"Katalógus importálása"}</button>
  </form>
  {error&&<div className="error-box"><b>A szinkron nem futott le.</b><br/>{error}</div>}
  {result&&<div style={{padding:14,border:"1px solid #b7d7bd",borderRadius:12,background:"#f3fbf4"}}>Import eredmény: <b>{result.rows??0}</b> sor feldolgozva, <b>{result.inserted_products??0}</b> új készítmény{result.updated_products!=null?<> · <b>{result.updated_products}</b> frissített készítmény</>:null}{result.inserted_uses!=null?<> · <b>{result.inserted_uses}</b> új felhasználás</>:null}{result.inserted_ingredients!=null?<> · <b>{result.inserted_ingredients}</b> új hatóanyag</>:null}.</div>}
 </div>
}
