import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {AdminNav} from "@/components/AdminNav";
import {BlockHelpButton} from "@/components/GuidedTour";
import {ImportForm} from "./ImportForm";

export const maxDuration=60;

export default async function PlantProtectionImportPage(){
 const supabase=await createClient();
 const{data:{user}}=await supabase.auth.getUser();
 if(!user)redirect("/login");
 const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();
 if(me?.role!=="advisor")redirect("/dashboard");
 const[{data:sources},{data:batches},{data:coverageRows}]=await Promise.all([
  supabase.from("operation_catalog_sources").select("country_code,source_name,source_url,last_imported_at,product_count,use_count,status,notes").in("country_code",["HU","SK"]).order("country_code"),
  supabase.from("plant_protection_import_batches").select("id,country_code,source_name,imported_at,row_count,product_count,use_count,ingredient_count").order("imported_at",{ascending:false}).limit(10),
  supabase.rpc("plant_protection_use_coverage",{p_country_code:"SK"})
 ]);
 const coverage=Array.isArray(coverageRows)?coverageRows[0]:coverageRows;
 const skCoverage={uses:Number(coverage?.uses??0),dose:Number(coverage?.dose??0),bbch:Number(coverage?.bbch??0),water:Number(coverage?.water??0),restrictions:Number(coverage?.restrictions??0),timing:Number(coverage?.timing??0)};
 const pct=(n:number)=>skCoverage.uses?Math.round(n/skCoverage.uses*100):0;
 return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">NÖVÉNYVÉDELEM</span><h1>Növényvédőszer-katalógus</h1><p>Hivatalos Nébih és ÚKSÚP/ISPOR forrásadatok kezelése a készítmény–kultúra–felhasználás–dózis katalógusban. Ez katalóguskezelés, nem gazdasági kijuttatási jóváhagyás.</p></div></header><AdminNav active="plant-protection-import"/>
 <section className="panel" data-help-block="advisor-plant-role"><div className="panel-heading"><div><span className="eyebrow">SZEREPKÖR</span><h2>Mit végez itt a szaktanácsadó?</h2></div><BlockHelpButton label="A növényvédelmi katalógus szerepkörének magyarázata" content={{title:"Szaktanácsadói katalóguskezelés",body:"Ezen az oldalon a szaktanácsadó a hivatalos növényvédőszer-adatforrások betöltését, frissességét és adatminőségét ellenőrzi. Ez biztosítja, hogy a szakmai munkában használható készítmény-, kultúra-, cél- és dózisadatok dokumentált forrásból származzanak.",important:"Ez nem gazdasági kijuttatási jóváhagyás. Az engedélyköteles művelet tényleges jóváhagyását a gazdasághoz rendelt, megfelelő jogosultságú személy végzi."}}/></div><p>A szaktanácsadó ezen az oldalon a hivatalos növényvédőszer-adatforrásokat kezeli és ellenőrzi. A gazdaság által rögzített engedélyköteles kijuttatást nem a szaktanácsadó hagyja jóvá; azt a gazdasághoz rendelt megfelelő jogosultságú személy végzi.</p></section>
 <section className="panel" data-help-block="advisor-plant-sources"><div className="panel-heading"><div><span className="eyebrow">ÁLLAPOT</span><h2>Betöltött katalógusok</h2></div><BlockHelpButton label="A betöltött katalógusok magyarázata" content={{title:"HU/SK katalógusállapot",body:"A magyar és szlovák kártyák megmutatják az adott ország betöltött készítményeinek és engedélyezett felhasználásainak számát, az import állapotát és az utolsó frissítés idejét. Így azonnal látható, hogy melyik hivatalos forrásból milyen katalógusállomány áll rendelkezésre.",important:"A rendszer hiányzó hivatalos adatot nem egészít ki becsléssel vagy kitalált dózissal. Konkrét növényvédelmi döntésnél mindig a hatályos engedélyokirat az irányadó."}}/></div><div className="stats-grid">{["HU","SK"].map(c=>{const s=sources?.find(x=>x.country_code===c);return <article className="stat-card" key={c}><span>{c==="HU"?"Magyarország":"Szlovákia"}</span><strong>{s?.product_count??0}</strong><small>{s?.use_count??0} felhasználás · {s?.status||"nincs import"}{s?.last_imported_at?` · ${new Date(s.last_imported_at).toLocaleString("hu-HU")}`:""}</small></article>})}</div><p style={{marginTop:12}}>A hivatalos forrásadatot a rendszer nem egészíti ki kitalált dózissal. A konkrét felhasználásnál mindig a hatályos engedélyokirat az irányadó.</p></section>
 <section className="panel" data-help-block="advisor-plant-coverage"><div className="panel-heading"><div><span className="eyebrow">ÚKSÚP ADATMINŐSÉG</span><h2>Szlovák részletes felhasználási lefedettség</h2></div><BlockHelpButton label="A szlovák adatlefedettség magyarázata" content={{title:"ÚKSÚP részletes adatlefedettség",body:"Ez a blokk azt méri, hogy a szlovák kultúra–cél felhasználási rekordok közül hány tartalmaz dózist, BBCH-információt, vízmennyiséget, korlátozást és alkalmazási időt. A százalékok tehát adatmező-lefedettséget, nem szakmai minősítést jelentenek.",important:"A 100% nem önálló cél. Csak az a részletes adat kerülhet a katalógusba, amely ténylegesen szerepel a hivatalos forrásban."}}/></div>{skCoverage.uses?<><div className="stats-grid"><article className="stat-card"><span>Felhasználási rekord</span><strong>{skCoverage.uses}</strong><small>kultúra–cél kapcsolatok</small></article><article className="stat-card"><span>Dózissal</span><strong>{pct(skCoverage.dose)}%</strong><small>{skCoverage.dose} rekord</small></article><article className="stat-card"><span>BBCH-val</span><strong>{pct(skCoverage.bbch)}%</strong><small>{skCoverage.bbch} rekord</small></article><article className="stat-card"><span>Vízmennyiséggel</span><strong>{pct(skCoverage.water)}%</strong><small>{skCoverage.water} rekord</small></article><article className="stat-card"><span>Korlátozással</span><strong>{pct(skCoverage.restrictions)}%</strong><small>{skCoverage.restrictions} rekord</small></article><article className="stat-card"><span>Alkalmazási idővel</span><strong>{pct(skCoverage.timing)}%</strong><small>{skCoverage.timing} rekord</small></article></div><p style={{marginTop:12}}>Ez a blokk megmutatja, hogy az ÚKSÚP készítménytörzs mögött mennyi ténylegesen használható, részletes engedélyezési adat áll rendelkezésre. A 100% nem cél önmagában: csak a hivatalos forrásban ténylegesen szereplő adat kerülhet be.</p></>:<div className="empty-state">A szlovák készítménytörzs már betölthető, de részletes kultúra–cél–dózis rekord még nincs. A lenti részletes ÚKSÚP importtal tölthető fel.</div>}</section>
 <section className="panel" data-help-block="advisor-plant-import"><div className="panel-heading"><div><span className="eyebrow">KATALÓGUS FRISSÍTÉS</span><h2>Hivatalos források</h2></div><BlockHelpButton label="A katalógusfrissítés magyarázata" content={{title:"Hivatalos katalógusfrissítés",body:"Ebben a blokkban indítható a támogatott hivatalos magyar és szlovák források feldolgozása. Az import a katalógus készítmény-, felhasználás- és kapcsolódó engedélyezési adatait frissíti.",important:"Importot csak ismert hivatalos forrásból indíts. A frissítés után az állapot- és adatlefedettségi blokkokban ellenőrizd az eredményt."}}/></div><ImportForm/></section>
 <section className="panel" data-help-block="advisor-plant-history"><div className="panel-heading"><div><span className="eyebrow">ELŐZMÉNY</span><h2>Legutóbbi importok</h2></div><BlockHelpButton label="Az importelőzmények magyarázata" content={{title:"Katalógusimportok előzménye",body:"Az előzménylista importonként megmutatja az országot, forrást, időpontot, feldolgozott sorok számát, valamint az új készítmények, felhasználások és hatóanyagok mennyiségét. Ebből visszakövethető, mikor és milyen tartalommal frissült a katalógus.",important:"Az importelőzmény az adatbetöltés auditnyoma; önmagában nem igazolja egy konkrét készítmény aktuális felhasználhatóságát."}}/></div>{batches?.length?<div className="inspection-list">{batches.map(b=><article className="inspection-card" key={b.id}><div className="inspection-head"><div><strong>{b.country_code} · {b.source_name}</strong><small>{new Date(b.imported_at).toLocaleString("hu-HU")}</small></div><span className="field-total">{b.row_count} sor</span></div><p>{b.product_count} új készítmény · {b.use_count} új felhasználás · {b.ingredient_count} új hatóanyag</p></article>)}</div>:<div className="empty-state">Még nincs katalógusimport.</div>}</section>
 </main>
}
