"use server";

import * as XLSX from "xlsx";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

type Row=Record<string,string>;
type Parsed={rows:Row[];sheets:number;products:number;crops:number;withDose:number;withTarget:number;sourceUrl:string};
export type UksupSyncState={ok:boolean;error?:string;job_id?:string;done?:boolean;status?:string;total_rows?:number;processed_rows?:number;inserted_products?:number;inserted_uses?:number;updated_uses?:number;inserted_ingredients?:number;source_url?:string;sheets?:number;products?:number;crops?:number;with_dose?:number;with_target?:number;remaining_chunks?:number};

const aliases:Record<string,string>={
 "obchodny nazov pripravku":"name","nazov pripravku":"name",pripravok:"name","nazov por":"name",
 "cislo autorizacie":"authorization_number","cislo povolenia":"authorization_number","autorizacne cislo":"authorization_number",
 "typ funkcie pripravku":"function_type","funkcia pripravku":"function_type",funkcia:"function_type",
 plodina:"crop","plodina alebo oblast pouzitia":"crop","oblast pouzitia":"crop",pouzitie:"crop",
 "skodlivy organizmus alebo iny ucel pouzitia":"target","skodlivy organizmus":"target","skodlivy cinitel":"target","ucel pouzitia":"target",skodca:"target",
 davka:"dose_raw","davka pripravku":"dose_raw","maximalna davka":"dose_raw","max davka mj":"dose_raw","minimalna davka":"dose_min",
 "jednotka davky":"dose_unit","merna jednotka davky":"dose_unit",
 "sposob aplikacie":"application_method","metoda aplikacie":"application_method","metoda pouzitia":"application_method",
 "ochranna doba":"phi_raw","ochranna lehota":"phi_raw",phi:"phi_raw",
 "bbch od":"bbch_min","bbch min":"bbch_min","rastova faza od":"bbch_min","stadium rastu od":"bbch_min",
 "bbch do":"bbch_max","bbch max":"bbch_max","rastova faza do":"bbch_max","stadium rastu do":"bbch_max","rastova faza":"bbch_range","rastove stadium":"bbch_range",bbch:"bbch_range",
 "maximalny pocet aplikacii":"max_applications","max pocet aplikacii":"max_applications","pocet aplikacii":"max_applications","max pocet pouziti":"max_applications","max pocet pouziti / sezona":"max_applications_season",
 "interval medzi aplikaciami":"application_interval_days","interval aplikacie":"application_interval_days",interval:"application_interval_days",
 "mnozstvo vody":"water_raw","objem vody":"water_raw","mnozstvo vody od":"water_volume_min","objem vody od":"water_volume_min","minimalne mnozstvo vody":"water_volume_min","mnozstvo vody do":"water_volume_max","objem vody do":"water_volume_max","maximalne mnozstvo vody":"water_volume_max",
 "termin aplikacie":"application_timing","cas aplikacie":"application_timing","poznamka k aplikacii":"application_timing",
 obmedzenia:"restrictions",obmedzenie:"restrictions","osobitne podmienky":"restrictions","podmienky pouzitia":"restrictions",poznamka:"restrictions",
 "ucinna latka":"ingredient","nazov ucinnej latky":"ingredient","chemicka latka":"ingredient","aktivna zlozka":"ingredient","ucinna latka / aktivna zlozka":"ingredient",
 "max davka / sezona mj":"seasonal_dose_raw",formulacia:"formulation","tank mix":"tank_mix","minoritne pouzitie":"minor_use",
 "drzitel autorizacie":"authorization_holder","doba autorizacie pripravku":"authorization_period_raw","datum ukoncenia predaja":"sale_end_raw","datum ukoncenia spotreby":"use_end_raw","stav rozhodnutia":"decision_status","typ pripravku":"product_type","typ pouzivatela":"user_type","paralelny obchod":"parallel_trade","referencny pripravok":"reference_product"
};
const pages=["https://www.uksup.sk/orp-zoznamy-pripravkov-na-ochranu-rastlin","https://beta.uksup.sk/orp-zoznamy-pripravkov-na-ochranu-rastlin"];
const important=new Set(["name","authorization_number","crop","target","dose_raw","dose_min","dose_unit","application_method","phi_raw","bbch_min","bbch_max","bbch_range","max_applications","application_interval_days","water_raw","water_volume_min","water_volume_max","application_timing","restrictions","ingredient"]);
function norm(v:string){return v.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/&nbsp;|\u00a0/g," ").replace(/[._–—-]+/g," ").replace(/\s*\/\s*/g," / ").replace(/\s+/g," ")}
function headerKey(v:string){const n=norm(v).replace(/^\d+[a-z]?\s*/,"");if(!n)return"";if(aliases[n])return aliases[n];if((n.includes("skodliv")&&(n.includes("organiz")||n.includes("cinitel")))||n.includes("skodca"))return"target";if(n.includes("ucel")&&n.includes("pouzitia")&&!n.includes("oblast"))return"target";if(n.includes("plodin")||(n.includes("oblast")&&n.includes("pouzitia")))return"crop";if((n.includes("ucinna")&&n.includes("latka"))||(n.includes("aktivna")&&n.includes("zlozka")))return"ingredient";if(n.includes("ochrann")&&(n.includes("dob")||n.includes("lehot")))return"phi_raw";if(n.includes("bbch")||n.includes("rastov")||n.includes("stadium")){if(n.includes("od")||n.includes("min"))return"bbch_min";if(n.includes("do")||n.includes("max"))return"bbch_max";return"bbch_range"}if(n.includes("pocet")&&(n.includes("aplik")||n.includes("pouziti")))return n.includes("sezona")?"max_applications_season":"max_applications";if(n.includes("max")&&n.includes("davka"))return n.includes("sezona")?"seasonal_dose_raw":"dose_raw";if(n.includes("interval")&&n.includes("aplik"))return"application_interval_days";if((n.includes("mnozstvo")||n.includes("objem"))&&n.includes("vod")){if(n.includes("od")||n.includes("min"))return"water_volume_min";if(n.includes("do")||n.includes("max"))return"water_volume_max";return"water_raw"}if((n.includes("termin")||n.includes("cas"))&&n.includes("aplik"))return"application_timing";if(n.includes("obmedzen")||n.includes("podmien")||n.includes("poznam"))return"restrictions";return n.replace(/\s+/g,"_")}
function nums(v:string){return(v.replace(/,/g,".").match(/\d+(?:\.\d+)?/g)||[]).map(Number).filter(Number.isFinite)}
function unit(v:string){return v.match(/(?:ml|l|kg|g)\s*\/\s*(?:ha|100\s*l)|(?:ml|l|kg|g)\b/i)?.[0]?.replace(/\s+/g,"")||""}
function add(a:string,b:string){return[a,b].filter(Boolean).join(" · ")}
function normalizeRow(original:Row){const r={...original};const d=String(r.dose_raw||"");if(d){const n=nums(d);if(n.length){r.dose_min=String(n.length>1?Math.min(...n):n[0]);r.dose_max=String(n.length>1?Math.max(...n):n[0])}if(!r.dose_unit)r.dose_unit=unit(d)}const w=String(r.water_raw||"");if(w){const n=nums(w);if(n.length){r.water_volume_min=String(n.length>1?Math.min(...n):n[0]);r.water_volume_max=String(n.length>1?Math.max(...n):n[0])}r.water_volume_unit=unit(w)||"l/ha"}const b=String(r.bbch_range||"");if(b){const n=nums(b).map(Math.trunc).filter(x=>x>=0&&x<=99);if(n.length){r.bbch_min=String(Math.min(...n));r.bbch_max=String(Math.max(...n))}}const p=String(r.phi_raw||"").trim();if(p){const n=nums(p);if(n.length)r.phi_days=String(Math.trunc(n[0]));else r.restrictions=add(r.restrictions||"",`Ochranná doba: ${p}`)}if(r.max_applications_season)r.restrictions=add(r.restrictions||"",`Max. počet použití / sezóna: ${r.max_applications_season}`);if(r.seasonal_dose_raw)r.restrictions=add(r.restrictions||"",`Max. dávka / sezóna: ${r.seasonal_dose_raw}`);if(r.formulation)r.restrictions=add(r.restrictions||"",`Formulácia: ${r.formulation}`);if(r.tank_mix)r.restrictions=add(r.restrictions||"",`Tank-mix: ${r.tank_mix}`);if(r.minor_use)r.restrictions=add(r.restrictions||"",`Minoritné použitie: ${r.minor_use}`);for(const k of["bbch_min","bbch_max","max_applications","application_interval_days"]){const n=nums(String(r[k]||""));r[k]=n.length?String(Math.trunc(n[0])):""}for(const k of["dose_min","dose_max","water_volume_min","water_volume_max"]){const n=nums(String(r[k]||""));r[k]=n.length?String(n[0]):""}if(r.bbch_min&&Number(r.bbch_min)>99)r.bbch_min="";if(r.bbch_max&&Number(r.bbch_max)>99)r.bbch_max="";if(r.bbch_min&&r.bbch_max&&Number(r.bbch_min)>Number(r.bbch_max))[r.bbch_min,r.bbch_max]=[r.bbch_max,r.bbch_min];r.source_reference=r.source_reference||"ÚKSÚP – rozsah použitia (hivatalos XLSX)";return r}
function combined(matrix:(string|number|null)[][],start:number,depth:number){const max=Math.max(0,...matrix.slice(start,start+depth).map(r=>r?.length||0));return Array.from({length:max},(_,c)=>{const parts:string[]=[];for(let i=start;i<start+depth;i++){const raw=String(matrix[i]?.[c]??"").trim();if(raw&&!parts.some(p=>norm(p)===norm(raw)))parts.push(raw)}return parts.join(" ").trim()})}
function detect(matrix:(string|number|null)[][]){let best:{start:number;depth:number;keys:string[];score:number}|undefined;for(let s=0;s<Math.min(matrix.length,60);s++)for(let d=1;d<=3&&s+d<=matrix.length;d++){const keys=combined(matrix,s,d).map(headerKey),u=new Set(keys.filter(Boolean));if(!u.has("name")||!u.has("crop"))continue;let score=50;for(const k of u)if(important.has(k))score+=4;if(u.has("target"))score+=25;if(u.has("dose_raw")||u.has("dose_min"))score+=10;if(!best||score>best.score||(score===best.score&&d<best.depth))best={start:s,depth:d,keys,score}}return best}
function sheetRows(sheet:XLSX.WorkSheet){const matrix=XLSX.utils.sheet_to_json<(string|number|null)[]>(sheet,{header:1,raw:false,defval:""}) as unknown as (string|number|null)[][];const h=detect(matrix);if(!h)return{rows:[] as Row[],diag:"nincs felismerhető fejléc"};const out:Row[]=[],carry:Row={};for(const cells of matrix.slice(h.start+h.depth)){const r:Row={};h.keys.forEach((k,i)=>{if(k)r[k]=String(cells?.[i]??"").trim()});for(const k of["name","authorization_number","function_type","ingredient","authorization_holder"]){if(r[k])carry[k]=r[k];else if(carry[k])r[k]=carry[k]}if(!r.name||!r.crop)continue;out.push(normalizeRow(r))}return{rows:out,diag:`fejléc ${h.start+1}. sor, ${h.depth} sor mély; mezők: ${h.keys.filter(Boolean).join(", ")}`}}
function workbook(buffer:ArrayBuffer){const wb=XLSX.read(buffer,{type:"array",cellDates:false}),all:Row[]=[],diag:string[]=[];for(const name of wb.SheetNames){const s=wb.Sheets[name];if(!s)continue;const p=sheetRows(s);all.push(...p.rows);diag.push(`${name}: ${p.diag}`)}const map=new Map<string,Row>();for(const r of all){const k=[r.name,r.authorization_number,r.crop,r.target,r.dose_max,r.dose_unit,r.application_method,r.bbch_min,r.bbch_max].map(v=>norm(v||"")).join("|");if(!map.has(k))map.set(k,r)}const rows=[...map.values()],products=new Set(rows.map(r=>norm(r.name))).size,crops=new Set(rows.map(r=>norm(r.crop))).size,withDose=rows.filter(r=>r.dose_max||r.dose_min).length,withTarget=rows.filter(r=>r.target).length;if(rows.length<100||products<20||crops<5)throw new Error(`A részletes XLSX szerkezete gyanús: ${rows.length} felhasználás, ${products} készítmény, ${crops} kultúra. ${diag.join(" | ")}`);if(withTarget===0)throw new Error(`A részletes XLSX ${rows.length} felhasználást tartalmaz, de egyetlen célkárosító/célfelhasználás sem volt felismerhető. ${diag.join(" | ")}`);return{rows,sheets:wb.SheetNames.length,products,crops,withDose,withTarget}}
async function textFetch(url:string,timeout=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:"no-store",signal:c.signal,headers:{"user-agent":"Agrar-Mentor/1.0 UKSUP staged sync",accept:"text/html,*/*"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function binFetch(url:string,timeout=30000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:"no-store",signal:c.signal,headers:{"user-agent":"Agrar-Mentor/1.0 UKSUP staged sync",accept:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,*/*"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.arrayBuffer();if(b.byteLength<10000)throw new Error("A letöltött XLSX túl kicsi.");if(b.byteLength>30*1024*1024)throw new Error("A letöltött XLSX szokatlanul nagy.");const sig=new Uint8Array(b.slice(0,4));if(!(sig[0]===0x50&&sig[1]===0x4b))throw new Error("A letöltött állomány nem XLSX/ZIP formátumú.");return b}finally{clearTimeout(t)}}
function strip(v:string){return v.replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim()}
async function discover():Promise<Parsed>{const problems:string[]=[];for(const page of pages){try{const html=await textFetch(page),anchors=[...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)],candidates=anchors.map(m=>({href:m[1],text:strip(m[2])})).map(x=>({...x,score:(norm(x.text).includes("rozsahom ich pouzitia")?100:0)+(norm(x.text).includes("autorizovanych a povolenych")?60:0)+(x.href.toLowerCase().includes("xlsx")?20:0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);for(const c of candidates){try{const sourceUrl=new URL(c.href,page).toString(),parsed=workbook(await binFetch(sourceUrl));return{...parsed,sourceUrl}}catch(e){problems.push(`${new URL(page).host}: ${e instanceof Error?e.message:"XLSX hiba"}`)}}problems.push(`${new URL(page).host}: nem találtam megfelelő részletes XLSX hivatkozást`)}catch(e){problems.push(`${new URL(page).host}: ${e instanceof Error?e.message:"oldalhiba"}`)}}throw new Error(`A hivatalos ÚKSÚP részletes XLSX automatikus letöltése nem sikerült. ${problems.slice(-6).join("; ")}`)}
async function ctx(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(p?.role!=="advisor")throw new Error("Csak szaktanácsadó/admin indíthat ÚKSÚP részletes szinkront.");return{supabase,user}}
function state(j:any):UksupSyncState{const m=j.metadata||{};return{ok:true,job_id:j.id,done:j.status==="completed",status:j.status,total_rows:Number(j.total_rows||0),processed_rows:Number(j.processed_rows||0),inserted_products:Number(j.inserted_products||0),inserted_uses:Number(j.inserted_uses||0),updated_uses:Number(j.updated_uses||0),inserted_ingredients:Number(j.inserted_ingredients||0),source_url:j.source_url,sheets:Number(m.sheets||0),products:Number(m.products||0),crops:Number(m.crops||0),with_dose:Number(m.with_dose||0),with_target:Number(m.with_target||0)}}

export async function startUksupOfficialDetailedSync():Promise<UksupSyncState>{try{const{supabase,user}=await ctx();const now=new Date().toISOString();const{data:existing}=await supabase.from("plant_protection_sync_jobs").select("*").eq("created_by",user.id).eq("country_code","SK").in("status",["prepared","running","error"]).gt("expires_at",now).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existing)return state(existing);const p=await discover(),chunkSize=300,totalChunks=Math.ceil(p.rows.length/chunkSize);const{data:job,error}=await supabase.from("plant_protection_sync_jobs").insert({country_code:"SK",source_name:"ÚKSÚP – hivatalos részletes felhasználási XLSX",source_url:p.sourceUrl,status:"prepared",total_rows:p.rows.length,processed_rows:0,metadata:{sheets:p.sheets,products:p.products,crops:p.crops,with_dose:p.withDose,with_target:p.withTarget,total_chunks:totalChunks},created_by:user.id}).select("*").single();if(error)throw new Error(error.message);const chunks=Array.from({length:totalChunks},(_,i)=>({job_id:job.id,chunk_no:i,row_count:p.rows.slice(i*chunkSize,(i+1)*chunkSize).length,rows:p.rows.slice(i*chunkSize,(i+1)*chunkSize)}));const{error:chunkError}=await supabase.from("plant_protection_sync_job_chunks").insert(chunks);if(chunkError){await supabase.from("plant_protection_sync_jobs").delete().eq("id",job.id);throw new Error(chunkError.message)}return state(job)}catch(e){return{ok:false,error:e instanceof Error?e.message:"Az ÚKSÚP szinkron előkészítése ismeretlen hiba miatt megszakadt."}}}

export async function processUksupOfficialDetailedSyncChunk(jobId:string):Promise<UksupSyncState>{try{const{supabase}=await ctx();if(!/^[0-9a-f-]{36}$/i.test(jobId))throw new Error("Érvénytelen szinkronazonosító.");const{data,error}=await supabase.rpc("process_plant_protection_sync_job_chunk",{p_job_id:jobId});if(error)throw new Error(error.message);const r:any=data||{};if(r.done){revalidatePath("/admin/plant-protection-import");revalidatePath("/operations")}const m=r.metadata||{};return{ok:true,job_id:r.job_id,done:!!r.done,status:r.status,total_rows:Number(r.total_rows||0),processed_rows:Number(r.processed_rows||0),inserted_products:Number(r.inserted_products||0),inserted_uses:Number(r.inserted_uses||0),updated_uses:Number(r.updated_uses||0),inserted_ingredients:Number(r.inserted_ingredients||0),source_url:r.source_url,sheets:Number(m.sheets||0),products:Number(m.products||0),crops:Number(m.crops||0),with_dose:Number(m.with_dose||0),with_target:Number(m.with_target||0),remaining_chunks:Number(r.remaining_chunks||0)}}catch(e){return{ok:false,error:e instanceof Error?e.message:"Az ÚKSÚP szinkron egy feldolgozási lépése megszakadt."}}}
