import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Sidebar} from "@/components/Sidebar";
import {BlockHelpButton} from "@/components/GuidedTour";
import {operationLabel} from "@/lib/operations";

function huDate(v:string|null){return v?new Date(v.includes("T")?v:`${v}T12:00:00`).toLocaleString("hu-HU"):"—"}
const auditLabel:Record<string,string>={created:"Létrehozva",updated:"Módosítva",approval_requested:"Jóváhagyásra küldve",approved:"Jóváhagyva",approval_invalidated:"Jóváhagyás érvénytelenítve",deleted:"Törölve"};
export default async function OperationDetailPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params,supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data:profile}=await supabase.from("profiles").select("role,full_name").eq("id",user.id).maybeSingle();
 const{data:op}=await supabase.from("field_operations").select("*").eq("id",id).maybeSingle();if(!op)notFound();
 const[{data:farm},{data:field},{data:audit}]=await Promise.all([supabase.from("farms").select("name").eq("id",op.farm_id).maybeSingle(),supabase.from("fields").select("name,area_ha").eq("id",op.field_id).maybeSingle(),supabase.from("field_operation_audit_log").select("id,action,changed_at,changed_by,changed_fields").eq("operation_id",id).order("changed_at",{ascending:false})]);
 const actorIds=Array.from(new Set((audit??[]).map(a=>a.changed_by).filter(Boolean)));const{data:actors}=actorIds.length?await supabase.from("profiles").select("id,full_name").in("id",actorIds):{data:[]};const actorMap=new Map((actors??[]).map(a=>[a.id,a.full_name]));
 return <div className="app-shell farmer-app"><Sidebar active="operations" userName={profile?.full_name||"Gazdálkodó"}/><main className="dashboard"><header className="topbar"><div><span className="eyebrow">MŰVELETI ADATLAP</span><h1>{operationLabel(op.operation_type)}</h1><p>{farm?.name||"Gazdaság"} · {field?.name||"Földtábla"} · {op.country_code}</p></div><Link className="ghost-btn" href={profile?.role==="advisor"?"/admin/operations":"/operations"}>Vissza a naplóhoz</Link></header>
 <section className="panel" data-help-block="operation-detail"><div className="panel-heading"><div><span className="eyebrow">RÖGZÍTETT ADATOK</span><h2>Végleges műveleti adatlap</h2></div><div style={{display:"flex",gap:8,alignItems:"center"}}><span className="user-pill">{op.approval_status==="approved"?"Jóváhagyva":op.approval_status==="pending"?"Jóváhagyásra vár":"Nem jóváhagyásköteles"}</span><BlockHelpButton label="A műveleti adatlap magyarázata" content={{title:"Végleges műveleti adatlap",body:"Ez az oldal egy konkrét rögzített agrár művelet részletes adatait mutatja: dátum, tábla, kezelt terület, végrehajtó, anyag vagy munkafolyamat, kultúra, cél, dózis, gép és jóváhagyási állapot.",important:"Növényvédelmi műveletnél külön ellenőrizd a hivatalos maximális dózist, az engedélyszámot, a forgalmi kategóriát és a jóváhagyási állapotot. A Jóváhagyva státusz csak azt mutatja, hogy a rendszerben megtörtént a gazdasági jóváhagyás; a tényleges kijuttatásnak minden hatályos feltételnek meg kell felelnie.",example:"Példa: egy permetezési műveletnél itt ellenőrzöd, milyen dózissal, melyik táblán, ki által és milyen jóváhagyási státusszal került rögzítésre a kezelés.",steps:["Ellenőrizd a művelet dátumát és földtábláját.","Nézd meg a kezelt területet és a végrehajtót.","Anyaghasználatnál ellenőrizd a készítményt, kultúrát, célt és dózist.","Vesd össze a dózist a hivatalos maximummal.","Engedélyköteles esetben ellenőrizd a jóváhagyó személyt és az állapotot.","Ha kérdés merül fel egy változtatásról, nézd meg az auditnaplót is."]}}/></div></div><div className="field-meta"><span><b>{op.operation_date}</b><small>Dátum</small></span><span><b>{field?.name||"—"}</b><small>Földtábla</small></span><span><b>{op.treated_area??"—"} ha</b><small>Kezelt terület</small></span><span><b>{op.operator_name||"—"}</b><small>Végrehajtó</small></span></div><div className="field-meta"><span><b>{op.product_name||op.subtype||"—"}</b><small>Anyag / munkafolyamat</small></span><span><b>{op.crop||"—"}</b><small>Kultúra</small></span><span><b>{op.target||"—"}</b><small>Cél</small></span><span><b>{op.dose!=null?`${op.dose} ${op.dose_unit||""}`:"—"}</b><small>Dózis</small></span></div>{op.official_dose_max!=null&&<p>Hivatalos maximális dózis: <b>{op.official_dose_max} {op.dose_unit||""}</b></p>}{op.authorization_number&&<p>Termék engedélyszáma: <b>{op.authorization_number}</b></p>}{op.regulatory_category&&<p>Forgalmi kategória: <b>{op.regulatory_category}.</b></p>}{op.machine_name&&<p>Gép: <b>{op.machine_name}</b></p>}{op.weather&&<p>Időjárás: <b>{op.weather}</b></p>}{op.notes&&<p>Megjegyzés: {op.notes}</p>}{op.approval_required&&<p>Gazdasági jóváhagyó: <b>{op.approver_name||"kijelölve"}</b> · állapot: <b>{op.approval_status}</b>{op.approved_at?` · ${huDate(op.approved_at)}`:""}</p>}</section>
 <section className="panel" data-help-block="operation-audit"><div className="panel-heading"><div><span className="eyebrow">AUDIT NAPLÓ</span><h2>Módosítási és jóváhagyási történet</h2></div><BlockHelpButton label="Az auditnapló magyarázata" content={{title:"Műveleti auditnapló",body:"Az auditnapló időrendben megőrzi a művelet létrehozásához, módosításához és jóváhagyásához kapcsolódó rendszereseményeket.",important:"Ha egy már jóváhagyott művelet lényeges adata módosul, a korábbi jóváhagyás érvénytelenné válhat. Ilyenkor új ellenőrzésre és jóváhagyásra lehet szükség.",example:"Példa: a művelet dózisát módosítják. Az auditnapló megmutatja a módosítás időpontját és felhasználóját, majd külön bejegyzés jelenhet meg a korábbi jóváhagyás érvénytelenítéséről.",steps:["Keresd meg a legfrissebb auditbejegyzést.","Nézd meg, ki és mikor hajtotta végre a műveletet.","Módosítás esetén ellenőrizd a felsorolt megváltozott mezőket.","Figyeld, történt-e jóváhagyásra küldés, jóváhagyás vagy érvénytelenítés.","Eltérés esetén hasonlítsd össze a jelenlegi műveleti adatlapot az audit történetével."]}}/></div>{audit?.length?<div className="inspection-list">{audit.map(a=><article className="inspection-card" key={a.id}><div className="inspection-head"><div><strong>{auditLabel[a.action]||a.action}</strong><small>{huDate(a.changed_at)} · {a.changed_by?actorMap.get(a.changed_by)||"Felhasználó":"Rendszer"}</small></div></div>{a.changed_fields?.length>0&&<p>Módosított mezők: {a.changed_fields.join(", ")}</p>}</article>)}</div>:<div className="empty-state">Ehhez a korábbi művelethez még nincs auditbejegyzés. Az auditnapló a v1.0 lezárásától kezdve készül.</div>}</section>
 </main></div>;
}