"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {BlockHelpButton} from "@/components/GuidedTour";
import {acceptPendingFarmMemberships} from "./actions";

export default function InvitePage(){const[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[ready,setReady]=useState(false),[inviteEmail,setInviteEmail]=useState("");const router=useRouter();
 useEffect(()=>{let active=true;(async()=>{const supabase=createClient();setReady(false);setError("");const hash=new URLSearchParams(window.location.hash.replace(/^#/,"")),accessToken=hash.get("access_token"),refreshToken=hash.get("refresh_token"),type=hash.get("type"),code=new URL(window.location.href).searchParams.get("code");if(!accessToken&&!code){if(active)setError("Érvénytelen vagy hiányos meghívó link. Nyisd meg újra a meghívó e-mailből.");return}try{await supabase.auth.signOut({scope:"local"});let sessionUserEmail="";if(accessToken&&refreshToken){if(type&&type!=="invite"&&type!=="signup"&&type!=="recovery")throw new Error("A link típusa nem használható fiókaktiválásra.");const{data,error:sessionError}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(sessionError||!data.session?.user)throw new Error(sessionError?.message||"A meghívó munkamenet nem hozható létre.");sessionUserEmail=data.session.user.email||""}else if(code){const{data,error:exchangeError}=await supabase.auth.exchangeCodeForSession(code);if(exchangeError||!data.session?.user)throw new Error(exchangeError?.message||"A meghívó kód nem váltható munkamenetre.");sessionUserEmail=data.session.user.email||""}if(!sessionUserEmail)throw new Error("A meghívott felhasználó nem azonosítható.");if(active){setInviteEmail(sessionUserEmail);setReady(true)}window.history.replaceState({},document.title,"/invite")}catch(err){if(active){setError(err instanceof Error?`A meghívó feldolgozása sikertelen: ${err.message}`:"A meghívó feldolgozása sikertelen.");setReady(false)}}})();return()=>{active=false}},[]);
 async function handleSubmit(event:FormEvent){event.preventDefault();setError("");if(!ready){setError("A meghívó nincs érvényesen betöltve.");return}if(password.length<8){setError("A jelszó legalább 8 karakter legyen.");return}if(password!==confirmPassword){setError("A két jelszó nem egyezik.");return}setLoading(true);const supabase=createClient();const{data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user||(inviteEmail&&userData.user.email!==inviteEmail)){setLoading(false);setReady(false);setError("A meghívott felhasználó munkamenete nem érvényes. Nyisd meg újra a meghívó linket.");return}const{error:updateError}=await supabase.auth.updateUser({password});if(updateError){setLoading(false);setError(`A fiók aktiválása sikertelen: ${updateError.message}`);return}try{const result=await acceptPendingFarmMemberships();router.push(result.joined>0?"/work":"/dashboard");router.refresh()}catch(err){setLoading(false);setError(err instanceof Error?`A gazdasági hozzáférés aktiválása sikertelen: ${err.message}`:"A gazdasági hozzáférés aktiválása sikertelen.")}}
 return <main className="login-shell"><form className="login-card" onSubmit={handleSubmit}><div style={{display:"flex",justifyContent:"flex-end"}}><BlockHelpButton label="A fiókaktiválás magyarázata" content={{title:"Meghívott fiók aktiválása",body:"A meghívó e-mailből megnyitott oldalon állíthatod be az Agrár Mentor jelszavadat. A rendszer először ellenőrzi, hogy a meghívó link érvényes és valóban a meghívott e-mail-címhez tartozik.",important:"A jelszó legalább 8 karakter legyen, és a két mezőben pontosan egyezzen. Ha a rendszer érvénytelen vagy hiányos linket jelez, ne próbáld kézzel módosítani a címet; nyisd meg újra az eredeti meghívó e-mailből.",example:"Példa: munkatársként meghívást kapsz a gazdaságba. Megnyitod az e-mail linkjét, beállítod a jelszavadat, majd az aktiválás után a rendszer automatikusan a neked elérhető munkafelületre irányít.",steps:["Nyisd meg a meghívó e-mailben kapott linket.","Ellenőrizd, hogy a saját e-mail-címed jelenik meg meghívott fiókként.","Adj meg legalább 8 karakteres jelszót.","Írd be ugyanazt a jelszót még egyszer.","Nyomd meg a Fiók aktiválása gombot.","Sikeres aktiválás után a rendszer a szerepkörödnek megfelelő felületre irányít."]}}/></div><div className="brand-mark">AM</div><h1>Fiók aktiválása</h1><p>Állíts be jelszót az Agrár Mentor fiókodhoz.</p>{inviteEmail&&<div className="notice">Meghívott fiók: <strong>{inviteEmail}</strong></div>}{!ready&&!error&&<div className="notice">Meghívó ellenőrzése…</div>}{error&&<div className="error-box">{error}</div>}<label>Új jelszó<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required disabled={!ready}/></label><label>Új jelszó újra<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={8} required disabled={!ready}/></label><button className="btn btn-primary full" disabled={loading||!ready}>{loading?"Aktiválás…":"Fiók aktiválása"}</button></form></main>}
