"use client";

import {FormEvent,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {BlockHelpButton} from "@/components/GuidedTour";

function safeNext(value:string|null){if(!value||!value.startsWith("/")||value.startsWith("//"))return null;return value}

export default function LoginPage(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
 async function handleSubmit(event:FormEvent){event.preventDefault();setLoading(true);setError("");setMessage("");const supabase=createClient();const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setLoading(false);setError(`Sikertelen belépés: ${error.message}`);return}const requestedNext=safeNext(new URLSearchParams(window.location.search).get("next"));const target=requestedNext||"/dashboard";window.location.assign(`/mfa?next=${encodeURIComponent(target)}`)}
 async function handleRecovery(){setError("");setMessage("");if(!email){setError("Add meg előbb az e-mail címedet.");return}setLoading(true);const supabase=createClient();const origin=window.location.origin;const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${origin}/reset-password`});setLoading(false);if(error){setError(`A visszaállító e-mail küldése sikertelen: ${error.message}`);return}setMessage("Elküldtük a jelszó-visszaállító e-mailt. Ellenőrizd a beérkező leveleket és a spam mappát is.")}
 return <main className="login-shell"><form className="login-card" onSubmit={handleSubmit}><div style={{display:"flex",justifyContent:"flex-end"}}><BlockHelpButton label="A biztonságos belépés magyarázata" content={{title:"Belépés kétfaktoros védelemmel",body:"A jelszó megadása után az Agrár Mentor külön authenticator-kódot is kér. A gazdasági adatok csak a második faktor sikeres ellenőrzése után érhetők el.",important:"Az authenticator kódját és beállítási kulcsát soha ne add át másnak. Ha valaki csak a jelszavadat szerzi meg, a második faktor nélkül nem kap hozzáférést a védett adatokhoz.",steps:["Add meg az e-mail-címedet és a jelszavadat.","Első használatkor olvasd be a megjelenő QR-kódot az authenticator alkalmazásba.","Írd be a 6 jegyű kódot.","Sikeres ellenőrzés után nyílik meg az Agrár Mentor.","Elfelejtett jelszó esetén használd a visszaállító e-mailt."]}}/></div><div className="brand-mark">AM</div><h1>Agrár Mentor</h1><p>Biztonságos belépés az ügyfélportálra</p><label>E-mail cím<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Jelszó<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}<button className="btn btn-primary full" disabled={loading}>{loading?"Belépés…":"Belépés"}</button><button type="button" className="btn full" onClick={handleRecovery} disabled={loading}>Elfelejtett jelszó</button></form></main>
}
