import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Sidebar} from "@/components/Sidebar";
import {FarmerTopbar} from "@/components/FarmerTopbar";
import {BlockHelpButton} from "@/components/GuidedTour";
import {savePlantProtectionApprover,deactivatePlantProtectionApprover} from "./plant-protection-actions";

export default async function FarmsPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role,system_role,full_name").eq("id",user.id).maybeSingle();if(profile?.system_role==="admin")redirect("/system-admin");if(profile?.role==="advisor")redirect("/admin/clients");
 const{data:farms,error}=await supabase.from("farms").select("id,name,settlement,address,owner_id,created_at").order("created_at",{ascending:true});if(error)throw new Error(error.message);const farmIds=(farms??[]).map(f=>f.id);
 const[{data:fields},{data:tasks},{data:members},{data:authorizations}]=farmIds.length?await Promise.all([
  supabase.from("fields").select("id,name,farm_id,area_ha,current_crop,crop_year,status").in("farm_id",farmIds).eq("status","active").order("created_at",{ascending:true}),
  supabase.from("tasks").select("id,farm_id,status").in("farm_id",farmIds).eq("assigned_to",user.id),
  supabase.from("farm_members").select("farm_id,user_id,member_role,active").in("farm_id",farmIds).eq("active",true),
  supabase.from("farm_plant_protection_approvers").select("id,farm_id,user_id,authorization_level,permit_number,valid_until,active").in("farm_id",farmIds).eq("active",true),
 ]):[{data:[]},{data:[]},{data:[]},{data:[]}];
 const memberIds=Array.from(new Set([user.id,...(farms??[]).map(f=>f.owner_id),...(members??[]).map(m=>m.user_id)]));const{data:people}=memberIds.length?await supabase.from("profiles").select("id,full_name,role").in("id",memberIds):{data:[]};const{data:licenses}=memberIds.length?await supabase.from("profile_plant_protection_licenses").select("user_id,authorization_level,permit_number,valid_until,active").in("user_id",memberIds).eq("active",true):{data:[]};const peopleMap=new Map((people??[]).map(p=>[p.id,p])),licenseMap=new Map((licenses??[]).map(l=>[l.user_id,l]));
 const totalArea=(fields??[]).reduce((sum,field)=>sum+(Number(field.area_ha)||0),0),openTasks=(tasks??[]).filter(task=>task.status!=="done").length;
 return <div className="app-shell farmer-app"><Sidebar active="farms" userName={profile?.full_name||"Gazdálkodó"}/><main className="dashboard"><FarmerTopbar userName={profile?.full_name||"Gazdálkodó"}/><header className="topbar"><div><span className="eyebrow">GAZDASÁGI ÁTTEKINTÉS</span><h1>Gazdaságom</h1><p>A gazdaságok, földterületek és a gazdaság saját növényvédelmi jogosultságai.</p></div><BlockHelpButton label="A Gazdaságom oldal magyarázata" content={{title:"Gazdasági áttekintés",body:"A Gazdaságom oldal a saját gazdaságaid, földtábláid, nyitott teendőid és növényvédelmi jogosult személyeid központi áttekintő felülete.",important:"A gazdasági alapadatokat és a földtáblákat a szaktanácsadóval együtt érdemes pontosan karbantartani, mert ezekre épül a műveleti napló, a térkép, a teendők és a jóváhagyási rendszer.",example:"Példa: egy gazdaságodhoz három földtábla tartozik. Innen gyorsan látod az összterületet, a nyitott teendők számát és a kijelölt növényvédelmi jóváhagyót, majd egy kattintással megnyithatod az érintett táblát.",steps:["Ellenőrizd a gazdaságok és földtáblák számát.","Nézd meg az összterületet és a nyitott teendőket.","A Földtáblák blokkban nyisd meg a szükséges területet.","A növényvédelmi felelősség résznél ellenőrizd a jogosult személyeket és azok érvényességét."]}}/></header>
 <section className="stats-grid" data-help-block="farm-summary" style={{position:"relative"}}><div style={{position:"absolute",right:8,top:8,zIndex:2}}><BlockHelpButton label="A gazdasági összesítők magyarázata" content={{title:"Gazdasági összesítők",body:"A négy kártya a saját gazdaságaid számát, a hozzájuk tartozó földtáblákat, ezek összterületét és a rád váró nyitott teendőket foglalja össze.",important:"A Nyitott teendők száma a még nem elvégzett, hozzád rendelt feladatokat jelzi; nem az összes gazdasági munkát."}}/></div><article className="stat-card"><span>Gazdaságok</span><strong>{farms?.length??0}</strong><small>Nyilvántartott gazdaság</small></article><article className="stat-card"><span>Földtáblák</span><strong>{fields?.length??0}</strong><small>Összes földtábla</small></article><article className="stat-card"><span>Összterület</span><strong>{totalArea.toLocaleString("hu-HU",{maximumFractionDigits:2})} ha</strong><small>Nyilvántartott terület</small></article><article className="stat-card"><span>Nyitott teendők</span><strong>{openTasks}</strong><small>Elvégzésre vár</small></article></section>
 <section className="dashboard-grid lower"><article className="panel" data-help-block="farm-details"><div className="panel-heading"><div><span className="eyebrow">GAZDASÁGOK</span><h2>Gazdasági adatok</h2></div><BlockHelpButton label="A gazdasági adatok magyarázata" content={{title:"Gazdasági adatok",body:"Itt gazdaságonként látod a nevet, települést, címet, a hozzá tartozó földtáblák számát és területét, valamint a nyitott teendők számát.",important:"Ez áttekintő blokk: a szakmai munka továbbra is a konkrét földtábla, feladat vagy művelet saját adatlapján történik."}}/></div>{farms?.length?<div className="inspection-list">{farms.map(farm=>{const farmFields=(fields??[]).filter(field=>field.farm_id===farm.id),area=farmFields.reduce((sum,field)=>sum+(Number(field.area_ha)||0),0);return <article className="inspection-card" key={farm.id}><div className="inspection-head"><div><strong>{farm.name}</strong><small>{farm.settlement||"Település nincs megadva"}</small></div><span className="field-total">{farmFields.length} tábla</span></div>{farm.address&&<p>{farm.address}</p>}<div className="field-meta"><span><b>{area.toLocaleString("hu-HU",{maximumFractionDigits:2})} ha</b><small>Terület</small></span><span><b>{farmFields.length}</b><small>Táblák</small></span><span><b>{(tasks??[]).filter(task=>task.farm_id===farm.id&&task.status!=="done").length}</b><small>Nyitott teendő</small></span></div></article>})}</div>:<div className="empty-state">Még nincs gazdaság rögzítve.</div>}</article>
 <article className="panel" data-help-block="farm-fields"><div className="panel-heading"><div><span className="eyebrow">GYORS ELÉRÉS</span><h2>Földtáblák</h2></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Link className="ghost-btn" href="/fields">Összes tábla</Link><BlockHelpButton label="A földtáblák gyorselérés magyarázata" content={{title:"Földtáblák – gyors elérés",body:"A legelső földtáblákat közvetlenül innen nyithatod meg. A kártyákon a tábla neve, aktuális kultúrája, területe és termesztési éve látható.",important:"Ez csak gyorslista. Ha több táblád van, az Összes tábla gombbal a teljes földtábla-nyilvántartás nyílik meg."}}/></div></div>{fields?.length?<div className="field-overview-grid">{fields.slice(0,6).map(field=><Link className="field-card field-card-link" href={`/fields/${field.id}`} key={field.id}><div className="field-card-top"><span className="field-icon">{field.name.slice(0,1).toUpperCase()}</span><div><strong>{field.name}</strong><small>{field.current_crop||"Nincs kultúra megadva"}</small></div><span className="field-arrow">→</span></div><div className="field-meta"><span><b>{field.area_ha?`${field.area_ha} ha`:"—"}</b><small>Terület</small></span><span><b>{field.crop_year||new Date().getFullYear()}</b><small>Év</small></span></div></Link>)}</div>:<div className="empty-state">Még nincs földtábla rögzítve.</div>}</article></section>
 <section className="panel" data-help-block="plant-protection-approvers"><div className="panel-heading"><div><span className="eyebrow">NÖVÉNYVÉDELMI FELELŐSSÉG</span><h2>Gazdasági jóváhagyók</h2><p>A növényvédelmi jogosultság a személy saját profiljához tartozik. Itt a gazdaság csak kijelöli a már érvényes jogosultsággal rendelkező személyt.</p></div><BlockHelpButton label="A növényvédelmi jóváhagyók magyarázata" content={{title:"Gazdasági növényvédelmi jóváhagyók",body:"A személy a saját profiljában rögzíti a növényvédelmi jogosultságát. A gazdaság tulajdonosa itt csak kijelöli az aktív, nem lejárt jogosultsággal rendelkező gazdasági személyt.",important:"A szaktanácsadó nem lehet gazdasági növényvédelmi jóváhagyó. Lejárt vagy hiányos személyes jogosultsággal senki nem választható ki."}}/></div>
{(farms??[]).map(farm=>{const farmMemberIds=(members??[]).filter(m=>m.farm_id===farm.id).map(m=>m.user_id),candidateIds=Array.from(new Set([farm.owner_id,...farmMemberIds])),today=new Date().toISOString().slice(0,10),candidates=candidateIds.map(id=>peopleMap.get(id)).filter((p):p is NonNullable<typeof p>=>{if(!p||p.role==="advisor")return false;const l=licenseMap.get(p.id);return !!l&&l.active&&!!l.valid_until&&l.valid_until>=today}),active=(authorizations??[]).filter(a=>a.farm_id===farm.id),canManage=farm.owner_id===user.id;return <article key={farm.id} style={{padding:"18px 0",borderTop:"1px solid #e8eee8"}}><h3 style={{margin:"0 0 10px"}}>{farm.name}</h3>{active.length?<div className="inspection-list">{active.map(a=>{const person=peopleMap.get(a.user_id),license=licenseMap.get(a.user_id);return <div className="inspection-card" key={a.id}><div className="inspection-head"><div><strong>{person?.full_name||"Gazdasági jogosult"}</strong><small>{license?license.authorization_level+". kategória · "+license.permit_number:"Személyes jogosultság nem elérhető"}</small></div><span className="field-total">{license?.valid_until?"Érvényes: "+license.valid_until:"Ellenőrizendő"}</span></div>{canManage&&<form action={deactivatePlantProtectionApprover}><input type="hidden" name="id" value={a.id}/><button className="ghost-btn" type="submit">Kijelölés megszüntetése</button></form>}</div>})}</div>:<div className="empty-state">Ehhez a gazdasághoz még nincs kijelölt növényvédelmi jóváhagyó.</div>}{canManage?<>{candidates.length?<form action={savePlantProtectionApprover} className="admin-form" style={{marginTop:16}}><input type="hidden" name="farm_id" value={farm.id}/><label>Érvényes jogosultságú személy<select name="user_id" required><option value="">Válassz személyt</option>{candidates.map(p=>{const l=licenseMap.get(p.id)!;return <option value={p.id} key={p.id}>{(p.full_name||"Gazdasági felhasználó")+" · "+l.authorization_level+". kategória · érvényes: "+l.valid_until}</option>})}</select></label><button className="btn btn-primary" type="submit">Jóváhagyó kijelölése</button></form>:<p style={{margin:"14px 0 0",fontSize:12,color:"#6f7c74"}}>Nincs olyan gazdasági személy, akinek a saját profiljában aktív és érvényes növényvédelmi jogosultság szerepel.</p>}</>:<p style={{margin:"14px 0 0",fontSize:12,color:"#6f7c74"}}>Ezt a gazdaságot munkatársként látod; a jóváhagyó kijelölését a gazdaság tulajdonosa kezeli.</p>}</article>})}</section>
 </main></div>;
}
