"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

function text(v:FormDataEntryValue|null,max:number){return String(v||"").trim().slice(0,max)}
function uuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}

async function ownerContext(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role==="advisor")throw new Error("A szaktanácsadó nem kezelheti a gazdaság növényvédelmi jóváhagyóit.");return{supabase,user}}

export async function savePlantProtectionApprover(formData:FormData){const{supabase,user}=await ownerContext();const farmId=text(formData.get("farm_id"),100),personId=text(formData.get("user_id"),100),level=text(formData.get("authorization_level"),4).replace(".","").toUpperCase(),permitNumber=text(formData.get("permit_number"),120),validUntil=text(formData.get("valid_until"),10);if(!uuid(farmId)||!uuid(personId))throw new Error("Érvénytelen gazdaság vagy személy.");if(level!=="I"&&level!=="II")throw new Error("I. vagy II. kategóriájú jogosultság választható.");if(!permitNumber)throw new Error("Az engedély/igazolvány számát meg kell adni.");if(!/^\d{4}-\d{2}-\d{2}$/.test(validUntil))throw new Error("Az engedély érvényességi dátuma kötelező.");if(validUntil<new Date().toISOString().slice(0,10))throw new Error("Lejárt jogosultság nem állítható be aktív jóváhagyónak.");const{data:farm}=await supabase.from("farms").select("id,owner_id").eq("id",farmId).maybeSingle();if(!farm||farm.owner_id!==user.id)throw new Error("Csak a saját gazdaságod jogosult személyeit kezelheted.");const{data:person}=await supabase.from("profiles").select("id,role").eq("id",personId).maybeSingle();if(!person||person.role==="advisor")throw new Error("Szaktanácsadó nem jelölhető gazdasági jóváhagyónak.");if(personId!==farm.owner_id){const{data:member}=await supabase.from("farm_members").select("id,active").eq("farm_id",farmId).eq("user_id",personId).eq("active",true).maybeSingle();if(!member)throw new Error("A kijelölt személy nem aktív tagja ennek a gazdaságnak.")}
 const{error}=await supabase.from("farm_plant_protection_approvers").upsert({farm_id:farmId,user_id:personId,authorization_level:level,permit_number:permitNumber,valid_until:validUntil,active:true,created_by:user.id,updated_at:new Date().toISOString()},{onConflict:"farm_id,user_id"});if(error)throw new Error(error.message);revalidatePath("/farms");revalidatePath("/operations")}

export async function deactivatePlantProtectionApprover(formData:FormData){const{supabase,user}=await ownerContext();const id=text(formData.get("id"),100);if(!uuid(id))throw new Error("Érvénytelen jogosultság.");const{data:row}=await supabase.from("farm_plant_protection_approvers").select("id,farm_id").eq("id",id).maybeSingle();if(!row)throw new Error("A jogosultság nem található.");const{data:farm}=await supabase.from("farms").select("owner_id").eq("id",row.farm_id).maybeSingle();if(!farm||farm.owner_id!==user.id)throw new Error("Nincs jogosultságod ehhez a gazdasághoz.");const{error}=await supabase.from("farm_plant_protection_approvers").update({active:false,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/farms");revalidatePath("/operations")}
