import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Sidebar} from "@/components/Sidebar";
import {BlockHelpButton} from "@/components/GuidedTour";
import {farmMemberRoleLabel} from "@/lib/farmMembers";
import {machineTypeLabel} from "@/lib/machinery";
import {dispatchTask} from "./actions";

export default async function DispatchPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role,system_role,full_name").eq("id",user.id).maybeSingle();if(profile?.system_role==="admin")redirect("/system-admin");if(profile?.role==="advisor")redirect("/admin/tasks");
 const[{data:owned},{data:managedMemberships}]=await Promise.all([supabase.from("farms").select("id,name,owner_id").eq("owner_id",user.id),supabase.from("farm_members").select("farm_id,member_role").eq("user_id",user.id).eq("active",true).in("member_role",["manager","agronomist"])]);
 const managedIds=(managedMemberships??[]).map(m=>m.farm_id);const{data:managedFarms}=managedIds.length?await supabase.from("farms").select("id,name,owner_id").in("id",managedIds):{data:[]};const farms=[...(owned??[]),...(managedFarms??[]).filter(f=>!(owned??[]).some(o=>o.id===f.id))];if(!farms.length)redirect("/work");const farmIds=farms.map(f=>f.id);
 const[{data:fields},{data:members},{data:tasks},{data:machines}]=await Promise.all([supabase.from("fields").select("id,name,farm_id,current_crop,area_ha").in("farm_id",farmIds).order("name"),supabase.from("farm_members").select("id,farm_id,user_id,member_role,active").in("farm_id",farmIds).eq("active",true),supabase.from("tasks").select("id,title,due_date,status,priority,farm_id,field_id,assigned_to,created_at").in("farm_id",farmIds).order("created_at",{ascending:false}).limit(80),supabase.from("machines").select("id,farm_id,name,machine_type,active,current_hours").in("farm_id",farmIds).eq("active",true).order("name")]);
 const taskIds=(tasks??[]).map(t=>t.id);const{data:assignments}=taskIds.length?await supabase.from("task_machine_assignments").select("task_id,machine_id").in("task_id",taskIds):{data:[]};
 const ids=[...new Set([...(members??[]).map(m=>m.user_id),...farms.map(f=>f.owner_id)])];const{data:people}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]};const peopleMap=new Map((people??[]).map(p=>[p.id,p.full_name])),farmMap=new Map(farms.map(f=>[f.id,f])),fieldMap=new Map((fields??[]).map(f=>[f.id,f])),machineMap=new Map((machines??[]).map(m=>[m.id,m])),assignmentMap=new Map((assignments??[]).map(a=>[a.task_id,a.machine_id]));const active=(tasks??[]).filter(t=>t.status!=="done");
 return <div className="app-shell farmer-app"><Sidebar active="dispatch" userName={profile?.full_name||"Gazdálkodó"}/><main className="dashboard"><header className="topbar"><div><span className="eyebrow">MUNKASZERVEZÉS</span><h1>Munkakiosztás</h1><p>Konkrét földtáblára, munkatársra és gépre kiosztható munkák.</p></div><span className="user-pill">{active.length} nyitott munka</span></header>
 <section className="stats-grid" data-help-block="dispatch-summary" style={{position:"relative"}}><div style={{position:"absolute",right:8,top:8,zIndex:2}}><BlockHelpButton content={{title:"Munkakiosztási összesítő",body:"A négy kártya azt mutatja, hány kezelt gazdaságban oszthatsz ki munkát, hány aktív munkatárs és gép választható, illetve hány nyitott munka vár még végrehajtásra.",important:"A Nyitott munkák száma minden olyan kiosztott feladatot tartalmaz, amely még nincs elvégezve."}}/></div><article className="stat-card"><span>Kezelt gazdaság</span><strong>{farms.length}</strong><small>ahol kioszthatsz munkát</small></article><article className="stat-card"><span>Munkatársak</span><strong>{members?.length??0}</strong><small>aktív csapattag</small></article><article className="stat-card"><span>Aktív gépek</span><strong>{machines?.length??0}</strong><small>kiosztható eszköz</small></article><article className="stat-card"><span>Nyitott munkák</span><strong>{active.length}</strong><small>végrehajtásra vár</small></article></section>
 <section className="panel" data-help-block="dispatch-create"><div className="panel-heading"><div><span className="eyebrow">ÚJ MUNKA</span><h2>Feladat kiosztása</h2></div><BlockHelpButton content={{title:"Feladat kiosztása",body:"Itt hozol létre konkrét munkát. Válaszd ki a gazdaságot és földtáblát, rendelj hozzá végrehajtót, szükség esetén gépet, majd add meg a feladat nevét, határidejét, prioritását és a végrehajtási utasítást.",important:"A gép opcionális. A gazdaság, földtábla és végrehajtó együtt határozza meg, hol és kinek kell a munkát elvégeznie.",example:"Például: Nagyrét 03. tábla → kijelölt munkatárs → tárcsa → Tarlóhántás → sürgős → 12 cm mélység, teljes területen."}}/></div><form action={dispatchTask} className="admin-form task-create-grid"><label>Gazdaság<select name="farm_id" required><option value="">Válassz gazdaságot</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Földtábla<select name="field_id" required><option value="">Válassz táblát</option>{fields?.map(f=><option key={f.id} value={f.id}>{farmMap.get(f.farm_id)?.name} — {f.name}</option>)}</select></label><label>Munkatárs<select name="assigned_to" required><option value="">Válassz végrehajtót</option>{farms.map(f=><option key={`owner-${f.id}`} value={f.owner_id}>{f.name} — {peopleMap.get(f.owner_id)||"Tulajdonos"} (tulajdonos)</option>)}{members?.map(m=><option key={m.id} value={m.user_id}>{farmMap.get(m.farm_id)?.name} — {peopleMap.get(m.user_id)||"Munkatárs"} ({farmMemberRoleLabel(m.member_role)})</option>)}</select></label><label>Gép / eszköz<select name="machine_id"><option value="">Nincs hozzárendelve</option>{machines?.map(m=><option key={m.id} value={m.id}>{farmMap.get(m.farm_id)?.name} — {m.name} ({machineTypeLabel(m.machine_type)})</option>)}</select></label><label>Feladat<input name="title" required placeholder="pl. Tarlóhántás"/></label><label>Határidő<input name="due_date" type="date"/></label><label>Prioritás<select name="priority"><option value="normal">Normál</option><option value="high">Fontos</option><option value="urgent">Sürgős</option></select></label><label className="task-description">Utasítás / megjegyzés<input name="description" placeholder="pl. 12 cm mélység, teljes területen"/></label><button className="btn btn-primary">Munka kiosztása</button></form></section>
 <section className="panel" data-help-block="dispatch-tracking"><div className="panel-heading"><div><span className="eyebrow">AKTUÁLIS MUNKÁK</span><h2>Végrehajtás követése</h2></div><BlockHelpButton content={{title:"Végrehajtás követése",body:"Ez a lista a már kiosztott munkákat mutatja. Soronként látható a feladat, a gazdaság és földtábla, a végrehajtó, a hozzárendelt gép, a határidő és az aktuális állapot.",important:"Az Elvégezve állapot a lezárt munkát, a Kiosztva állapot a még végrehajtásra váró munkát jelzi."}}/></div>{tasks?.length?<div style={{display:"grid",gap:9}}>{tasks.map(t=>{const field=fieldMap.get(t.field_id),farm=farmMap.get(t.farm_id),machine=machineMap.get(assignmentMap.get(t.id));return <article key={t.id} className="task-admin-row"><span className={`dot ${t.priority}`}/><div><strong>{t.title}</strong><small>{farm?.name} · {field?.name||"—"} · {peopleMap.get(t.assigned_to)||"Végrehajtó"}</small>{machine&&<small>Gép: {machine.name} · {machineTypeLabel(machine.machine_type)} · {machine.current_hours??"—"} üó</small>}</div><div><b>{t.due_date?new Date(`${t.due_date}T12:00:00`).toLocaleDateString("hu-HU"):"Nincs határidő"}</b><small>{t.status==="done"?"Elvégezve":"Kiosztva"}</small></div></article>})}</div>:<div className="empty-state">Még nincs kiosztott munka.</div>}</section>
 </main></div>
}
